### ISSUE TITLE
Stepping backwards up a waterfall dialog

### ISSUE THREAD

**Issue by jwiley84** [Microsoft/botbuilder-dotnet#1006]
Problem:
Working on a bot with waterfall dialogs. The bot goes DOWN a waterfall exactly as expected, however, I was wondering if there was a way to step back up the waterfall a step.

Possible Solution:
Bot asks question 1 using prompt.
User answers.
Bot asks to confirm answer.
User negates.
Bot repeats question 1.
User answers
Bot asks to confirm answer
User confirms.
Bot asks questions 2 using prompt 
(etc)

Describe alternatives:
Attempted to use .ReplaceDialog(), but that resets the entire dialog step. Currently testing overriding the 'NextAsync'.

**Comment by johnataylor** [comment]
The notion of going forward is pretty much baked in. See code in the Resume and the private RunStep. The increment is done in the Resume and the boundary check is done in the RunStep.

However, it would not be too difficult to create your own backward waterfall - as long as you can decide what the semantics of that actually mean.

Anyhow checkout the sample "Custom-Dialog" which is basically a waterfall style abstraction but one running off of a dictionary rather than a list.
