### ISSUE TITLE
DCR: Revise HTTP response characteristics

### ISSUE THREAD

**Issue by dandriscoll** [Microsoft/botbuilder-dotnet#1009]
This change was motivated by an observation about inconsistent HTTP response codes between SDK languages. When we dug in, we found some improvements we could make to the SDK's HTTP response behavior.

Discussed with @johnataylor and came up with the right HTTP behavior:
- SDK accepts an Activity for processing and loads state
- SDK processes Activity and makes decisions about what to do next (sometimes this is immediate, for example, issuing a prompt; sometimes this is deferred, for example kicking off a background request that could take ~60 seconds to complete)
- SDK commits state
- SDK issues HTTP 200 OK
- SDK sends conversational replies in the background

The delta from the current v4 implementation is:
1. All SDKs return 200 OK instead of 202 Accepted
2. All SDKs perform conversational replies in the background

**Comment by drub0y** [comment]
It seems to me that if you intend to "eventually" reply (i.e. "perform conversational replied in the background") that should mean you're returning a `202 Accepted`, not a `200 OK`.

Also, what are the actual runtime implications here? For example, on the .NET side, this is executing in the scope of an ASP.NET request pipeline. The only way to end the response would be to push the actual bot execution off to a background thread pool. In Node, I'm sure it's going to be server implementation dependent, but it looks like Restify has a similar limitation. This of course makes sense because HTTP is a request/response style protocol and the frameworks are designed around that.

Finally, don't forget about the special `Invoke` activity type which _requires_ the bot to actually respond with a payload in the response body and, thus, also with a `200 OK` status. So you'd have to have some kind of dual mode support if you wanted to switch all non-`Invoke` activity processing to this new "background" approach.

**Comment by dandriscoll** [comment]
The key definition for me is what constitutes *processing* a request. We settled on it covering these steps: accepting the request, loading state and validating it, and committing the conversational state and any background APIs. This is a pretty clean definition of processed and maps well with retry characteristics.

At this point, responsibility for any long-running tasks and communicating back to the user is transferred to the bot (and not the caller). We exclude this from the definition of *processing* because it occurs after the state transition has been committed, and because including it has weird side-effects like seeing replies before a request was acknowledged.

The characteristics for `invoke` are defined within the protocols that build on it, and are exempt from this change as you point out.

**Comment by johnataylor** [comment]
And to clarify the phrase "in the background" in this context means the last two steps as listed are essentially interchangeable. The client (acting as a server) will accept the activities at any point whether it has received the HTTP response yet or not. At this level, the back to back HTTP exchanges are independent.

An implementation is free to send activities before, after or concurrently with the 200. The point is that even if one of these were to fail the bot should still reply 200. The only thing to read from the sequence as described is that the 200 is send as an acknowledgment that the state has been updated.

What this means is in any end to end inconsistencies introduced would be solved at a higher level.

Saying that an implementation may choose to buffer the output of the processing until after the state is updated allows for improved behavior when the bot is deployed in a scale out scenario. For example, it might choose to use an eTag precondition check on its state update and then if this check were to fail it would retry its work. It would do this before sending the 200. Of course such behavior also means any downstream services its processing depends on plays by the same (idempotent) rules.

As @dandriscoll says some scenarios are exempt. @stevenic describes a "Expense Report Workflow" scenario working with Slack channels. In this case buffering messages is made difficult because responses from the channel need to be processed and included in state during the turn. This scenario includes Adaptive Cards, the buffering behavior discussed here involves Dialogs. These scenarios are mutually exclusive anyhow.

Related to this is the long running workflow scenario. For example, a message sent by the bot to a reservation booking service. This might take several minutes to complete. There should be no expectation here that the inbound HTTP is kept hanging for this time. This scenario requires other support, for example, the application might chose to use durable message queuing technology.

**Comment by sgellock** [comment]
the fix is a PR from @Stevenic that is out for review
