### ISSUE TITLE
Timex converter

### ISSUE THREAD

**Issue by thomasmartinsen** [Microsoft/botbuilder-dotnet#1050]
It seems that the Timex dates coming from LUIS datetimeV2 is not handled in the latest version and the helper classes are not available anymore?

**Comment by johnataylor** [comment]
Can you include an example of something that wasn't handled correctly?

Please include enough details for me to repo. Thanks.

We realized that some locales that were serving up datetime (not the datetimeV2) were failing with the new client bits, and we've fixed that bug in the next release. If I remember correctly I think it was Spanish.

Also we have a new library that is designed to help you deal with TIMEX expressions. This is new, and the documentation and samples are way behind. However, there are a bunch of unit tests that can serve as usable samples to get you going if you are interested:

https://github.com/Microsoft/Recognizers-Text/tree/master/.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression

The NuGet package is here:

https://www.nuget.org/packages/Microsoft.Recognizers.Text.DataTypes.TimexExpression/

The aim of this library is to allow you to take a raw TIMEX expression and get DateTime objects and natural language from it. The TIMEX expression coming back from LUIS also includes a type (as in timespan, time, date, datetime etc. etc.) the code can infer these from the expression. You can then write code that switches on that inferred type.

Another thing the library does is allow you to evaluate a TIMEX expression against some constraints. For example, you might have a set of two TIMEX expressions that capture the natural language utterance "Wednesday 4 o'clock" this could be any Wednesday and it could be 4am or 4pm.

Incidentally there are two TIMEX expressions in this example because TIMEX can represent ambiguity in the date part but not the time part. So in the case of ambiguous time LUIS returns multiple expressions.

I say "LUIS" but you can get this exact same behavior running the DateTime Recognizer locally if you like.

So if you want a single _specific_ DateTime you would need to apply some constraints. The first constraint would be on the date part, specifically the week, and second constraint would be on the time part. Each of these constraints you express with a TIMEX expression.

The JavaScript version of this shows the usage better perhaps:

https://github.com/Microsoft/Recognizers-Text/blob/master/JavaScript/packages/datatypes-date-time/test/timexIntegrated.spec.js

If you think this looks like a good direction or not please do give feedback. As I say this is new.

**Comment by thomasmartinsen** [comment]
Thank you for the link to the library - I will check that out.

I came across the issue when updating the Contoso Cafe sample (https://github.com/Microsoft/BotFramework-Samples/tree/contosocafe-v4-dotnet/docs-samples/V4/dotnet/ContosoCafe/ContosoCafe-5-DialogsWithLUISEntities) to the latest release of the botframework.

**Comment by johnataylor** [comment]
In the DateTimePrompt the values from the underlying recognizer are copied across to the result. The code to do that is in a private function ReadResolution on that class:

https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs

(Note the way the result works is that you either get the value or you get the start and end depending on whether you have a range or note.)

So the code in the prompt looks good to me. (Given an assumption that you only care about the first entity.) However, this code doesn't seem to be there for the LUIS recognizer.

So are you using LUIS or the stand alone prompts?

And I see the LUIS recognizer does return the distinct TIMEX values so you should be able to create the full LUIS response using those with the library I pointed you at.

**Comment by johnataylor** [comment]
Two things, firstly we have #1060 tracking the bug in the parsing (i.e. the missing first/last in the values in the resolution). And secondly, because we think its actually better to base your bot logic on evaluation of the TIMEX expression we have a new sample:

https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/40.timex-resolution

Hopefully that is helpful.
