### ISSUE TITLE
DateTime Promp Validation loop used for refinement

### ISSUE THREAD

**Issue by MickH3** [Microsoft/botbuilder-dotnet#1063]
**DateTimePrompt needs ability to maintain context during validation loop, similar to Chronic**

The new DateTimePrompt in Bot Framework v4 SDK is great. The multi-language support we get from it being based on the same LUIS functionality is a nice improvement.

I was using Chronic before which did not have the language support, but did have a nice feature I think would be helpful during the validation loop in a Prompt dialog.

I am able to set a 'Clock' in the Chronic Parser that limits the scope of the next phrase I send it.
For example, if the user says "Next Week" the first time around and I then ask for which day of that week, and the user responds with "Tuesday". Chronic can be configured to parse the "Tuesday" in the context of the time span produced from "Next Week".

With the current DateTimePrompt, I would have to do this manually. It would be great to be able to feed a set of Start/End dates as a State object during a Retry Prompt as a way to *refine* the datetime as opposed to *replace* it.
 
I'm currently doing this manually, but it isn't complete parity with how Chronic worked so I've lost a little capability.  The multi-lingual support more than makes up for it, but would be great if this capability was built in.  Seems like a natural use of the validation mechanism on datetime prompts.

Thank you!

**Comment by johnataylor** [comment]
There are two aspects to this. Firstly the control flow. If you want to loop, retry etc. then you would do that within the dialogs framework. There are various solutions:

1) You could, for example, contain the DateTimePrompt within your own waterfall inside a derived ComponentDialog class.
1) Alternatively you could subclass Prompt and provide your own DateTimePrompt. You would be doing this because you want to break away from the validator function model and do something more sophisticated. You could use the existing DateTimePrompt as a starting point for your Prompt.
1) You could implement a full custom dialog. This is the least attractive solution as its the most complex. However, if you would like to do this take a look at the 19.Custom-Dialog sample:
https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/19.custom-dialogs

The other side of this problem is the resolution of the recognized data. DateTime recogniztion involves modeling ambiguity. For example, "Wednesday 4 o'clock" could be any Wednesday at 4AM or 4PM. The default behavior of LUIS (and the underlying recognizer) has been to go forward and backwards. Because here there is ambiguity in date and time you end out with four result. However, now we have a new library called TimexExpression that allows you to resolve the array of TIMEX values to a specific DateTime by applying constraints. For example, taking this text and constraining it to next week and afternoon would result in a single specific DateTime. This library is new and samples and documentation are lacking. However, the unit tests illustrate how it can be applied.

The package:

https://www.nuget.org/packages/Microsoft.Recognizers.Text.DataTypes.TimexExpression/

The source code:

https://github.com/Microsoft/Recognizers-Text/tree/master/.NET/Microsoft.Recognizers.Text.DataTypes.TimexExpression

And unit tests, that show some example usage:

https://github.com/Microsoft/Recognizers-Text/tree/master/.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests

In particular:

https://github.com/Microsoft/Recognizers-Text/blob/master/.NET/Microsoft.Recognizers.Text.DataTypes.DataDrivenTests/TestTimexResolver.cs

The model of constraints to "resolve" used in this library seems close to what you describe.

You might be able to get the behavior you want using this library inside the regular validator function. However, I suspect you want to alter the prompt text each iteration in a meaningful way - for example confirm the date part but ask for clarity on the time part. The regular DateTimePrompt might be too restrictive as all you get is the retry text.

**Comment by johnataylor** [comment]
Leaving this open as we need to provide samples and docs in this area.

**Comment by yochay** [comment]
Need a new sample and add a doc about time resolution.

**Comment by johnataylor** [comment]
We've added a new sample, hopefully this is helpful.

https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/40.timex-resolution

The LUIS Recognizer drops the start/end of a value. That should be fixed in 4.2 however, using the TIMEX in the long run should give better behavior.
