### ISSUE TITLE
DialogInstance --> Step property is missing

### ISSUE THREAD

**Issue by utkarsh24** [Microsoft/botbuilder-dotnet#1068]
I have used bot framework v4 preview for my project.

After upgrading to latest stable version 4.0.8 I found that the DialogInstance.Step property is missing.

DialogInsatnce preview class definition 

    public class DialogInstance
    {
        /// <summary>
        /// ID of the dialog this instance is for.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// The instances persisted state.
        /// </summary>
        public IDictionary<string, object> State { get; set; }

        /// <summary>
        /// Used when the instance is a Waterfall.
        /// </summary>
        public int Step { get; set; }
    }
}

and current class definition is 

    public class DialogInstance
    {
        /// <summary>
        /// Gets or sets the ID of the dialog this instance is for.
        /// </summary>
        /// <value>
        /// ID of the dialog this instance is for.
        /// </value>
        public string Id { get; set; }
        /// <summary>
        /// Gets or sets the instances persisted state.
        /// </summary>
        /// <value>
        /// The instances persisted state.
        /// </value>
        public IDictionary<string, object> State { get; set; }
    }

I am using step property for custom logic.

For Ex  if (dc.ActiveDialog.Step > 0) 
 

For waterfallContext I found that it has Index property which can be used as current dialog step..

Could you please suggest me what changes i need to make to work my existing code..

**Comment by johnataylor** [comment]
In the release version (4.0.6 upwards) the persisted step index is just held in the State dictionary. An example of that usage is in the private RunStepAsync function in the WaterfallDialog class.

This value is also available as the Index property on the WaterfallStepContext.

The point is the notion of an index, and the specific WaterfallStepContext class in particular, is specific to the WaterfallDialog class. Whereas the DialogInstance is a general across all dialogs. That's why you are seeing a general purpose property bag used in one place and the typed object model used in the other.

So if you have some existing code then, depending on what you are doing, you could put your values in that dictionary - as the WaterfallDialog does. Or if you are writing code that plugs into a Waterfall you could also consider the Values dictionary on the WaterfallStepContext.

This is an advanced scenario, but an example of a full custom dialog that uses the DialogInstance state directly is here:

https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/19.custom-dialogs

Take a look at the code in here for an example:

https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/19.custom-dialogs/Dialogs/SlotFillingDialog.cs

Hopefully that is helpful. And please direct future questions to Stack Overflow.

**Comment by utkarsh24** [comment]
thanks @johnataylor for your input.
for getting/setting current step from state dictionary i am using dc.ActiveDialog.State["stepIndex"]
