### ISSUE TITLE
ActivityType "Ping" AutoReply or CreatePingReponse()

### ISSUE THREAD

**Issue by Prybe** [Microsoft/botbuilder-dotnet#1074]
**Is your feature request related to a problem? Please describe.**
Yes, it is related to the problem that the ActivityType "Ping" is removed from v4 Bot.Schema.
Version 3 of BotBuilder had it and you could respond to it with a HttpMessage "200".

**Describe the solution you'd like**
If a Ping message is coming in, like from the Skype review process", I would prefer an autoreply.
I don´t want to implement the response by myself.
A Setting/Option would be very nice.

**Describe alternatives you've considered**
Using a middleware could be an Option.
Or bring back the ActivityType "Ping" + provide the "Activity.CreatePingReponse()" functionality.
Right now i was not able to implement a solution.
So a default solution should be given fot this.

**Additional context**
Screenshot from the Skype review process.

![image](https://user-images.githubusercontent.com/15085028/47781944-4956da00-dcff-11e8-9fed-1f7baa8fc506.png)

**Comment by jwiley84** [comment]
Hi @Prybe! 

I'll be reaching out to the skype team today to see what their approval process is going to consist of for v4 now that the ActivityType Ping has been removed. In the mean time, can I get your bot id? It's possible that what Skype called a 'ping' might have been something else, as the server error 500 could mean a number of things, but boils down to Skype trying to communicate with the bot and the bot simply not replying for one reason or another.

**Comment by Prybe** [comment]
The Id is 0696973a-7b0e-4833-9f17-f682b6d32b75.
Channels: Skype (not published), Telegram and FB Messenger are fine.

**Comment by jwiley84** [comment]
Hi Prybe!

One of our internal tools shows that on 10/23 there was a successful (HTTP 200) call from Skype to the bot, so I'm not sure what they received a HTTP 500 from. Your bot seems to be up and responsive, so I'm using another tool to try to narrow down what's going on.

**Comment by Prybe** [comment]
Yes. The bot is up and running. The communication works pretty good.
Only the review process or automated step before sends "something" which I cannot handle correctly.

**Comment by CoHealer** [comment]
Answered

**Comment by CoHealer** [comment]
@Prybe, reopening this for tracking will close [Skype] Botframework publishing review ping test failed #6

**Comment by jwiley84** [comment]
I think you meant https://github.com/Microsoft/BotBuilder-V3/issues/6, but it won't let me alter your comment. 

@Prybe I saw your comment on the above linked issue, and am looking into it now.

**Comment by CoHealer** [comment]
@Prybe, is this a repro of the issue you're seeing?

**Comment by Prybe** [comment]
yes it is.

**Comment by jwiley84** [comment]
Hi Prybe. I'm trying to track down the source of this by spinning up a skype bot and trying for approval myself to see if I can repro it. I haven't forgotten you!

**Comment by CoHealer** [comment]
@jwiley84, what's the current status?

**Comment by jwiley84** [comment]
Hi @Prybe!

Here's what I've come up with so far:

Despite 'Activity.Ping' being deprecated ages ago, it would seem that Skype is still trying to send this type of activity to the bot. I've reached out to some of the channel devs to see what's going to happen going forward, but I've come up with a suitable workaround for now:

Skype is looking for an activity that doesn't exist anymore, so I handled it in the OnTurnAsync method, specifically, in the turnContext check:

```
public async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            if (turnContext == null) { BOT CODE FOR ERRORS }
            if (turnContext.Activity.Type == ActivityTypes.Message) { BOT CODE FOR TALKING }  
            else if (turnContext.Activity.Type == ActivityTypes.ConversationUpdate) { BOT CODE FOR WELCOME IN NON-SKYPE }
            else if (turnContext.Activity.Type == ActivityTypes.ContactRelationUpdate) { BOT CODE FOR WELCOME IN SKYPE}

            //HERE'S WHERE IT WENT GOOGLY.
            else if (turnContext.Activity.Type == ActivityTypes.Event)
            {
                if (turnContext.Activity.ChannelId == "facebook")
                {
                    //handle ALL OTHER channel specific events here
                    await turnContext.SendActivityAsync($"{turnContext.Activity.Type} event detected", cancellationToken: cancellationToken);
                }
                else
                {
                    //handle skype with empty, because skype freaks out if you detect it's channel on the ping
                }
            }
            else
            {
                await turnContext.SendActivityAsync($"{turnContext.Activity.Type} event detected", cancellationToken: cancellationToken);
            }
```

Starting from the line "HERE'S WHERE IT WENT GOOGLY", I tracked that the ping was an event Activity Type, and if you have an if-check for `turnContext.Activity.Type == ActivityTypes.Event`, leaving it empty will result in Skype's ping succeeding. 

I went a step farther, however, because tying up an entire ActivityType just for one check is a bit silly. The Skype check WILL fail, if you try to do a channelId check for `turnContext.Activity.ChannelId == "skype"`. Possibly because the ping isn't coming from a channel, per se. I dunno. But if you see what I did above, where I did a check for a different channel, and then filtered all else down to an empty `else` block, the ping check succeeded.

It's not pretty and it's not elegant. But until I have a definitive answer on what Skype is doing and how we're handling it, it works as a work around.

**Comment by Prybe** [comment]
Wow. Thank you so much! Really! I will test it as soon as possible in my bot app.

**Comment by CoHealer** [comment]
Hey @Prybe, did the solution @jwiley84 work for you?

**Comment by CoHealer** [comment]
Closing with solution given. @Prybe, please let know if you think this should be readdressed.
