### ISSUE TITLE
Shouldn't BotFrameworkAdapter.ProcessActivityAsync be virtual

### ISSUE THREAD

**Issue by nimbusparis** [Microsoft/botbuilder-dotnet#1081]
While inherit from `BotFrameworkAdapter `and override `ProcessActivityAsync`, I saw that it was not `virtual `as other methods such as `SendActivitiesAsync`. Shouldn't it be `virtual`?

**Comment by johnataylor** [comment]
SendActivitiesAsync is virtual because it is overridden from the abstract class BotAdapter.

BotFrameworkAdapter wasn't explicitly intended for derivation in the same way, though there's nothing stopping you doing that: its not sealed

There is a new interface in 4.1. that defines exactly this method. See IAdapterIntegration.

With this interface you should be able to write something like this in theory:

class MyAdapter : BotFrameworkAdapter, IAdapterIntegration
{
    Task<InvokeResponse> IAdapterIntegration.ProcessActivityAsync(...)
    {
          // TODO your code
    }
}

And hopefully you find these new samples helpful:

This contains an example of defining your own adapter:

https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/42.scaleout

And this makes use of the new interface: 

https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/30.asp-mvc-bot 

If for some reason you prefer not to use ASP MVC, you can also use the new interface with dependency injection to plug your own custom adapter into the bot-builder integration pieces that shipped in 4.0.

So please take a quick look and if everything works for you please let us know and we'll close this issue.

**Comment by nimbusparis** [comment]
Thank you for your reply (and sample !), I've already inherit from BotFrameworkAdapter the method ProcessActivityAsync, it work but I got a warning since my method hide the base.
I'll perhaps consider to inherit from BotAdapter and forget all the stuff implemented by BotFrameworkAdapter (and that complicated my implementation !)
Perhaps a reference about the sample of custom adapter in documentation would help newbees (like me !) to implements his own adapter since the title of the sample is not meaningful ! 
About the DI of the adapter, I struggled a little since I wanted to use more modern DI engine like Autofac, but I finally put all the pieces together.
