### ISSUE TITLE
Right-Click / Publish in Visual Studio is broken

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#1085]
Right-Click / Publish in VS results in a Internal Server Error / HTTP 502 

![image](https://user-images.githubusercontent.com/17333688/48017998-8d255700-e0e4-11e8-9340-75509faade1b.png)

Repro steps:
1) Create new echo bot on VS.
2) Right-Click / Publish.
3) Navigate to end point
4) see above error image
5) Connect bot channels registration, update appId and password
6) Test in Web Chat
7) Receive 502 error.

**Comment by johnataylor** [comment]
The problem occurs when there are spaces in the name.

**Comment by drub0y** [comment]
So there's actually two issues. The `502.5` is caused by the space in the assembly name, but that picture is not of the `502.5`... that picture is of a `500` because there's an internal error and ASP.NET is putting up its friendly error page. 

Assuming you don't have a space, what happens next is is that there's nothing in the template or any deployment documentation along the "VSIX-first" deployment path (right now) that's going to lead you to ending up with an endpoint named `"production"` in your `.bot` file, so it's going to throw in Startup causing that `500` and there's no way you'd know this unless you knew how to spelunk through App Services logging.

**Comment by cleemullins** [comment]
The latest VSIX was just published to the Visual Studio Marketplace. It resolves part of this, with more improvements on the way. 

By default, the project name doesn't have spaces in it any longer. There is also a "production" endpoint in the bot file, although it remains a manual process to for the developer to fill it out. 

We have PR #1214 in flight to enable actual validation as part of the publish process, but that's not quite ready yet.

**Comment by sgellock** [comment]
we've turned the crank on this for the 4.2 release.  those bits have been published to the vs marketplace.
we're moving the issue to 4.3 as we plan to turn the crank on this again in the next release

**Comment by cleemullins** [comment]
The master tracking bug for this problem is here:
https://github.com/Microsoft/BotBuilder-Samples/issues/955

Closing this as a dupe.
