### ISSUE TITLE
.Net Samples need to updated to latest .Net SDK Version

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-dotnet#1086]
The samples need to updated to SDK v4.1.5.

**Comment by JSWilsonX** [comment]
It would be nice to include some as templates in Visual Studio for the Mac while you are at it. It is difficult to figure out how thing should work if the samples have errors because `options.State.Add(conversationState);` is obsolete. This is a problem with the samples that I have looked at that need to collect multiple inputs from the user.
