### ISSUE TITLE
Confirm prompt does not support "en" or ""

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [Microsoft/botbuilder-dotnet#1206]
## Version
4.1.5

## Describe the bug
When setting locale as 'en', the confirm prompt fail to handle and throw an exception:
The given key 'en' was not present in the dictionary. |    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at Microsoft.Bot.Builder.Dialogs.ConfirmPrompt.OnRecognizeAsync(ITurnContext turnContext, IDictionary`2 state, PromptOptions options, CancellationToken cancellationToken)\r\n   at 

 Or setting locale as '', the same thing happens:
The given key '' was not present in the dictionary. |    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)\r\n   at Microsoft.Bot.Builder.Dialogs.ConfirmPrompt.OnRecognizeAsync(ITurnContext turnContext, IDictionary`2 state, PromptOptions options, CancellationToken cancellationToken)\r\n   at 

## To Reproduce
For "en" case:
![image](https://user-images.githubusercontent.com/16643193/49362961-4b0b2780-f71b-11e8-9956-f704b631aa0d.png)
Then use confrim prompt

## Expected behavior
1. support "en" locale
2. ignore when turnContext.Activity.Locale is empty

**Comment by ceciliaavila** [comment]
We are closing this issue because it has been fixed in the [version 4.2.0](https://github.com/Microsoft/botbuilder-dotnet/releases/tag/4.2) released in December 2018. The changes belong to the [PR #1178](https://github.com/Microsoft/botbuilder-dotnet/pull/1178) and the original issue ([#1177](https://github.com/Microsoft/botbuilder-dotnet/issues/1177)) is closed as well.
