### ISSUE TITLE
Unable to perform ContinueDialog through a Waterfall Step set without at least a single back and forth with the user

### ISSUE THREAD

**Issue by MickH3** [Microsoft/botbuilder-dotnet#1241]
## Version
SDK 4.1.5

## Describe the bug
When I start a waterfall step based dialog set with 4 steps in it, I am unable to call stepContext.ContinueDialogAsync(cancellationToken) to move through the steps.  It seems the only step loaded is the first step and calling Continue...() ends the dialog instead of moving to the next step.

If I add an initial step that prompts for input from the user, my same Continue...() chain works and I can skip steps as needed.

## To Reproduce
1.  Create a WaterfallStep array with 2+ steps in it (mine has 4).
2.  Have the steps call stepContext.ContinueDialogAsync(cancellationToken) with no prompts.
3.  Perform a basic BeginDialog(...) using this WaterfallStep array
4.  While stepping through code, note that the 2nd and beyond steps do not get hit.
5.  Add a new step to the beginning of the WaterfallStep array that includes a simple text prompt.
6.  While stepping through code, note that after the 1st step prompt, all other steps are hit.

## Expected behavior
I should be able to Continue...() through my waterfall steps from either a BeginDialog() or ContinueDialog().

## Additional context
I am not sure if this matters, but I am initiating the dialog from an 'Event' typed Activity.

[bug]

**Comment by v-kydela** [comment]
Hi @MickH3 

Thanks for your post.

I just tried reproducing your bug and my bot correctly and easily goes from step 1 to step 2, so I think it may actually matter that you're initiating the dialog from an event activity. I seem to recall in V3 there was some issue with constructing a dialog context from the information in an event activity, because there was needed data that only gets sent in a message activity. See if your issue persists when you start your dialog in response to a message activity instead of an event.

I should also mention that this isn't how dialogs are meant to be used. If you have multiple waterfall steps that don't wait for user input between them, why not just make them one step? ContinueDialogAsync is normally meant to be called from outside your dialog in OnTurnAsync rather than from inside your dialog.

**Comment by MickH3** [comment]
Hi Kyle,

Yes my goal was to circle back on this today and got side tracked. I’ll make sure to close the loop tomorrow.

Thank you again!

Sent from my iPhone

On Dec 20, 2018, at 7:25 PM, Kyle Delaney <notifications@github.com<mailto:notifications@github.com>> wrote:


@MickH3<https://github.com/MickH3> - Are you still working on this?

**Comment by MickH3** [comment]
Hi Kyle,

Thanks again for your help.  I did some tests and it's definitely the fact that the activity is an event.  If I had to guess, it's due to the event typed activity not having an ID.  I compared an event to a message activity and that was the only real difference that stood out to me.

I've worked around this by not entering a dialog if I can detect I would just cancel out of it.  My original goal was to consolidate where I was applying the logic to make the decision to cancel out or not.  Due to multiple entry points into the dialog, it was an attempt to simplify.

Thanks again!

Mick
