### ISSUE TITLE
Microsoft.Bot.Connector.Tests project in Microsoft.Bot.BotConnector solution doesn't build

### ISSUE THREAD

**Issue by apulliam** [Microsoft/botbuilder-dotnet#126]
Here is the error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for framework ".NETFramework,Version=v4.6.2" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	Microsoft.Bot.Connector.Tests	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1124	

Also, its unclear what the purpose of this solution is. The Microsoft.Bot.Connector project is also in the Microsoft.Bot.Builder solution.

**Comment by cleemullins** [comment]
That's... odd. I'll dig into this.

**Comment by cod7alex** [comment]
I think to resolve this target framework of this project should be changed to `netcoreapp2.0`. Other test projects target it. But i noticed that it doesn`t build anywat because of errors in tests.

**Comment by nrobert** [comment]
> Also, its unclear what the purpose of this solution is. The Microsoft.Bot.Connector project is also in the Microsoft.Bot.Builder solution.

I think this is a good question: there are 2 projets (samples/Connector.EchoBot and Microsoft.Bot.Connector.Tests) referenced in this "Microsoft.Bot.Connector" solution, what is the purpose of doing 2 solutions here? And the side-effect is that commits on "Microsoft.Bot.Builder" have not been reflected in those 2 projects, hence the build errors now.
In that case here the tests may be failing due to this change with the reuse of httpClient: https://github.com/Microsoft/botbuilder-dotnet/commit/104d6cd41a5173050d3234967ec225e2d6f0fb87#diff-7455180913d2396824708a30dfdac5cb

@cleemullins , do you think we should those 2 solutions splitted?

**Comment by cleemullins** [comment]
This has been fixed in PR #163. 

@nrobert, there is no value in having 2 solutions. We should just have 1. That is an artifact of when we were building the lower layer and I've not cleaned it up yet.

**Comment by nrobert** [comment]
That's what I was thinking, thanks for the reply. Good for the PR, I was preparing quite the same
