### ISSUE TITLE
QnA MetaData suspected indexing issue

### ISSUE THREAD

**Issue by DigitalSa1nt** [Microsoft/botbuilder-dotnet#1276]
## Version

V.4.

## Describe the bug

If only adding a single metadata tag to knowledge base keyvalue pairs at https://www.qnamaker.ai/ the V4 SDK returns a MetaData zero length array as part of the QueryResults.

If you add >2 metadata tags it will pull down the first one. I suspect there is an array starting index issue somewhere in the code.

## To Reproduce

1. Go to https://www.qnamaker.ai/

2. Create knowledge base, and connect up to BotFramework using the V4 SDK and Microsoft.Bot.Builder.AI.QnA

3. create a single metadata tag for any of the keyvalue pairs.

4. send a query designed to pull that question/answer pair, and inspect the QueryResult array for metadata, you'll see it has a zero length array.

5. Add a second metadata tag to the same key value pair

6. send a query designed to pull that question/answer pair, and inspect the QueryResult array for metadata, you'll see it has a 1 length array containing the first metadata tag and not the second.

## Expected behavior
See all metadata tags for a key value pair

## Screenshots
N/A

## Additional context
N/A

[bug]

**Comment by DigitalSa1nt** [comment]
After investigating a little further, it looks as though unless either the key or value is amended during a knowledge base train and publish, it won't update the metadata tags at all. 

Cannot confirm why adding a second tag causes it to update correctly. Looks like the only scenario it fails under are if you ONLY add a metadata tag since the last time you performed a 'save & train'/'publish'.

If you add a metadata tag to three questions, and update one of the key/value sections of one of the questions, ONLY that one question will get updated with the new metadata tag.

**Comment by Zerryth** [comment]
investigating...

**Comment by Zerryth** [comment]
@DigitalSa1nt I thought I had repro'd the behavior you described earlier, however after I left the QnA Maker service alone "for a few minutes", without updating anything, the updates caught up.
* meaning I added 1 metadata tag > Save and train > Test in panel > no metadata tag in results
* added 1 more metadata tag to the same question (2 metadata tags total on 1 question) > Save and Train > Test > only 2nd metadata tag showed

Again, after waiting for a few minutes, however, the metadata eventually showed up in the results when testing.
___
I did notice that sometimes the results showing metadata would actually show up in the "**Test**" pannel inside the qnamaker.ai portal, but the results shown in a **Postman** request would only show the updated metadata tags after giving it "a moment". 
(Without giving it time, via Postman it would show `"metadata": []` (empty array), despite having published it and double checking that the Test panel in the QnA portal actually showed the results with metadata)
___
At a different time of day I decided to add metadata tags to my KB, and they showed up immediately, instead of with a delay

It appears that just sometimes (perhaps depending on traffic) QnA Maker just simply takes a bit longer to update all new trained data. And if you've made a change in metadata, wait a few minutes, then try testing with a question again.

**Comment by Zerryth** [comment]
And you are correct, this is not directly a Bot Framework bug, but instead the behavior of the service itself. I'll communicate with the QnA team feedback regarding the metadata behavior, so they are aware of the confusion the service may cause (or perhaps need to document more on expectations of training)

**Comment by DigitalSa1nt** [comment]
@Zerryth thank you for taking the time to look into this, you're absolutely spot on, it did give a false positive in believing that there was an issue with adding metadata tags by themselves during a train and publish cycle, and thank you for passing this along to be checked out.
