### ISSUE TITLE
Proactive message without Teams Context in Teams

### ISSUE THREAD

**Issue by markolb81** [Microsoft/botbuilder-dotnet#1301]
Obviously it is currently not possible to initiate a conversation (proactive message) from a Bot to a user within Microsoft Teams outside of a teams-channel (just a chat).

With this code I'm currently able to initiate a proactive conversation to any skype user:
```
string serviceUrl = "https://api.skypeforbusiness.com/platformservice/botframework";
MicrosoftAppCredentials.TrustServiceUrl(serviceUrl);
var connector = new ConnectorClient(new Uri(serviceUrl), <appId>, <appSecret>);
var user = new ChannelAccount("sip:user-upn@domain.com", "User Name To Contact");
var bot = new ChannelAccount("sip:bot-upn@domain.com", "Name of Bot");
ConversationParameters cpMessage = new ConversationParameters(false, bot, new List<ChannelAccount> { user }, "Topic of the conversation");
ConversationResourceResponse response = await connector.Conversations.CreateConversationAsync(cpMessage);
```
When I replace the serviceUrl to "https://smba.trafficmanager.net/emea-client-ss.msg" I just receive "Bad Request".
According to the (lack of) Documentation, I suppose that it's not meant to work like this for Teams / not implemented yet. 

Since there are hundreds of use cases where a bot must initiate the conversation without ever having talked to a user before (or being added to a teams / channel), I hereby kindly ask for this feature to be implemented.

Thanks!

**Comment by Zerryth** [comment]
You are correct, this feature is not available at the moment in Teams, and is intentional.

Currently there's not such thing as a spam bot on Teams, largely because of the lack of this ability.

According to Bill Bliss, the team has been discussing ways to do this in the future, however there's nothing specific on the roadmap at the moment. Implementation of such feature needs to be done in such a way that we ensure that there's no way for a bot to spam users (e.g. limit the capability to bots that have been deployed in a company, require tenant-level consent for bots that need to do this)

**Comment by markolb81** [comment]
Okay, I understand - thank you for your clear answer.
Then, we'll just switch back to a combination of good old Skype for Business & E-Mail.
