### ISSUE TITLE
StateAccessors are confusing and provide no perceived benefit

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/botbuilder-dotnet#1400]
When working with docs, samples, and tutorials that require state management, the StateAccessors paradigm doesn't appear to serve any discernible purpose and provides only a layer of indirection; another pattern developers must grok in order to build a useful bot.

We should strive to make state management as straightforward as possible as this is fundamental to useful bot creation.

**Request**: Make state accessibility & manipulation native to the SDK, not something that must be hand-rolled every time it wants to be used (via something like Accessors); showcase this way of doing state management in our docs & tutorials.

**Comment by cleemullins** [comment]
@johnataylor is working on this. I don't know how far towards what you're asking we'll be able to get, in part due to the need to preserve compat.

**Comment by GraniteStateHacker** [comment]
Anyone have a good example of conversation state that works?  I had a user state object worked, but really needed to be conversation state. The refactor has not gone well.  TIA

**Comment by johnataylor** [comment]
Yes absolutely, the title of the issue says it all.

So analyzing this a little: Accessors look like classes however they are really just awkward methods on a BotState class. They have odd semantics, at first they look like a classic get/set patter however set is never called - anywhere. Anyhow... they are public classes and back peddling is difficult.

The good news is we have a growing set of samples that should demonstrate how not to worry about this too much.

Couple of specifics to look at:

1. Sample 42 "Scaleout" shows how to build your own state solution from the ground up. In order to integrate this with the existing Dialog stack you'll find a completely generic shim class called RefAccessor buried deeply in the implementation. (You might ask yourself why Accessors exist if its so easy to write a completely generic implementation.)
 
1. In the revised samples (temporarily on a branch called samples-work-in-progress) there is a couple of classes: DialogBot<T> and the Run extension method that handle Dialogs for you. Just use those and you don't have to worry about your own accessors - at least for ConversationState.

If you want to use UserState you will have to grab an Accessor from it. But we have provided samples of how to do this correctly. Please follow exactly the sample because the semantics of the BotState/Accessor model have some surprises.

So the path we are on is to firstly help you deal with this so you hardly have to worry, and secondly to revise the model more completely and replace it with something more conventional.
