### ISSUE TITLE
DateTimePrompt generates NullReferenceException with certain phrases

### ISSUE THREAD

**Issue by steve-duff** [Microsoft/botbuilder-dotnet#1472]
## Version
4.3.1

## Describe the bug
DateTimePrompt generates an exception when given the phrase "between 7 and 9 last night". This appears to be because the DateTimeRecogniser returns two results - the first refers to "between 7 and 9" and has a null Resolution, and the second result refers to "last night" and contains a timespan of 20:00 to 24:00 with yesterdays date.

The phrase is a fairly common usage in conversational British English. It would seem that the problem is with the underlying DateTimeRecogniser, but it would be trivial to make the Prompt code defensive enough.

## To Reproduce
1. Create a bot dialog with a DateTimePrompt
2. When prompted enter the text "between 7 and 9 last night".
3. Prompt throws NullReferenceException.

## Expected behavior
Validation should succeed because the partially matched text should be skipped -or- validation should fail gracefully either because the DateTimeRecogniser has returned malformed data, or simply because the DateTimePrompt is not intended to match more than one clause in the text.

## Screenshots
N/A

## Additional context
N/A

[bug]

**Comment by dmvtech** [comment]
As there are two aspects to this issue, I will create a bug in https://github.com/Microsoft/Recognizers-Text/ to handle that side.

**Comment by johnataylor** [comment]
As far as my tests show "between 7 and 9" is not recognized as a time range. It should be.

Trying "last night between 7 and 9" and "last night" is recognized _and fully resolved_ even in the TIMEX expression which reflects the limitation of TIMEX. Specifically TIMEX can't express "last" or "next" very well. For example, it should have a way to express the more abstract notion of "last Christmas" rather than having to resolve it to 2018-12-25.

And given the test from the issue. "between 7 and 9 last night" resolves but incorrectly to TIMEX 2019-03-24T21 it also fully resolves reflecting the known limitation in the expressiveness of TIMEX. The bug is that it resolves to a time rather than a time range.

The issue https://github.com/Microsoft/Recognizers-Text/issues/1492 seems good.

In the prompt code I don't see a null exception in 4.3.2. Possibly application code could have a null exception because the DateTimeResolution structure can contain nulls in the non-TIMEX fields - depending on the specifics of the resolution. This is perhaps weak, however, the real problem is that it returns non-TIMEX resolutions at all. You should always use the TIMEX field and the TimexExpression library to deal with the ambiguity.

Please re-open if you can get a repo of the null exception on 4.3.2.
