### ISSUE TITLE
Ignore typing activity while setting dc.Responded = true. This impacts prompt dialog validator. 

### ISSUE THREAD

**Issue by aforank** [microsoft/botbuilder-dotnet#1589]
## Version
4.3.2

## Describe the bug
In all the prompt dialogs, SDK calls the OnPromptAsync method only if dc.Responded property is false otherwise not. This prevents the retry prompt to appear if I send a typing activity in the validator delegate and returns isValid = false.

**Comment by aforank** [comment]
Is there any update on this?

**Comment by v-kydela** [comment]
@cleemullins - If we decide to set `dc.Responded` to true only for message activities then it should be an easy fix but not necessarily an easy decision. It makes sense to only consider the bot to have responded when it sends a message activity because that property is used to determine if another message (the retry prompt) should be sent as well. However, it is a public property and this change could affect the logic of people's bots if they refer to that property.

Shall I proceed with the change?

**Comment by v-kydela** [comment]
@aforank - You meant `dc.Context.Responded`, right?

**Comment by cleemullins** [comment]
Changing this would break existing behavior and bots. I don't think this is a change we can take at this time.

**Comment by v-kydela** [comment]
@aforank - While I believe it would make a lot of sense to treat `TurnContext.Responded` differently, right now we want to ensure that people's bots break as seldom as possible when they upgrade to newer versions of the SDK. It's common for people to want to prevent prompts from reprompting and rare for people to want to ensure that a prompt reprompts.

Consider that the reason `OnPromptAsync` is not called when `dc.Context.Responded` is true is because the validator function may send its own version of the retry prompt and then reprompting on top of that would be redundant. This suggests a workaround for you. All you have to do is send the retry prompt in the validator instead of depending on the prompt to reprompt automatically.

I'm sorry this took so long, but hopefully the information is helpful. I'm closing this issue now.

**Comment by aforank** [comment]
@v-kydela That's alright. I understand that this change would break a lot of production bots.

I raised this issue almost 6 months back and as far as remember I overrode the OnPromptAsync method as per my needs.
