### ISSUE TITLE
Hosting an on-premises bot behind a proxy, failing to get OpenID configuration.

### ISSUE THREAD

**Issue by dmvtech** [Microsoft/botbuilder-dotnet#1595]
## Version
4.4 Preview

## Describe the bug
When hosting a on-premises bot behind a proxy, failing to get OpenID configuration.

## To Reproduce
Customer is hosting Azure Bot (API) on-premise.  Bot channel registration is hosted in Azure.  They are running into the issue when the request is received by on-premise Bot API ( that is hosted behind a proxy ), it fails to get openid configuration
	
When this was first investigated it was determined that the issue is with HttpClient not honoring BotframeworkOptions in ConnectorClient and other downstream logic and so two bug reports were opened (and subsequently closed): Bug Report #1360  and the older bug report #1242.  

Recently, after being told that 4.4 preview in nightly build had the merged fix for this issue, we went back to the customer and ran a test on a proxy enabled EchoBot app but still running into same issue.

They get this error:
IDX20803: Unable to obtain configuration from: 'https://login.botframework.com/v1/.well-known/openidconfiguration'.

## Expected behavior
Be able to run on-premises bot behind proxy. 

[bug]

**Comment by drub0y** [comment]
I _believe_ the problem is right here:

https://github.com/Microsoft/botbuilder-dotnet/blob/b56cc65e6fefdfdc2cd6a17b9294b99f438e5237/libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs#L73

The `httpClient` needs to be passed to a constructor overload, like so:

```CSharp
return new ConfigurationManager<OpenIdConnectConfiguration>(metadataUrl, new OpenIdConnectConfigurationRetriever(), httpClient);
```

That will trigger the `ConfigurationManager<>` to build an `HttpDocumentRetriever` based on the supplied `HttpClient` instance which it will then pass to the `OpenIdConnectConfiguration::GetConfigurationAsync(...)` API which then utilizes it to fetch the metadata document.

I'll PR and let you all test/review/validate from here.
