### ISSUE TITLE
 [declarative-hack] LG in retryPrompt is sticky (doesn't shuffle through generations)

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-dotnet#1671]
## Version
Hackaton prebuild

## Describe the bug
Using declarative form, when using LG [name] in activity, all is well. When using the same [name] in "retryPrompt": "[name]", it doesn't shuffle through LG entries.

## To Reproduce
Use declarative dev, place an LG [token] in retryPrompt, run, try to see one of the alternates. The first one that comes up is sticky during the retry.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
Ok. I was able to get to the bottom of this. The issue here is that although user specifies an LG template to 'retryPrompt' it is never called multiple times because the initial prompt is initialized with the retry string (LG called at that point) and is not called on every single retry. We possibly need to address this via the reprompt .vs. continue discussion via #1682 

``` C#
var prompt = await Prompt.BindToData(dc.Context, dc.State).ConfigureAwait(false);
var retryPrompt = RetryPrompt == null ? prompt : await RetryPrompt.BindToData(dc.Context, dc.State).ConfigureAwait(false);

return await dc.PromptAsync(this.prompt.Id, new PromptOptions() { Prompt = prompt, RetryPrompt = retryPrompt }, cancellationToken).ConfigureAwait(false);
```

@yochay

**Comment by vishwacsena** [comment]
This is related to the reprompt re-work. Punting to post //build.

**Comment by vishwacsena** [comment]
@luhan2017 , this should be fixed via the input work. Can you please verify and close?
