### ISSUE TITLE
Activity does not support IClonable Interface for doing Deep Clone 

### ISSUE THREAD

**Issue by james-novino** [Microsoft/botbuilder-dotnet#1726]
**Is your feature request related to a problem? Please describe.**

The Activity class currently does not implement the ICloneable interface which makes mutation of the activity very dangerous as it applies to any portion of the code base that is accessing the activity.

When building multi-threaded APIs this is dangerous and can lead to some challenging threading issues around data correctness. This is even more frustrating when using F# where everything is considered immutable by default, so in order to safely mutate the activity as to not affect the rest of the code base. You would deep clone the activity and pass it to the portion of the call stack that needs that mutation, however, currently, the Activity doesn't implement the ICloneable interface to make this possible. 

**Describe the solution you'd like**

The Activity class should ideally implement the IClonable interface or provide an interface for deep cloning an activity so to be able to mutate the activity without affecting the original activity. 

**Describe alternatives you've considered**

Some alternatives were cloning the memory or trying to change the usage of the activity to be sequentially executed to prevent any race conditions with the mutation affecting unwanted portions of the call stack. 

[enhancement]

**Comment by cleemullins** [comment]
Hi James, 
This is by design, as IClonable is (these days) very much considered an anti-pattern. To clone the activity, the most robust way - and this does a deep clone - is to serialize it to JSON and then back to an Actvity. This will pickup everything and is the mechanism used throughout our codebase do exactly what you describe. 

If there were an IDeepClonable<T> then that would be interesting on Activity, but the old-school IClonable only causes us problems.

As an additional set of ideas, I would love an Immutable Activity class. Everything set at construction, and that's it. Doing this would make some of the C# concurreny and mutation issues cleaner. 

I wonder if something like this would be enough: 
'''cs
var immutableActivity = new ImmuitableActivity(myActivity);
'''

**Comment by james-novino** [comment]
@cleemullins Something that would work, it would be nice to see if we could add an ImmutableActivity constructor for such activities, it would be even better if this ImmutableActivity class supported F# records. But that might be harder to achieve in the core C# sdk.

**Comment by james-novino** [comment]
Additionally, the serialization to and from Json is a very expensive way of trying to achieve mutation, that's not something we could do reliably due to performance concerns. So having the ability to clone or construct a new activity from an existing activity would help with this since it's just a memory clone rather than a serialization -> deserialization which tends to be very expensive.
