### ISSUE TITLE
[Adaptive] [DCR] We need to clarify .lg file semantics in order to support components

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#1815]
The semantics around .lg files need to be clarified in order to support components and overriding of templates in a consistent and comprehensible way.

# Requirements:
1) You can have a .lg file for any $type or that has an id either through the top-level filename or through an explicit $id.
2) You can have an .lg file for a language and there is a fallback story.
3) We want to find the most specific template with respect to a given id so that people can always override and understand how to override templates including sub-templates.
4) We need a component story that allows using .lg files you do not own while still allowing overriding of templates.  Think of the default template values included with a type.

# Proposal
This proposal grew out of working through some scenarios.  I started with using the .CSS fallback notion, but that was just way to complex and didn't seem to capture the essence of the requirements.  This proposal is relatively simple and captures how we want to be able to override in different scopes.  

There are a couple of concepts in the proposal.
1) The **contained path**.  This is the path of components from where an id is defined to the id defined by the file the id is found in.  (The story becomes simpler if we did not allow embedded ids.)
2) The **copy path**.  When a component is a $copy of another id, this is the contained path starting at the id of the component that was copied.
3) **global .lg** A global .lg file provides a place to define the templates for your application.  In most cases this together with type .lg files will be enough.
4) **type .lg** The .lg file corresponding to a specific $type.  This is how a $type can define the structure and provide defaults for the templates it uses.

When trying to resolve a template we would look until we found a template definition whether a top-level one or any sub-template.  The intuition is that the contained path is a unique scoping mechanism for what a definition overrides and it is always possible to override at the leaf.  This does mean that a parent sepcifying a template override will be more specific than one specified in a copy source.  You can always fix this  by explictly copying from the source into the copy .lg file.  Here is the procedure:
1) Look along the contained path from ID.
2) Look along the highest remaining copy path.
3) Look in the global .lg.
4) Look in the $type .lg.
5) Fallback to the next language.

Here is a diagram to make this concrete that uses these conventions:
- ID/Type: The id we are resolving the template reference with and its $type.
- P<N>: The id of a parent that contains other componentd.
- C<N>: The id of a copy source.
- -contained> : A contained relationship.  Following these defines the **contained path**
- -copiedFrom> : A pointer to where we copied the definition from.
```
ID/T1   -contained> P1  -contained> P2  -contained> P3
                                        -copiedFrom> C4
        -copiedFrom> C5 -contained> P6 -contained> P7
                                        -copiedFrom> C8
```

In this case we would look for a template in this order: 
1) The id contained path: ID, P1, P2, P3
2) The copy paths in order: (C4), (C5, P6, P7), (C8)
3) Global
4) Type
5) Fallback to the next language

In practice for most bots they will just rely on the type .lg and a single global file and likely only override at the leaf if needed.

**Comment by boydc2014** [comment]
Although this is already way simpler than .css fallback or node module look up (which the author regret about), this still looks too complex to me, let me feel like we will push users away from this.

My top problem around .lg file semantic is lg file is being used too "implicit". Unlike LU, we explicitly says about which .lu is used in this dialog, but we are not explicit about .lg file.  I think making this explicit, can large solve the problem of supporting components, (or at least force we think LU + LG together). 

So here is my simplest proposal on here, we being as explicit about .lg files as .lu files, means we have a field in dialog called 'MultiLanguageOutputGenerator' (this name comes from Vishwac), with a similar structure of MultipleLanuageRecongizer, which has the same language fallback policy there.  Then we are all set. 

The scenario of copying object, or shipping objects as components, is like this
* if you are using my component, you should always include my .lg, it should ship with my objects and it should work. 
* if you want to override my lg. you can still use my dialog object but overriding the MultiLanguageOutputGeneator, then you basically have to create your own .lg at least for this object. 

This means
* we don't allow you to override one template inside .lg (we don't allow override one intent in luis, right?)
* we don't built any fallback except for language (same as luis model, we don't do automatically model fallback\lookup).

I know this sounds plain, simple and not exciting, and i may oversimplify the scenario. But to me, this is a lg story same good as lu. My intuition is that we can always go complex as we wish, when the requirement is so strong, when so many many people are asking for something more, then this becomes a 'happy problem', in some sense.

**Comment by vishwacsena** [comment]
From @tomlm

Here arethe goals:
1.	Templates are evaluated against a ILanguageGenerator
2.	Fallback logic is built into ILanguageGenerator
3.	We don't use class hierarchy or prototype hierarchy, but simply use file name as the id for the ILanguageGenerator to use.

Here are the changes we think we need:
1.	The default for ActivityTemplate today does TurnContext.get<ILanguageGenerator>() to get the active language generator.  This will not change
2.	ActivityTemplate *optionally* takes in ILanguageGenerator.  This allows you to customize any instance of ILanguageGenerator anywhere.
3.	*change* instead of having ILanguageGenerator at the root for all language resources we change to
a.	have global dictionary driven by ResourceExplorer resource changes which has map of D1.lg -> ILanguageGenerator, this will be registered into turn context giving anyone access to the ILanguageGenerator for a given lg 
b.	Change AdaptiveDialog to have peer to IRecognizer called ILanguageGenerator.  If the ILanguageGenerator is set, then we will register the turnContext.Set<ILanguageGenerator>() contextually to that dialog.  This has the effect that whenever we are calling in the context of a dialog we can contextually change the language generator for that dialog in that context.
c.	When resource changes we simpy update the global map for file -> ILanguageGenerator
The net result of this is that you can simply have 1 lg file at the root and write it that way, you can have a component with a LG resource and just consume, and you can replace it if you want.

I think this is super targeted and clean and mirros the way that LU files are stitched into the system.
