### ISSUE TITLE
Bot Framework SDK v4 template for C# for MacOS

### ISSUE THREAD

**Issue by CMashudu** [microsoft/botbuilder-dotnet#1896]
## Version
What package version of the SDK are you using.

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by CMashudu** [comment]
I cannot seem to be able to add Bot Framework SDK v4 template for C# on VS on MacOS. Can you kindly assist.

**Comment by mdrichardson** [comment]
MacOs doesn't support `.vsix` extensions at this time. However, the templates are basically the same as [the samples](https://github.com/microsoft/botbuilder-samples).

Here's some links to the same samples from the template (except Empty Bot):

**C#**:

* [Echo Bot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/02.echo-bot)
* [Core Bot}(https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/13.core-bot)

**Node**:

* [Echo Bot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/02.echo-bot)
* [Core Bot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/13.core-bot)

The above workaround is the only solution currently. Unfortunately there are no other elegant ways of doing this at this time. I am closing the issue since this should unblock you and allow you to continue. Feel free to reopen if this does not quite solve your scenario.
