### ISSUE TITLE
BotConfiguration.ConnectService Bug

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botbuilder-dotnet#1910]
In the BotConfiguration.ConnectService method, [found here](https://github.com/microsoft/botbuilder-dotnet/blob/644dbf497b07879a4e2c263f2616133e774b5a64/libraries/Microsoft.Bot.Configuration/BotConfiguration.cs#L255), there is a bug. 

We see this in "occasional" unit test failures, such as [in this build run](https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=59696):
```
Failed   DisconnectServicesByNameOrId_UsingId
Error Message:
 Test method Microsoft.Bot.Configuration.Tests.ConnectionTests.DisconnectServicesByNameOrId_UsingId threw exception: 
System.Exception: service with 12 is already connected
Stack Trace:
    at Microsoft.Bot.Configuration.BotConfiguration.ConnectService(ConnectedService newService) in d:\a\1\s\libraries\Microsoft.Bot.Configuration\BotConfiguration.cs:line 267
   at Microsoft.Bot.Configuration.Tests.ConnectionTests.DisconnectServicesByNameOrId_UsingId() in d:\a\1\s\tests\Microsoft.Bot.Configuration.Tests\ConnectionTests.cs:line 78
```

The problem is:
1. When a service is "connected", it's checked (by id) to see if it's already in the set.
2. If the Id is present already, an exception is thrown. 
3. If the Id is NOT present, then it's assigned a **random id** from 0-255.

In the case where there are 2 services, consider the following:
1. Service 1 is passed.
2. The check passes.
3. The RANDOM number is "12", and the service is added. 
4. Service 12 is passed in. 
5. Service 12 FAILES (with the above exception) as that service id already exists. 

This causes both random test failures and random BOT STARTUP failures. 

Problem #2: The code has an infinite loop if >255 services are added. 

Note: The [JS Codebase uses the Random function](https://github.com/microsoft/botbuilder-js/blob/2115012394877abcfc8234ebad43d09b9ac2d9d0/libraries/botframework-config/src/botConfigurationBase.ts#L114) still, but verifies the id isn't taken or picks a new random. That is subject to an infinite loop, which is tracked in https://github.com/microsoft/botbuilder-js/issues/928.

**Comment by garypretty** [comment]
@cleemullins I've been taking a look at this issue. Given that the connected service ID is of string, is there any reason why we couldn't have the random ID be generated as a GUID instead of a number <= 255?  Doing this should allow services that have a specific ID already set (e.g. service 12 in the scenario above) use their explicitly set ID, but service 1 will get a random GUID.  

This should hopefully still allow a user to use the method 'DisconnectServicesByNameOrId' (passing in an ID) predictably to remove services where they have explicitly added them with a given ID, because we are maintaining the IDs if they are set by the user initially, whilst still also allowing for IDs to be generated if not supplied.

We could switch to the JS method, but this means that the user can never be sure that a service ID they have supplied will actually be used.

I might be missing something, obviously, but just an initial look at this and thought I would drop a note.

**Comment by Dmitresky** [comment]
Hello, @cleemullins, hello, @garypretty.
I want to contribute. I have never did it before. 
So, should I change [this](https://github.com/microsoft/botbuilder-dotnet/blob/644dbf497b07879a4e2c263f2616133e774b5a64/libraries/Microsoft.Bot.Configuration/BotConfiguration.cs#L268)
```
// Assign a unique random id between 0-255 (255 services seems like a LOT of services
var rnd = new Random();
do
{
    newService.Id = rnd.Next(byte.MaxValue).ToString();
}
while (this.Services.Where(s => s.Id == newService.Id).Any());
```

to this
```
do
{
    newService.Id = Guid.NewGuid().ToString();
}
while (this.Services.Where(s => s.Id == newService.Id).Any());
```

?

**Comment by tomlm** [comment]
The real problem is that we are checking for duplicates in the case where we want a new auto assigned id.  I have changed the logic to only do duplicate detection in case where there is a user supplied id, and then not use random (which requires multiple scans) and instead simply detect high water mark id in single scan. (see #2069) 
Thanks @dmitresky and @garypretty for engaging on this issue.  I literally ran into this random behavior on a unit test this morning and was scratching my head, so your discussion and contributions were timely.
