### ISSUE TITLE
[Adaptive] [DCR] Update @ short hand behavior

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#1969]
We also need to update the @<EntityName> behavior to be this 

- If the entity returned by the recognizer is a list, set the property to the list
- If the entity returned by the recognizer is a list of one item, set the property to the only item in the list. 

Users that prefer to always set the list to the property can use turn.entities.<entityName> which will give the un-optimized behavior.

**Comment by boydc2014** [comment]
I think this is not limited to setProperty step, right? you also want this shorthand can work elsewhere like in lg.  So this essentially means making the underlying expression support that.

Current the shorthand is a syntax sugar, which don't aware of the runtime memory. which means we are doing it in compiling time, not runtime. The fix can be either 
1. in compile time, turn it into a conditional operator for example
    '@something' would becomes => 'if(count(turn.entities.somethings) > 1, turn.entities.somethings[0], turn.entities.somethings)'.

   this approach looks nice and clean to me, but this only handles one layer list (and must be a list), not multiple or non-list.

2. in run time, do some trick, can support multiple layer, but at the cost of breaking the interfaces between layers. 

Overall i think this make somethings handy, but a little design break. what do you think

**Comment by chrimc62** [comment]
I'm going to pick this one up.

**Comment by boydc2014** [comment]
@chrimc62 we have a PR out there to fix this https://github.com/microsoft/botbuilder-dotnet/pull/2128. 

In this PR, what we do is instead of rewrite the expression for shorthand expression, we treat shorthand as function, which can ends up in a more clean and flexible approach. ie. 
 * to solve a conflict of "^" for shorthand and for exp function, this means we should not do shorthand in lexer, otherwise we don't have the flexibility to dis-ambiguous. 
 * to support the operations described here, remove list if only one item, also for two-level list.

So, Chris, can you help take a look at this？

**Comment by chrimc62** [comment]
Fixed by #2128
