### ISSUE TITLE
[LG] Vague error message

### ISSUE THREAD

**Issue by ZhaoqingCui** [microsoft/botbuilder-dotnet#1997]
## Version
Adaptive

## Describe the bug
We could use dialogue files to call [LG]. However, when the bug occurs during this process, the error message is too vague to help us solve the problem. This problem is especially significant when we are trying to use multi-line text. For example, in .cs file
`new SendActivity("[CreateCalendarEntryReadBack]")`
In .lg file, we use @{lgTemplate("HelpPrefix")}, @{turn.Subject}", @{count(user.Entrys)}, 
@{lgTemplate("Welcome-Actions")}
The current error message is "Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter:Error: Exception caught: Object reference not set to an instance of an object.", which is blurry.

## To Reproduce
1. Run the bot and open your bot in Bot Framework Emulator
2. Say hi to your bot and click "Create Calendar Entry"
3. Type "meeting" to name the subject of your event
4. Open Debug of Output in Visual Studio to see the error message

## Expected behavior
The error message should be specific and accurate.
For the above example, the error message could be 
Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter:Error: Exception caught : turn.Subject at line 78 is not a valid instance of an object in CreateCalendarEntry.lg.
or 
Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter:Error: Exception caught : Welcome-Actions at line 78 is not defined in CreateCalendarEntry.lg.

## Screenshots
![image](https://user-images.githubusercontent.com/32658030/58871955-936cc780-86f5-11e9-8a48-3c4c5f5cf9b1.png)

**Comment by boydc2014** [comment]
@ZhaoqingCui can you provide the code that be able to repro this bug?

**Comment by ZhaoqingCui** [comment]
https://github.com/ZhaoqingCui/BotBuilder-Samples/tree/TestAdaptive/experimental/adaptive-dialog/csharp_dotnetcore/calendar-bot-cui

Above is the code. Let me know if you have any other questions. Thanks.

**Comment by vishwacsena** [comment]
In the new adaptive dialog model, there is a baked in Generator that you can explicitly add a template manager instance to. See [here](https://github.com/microsoft/botbuilder-dotnet/blob/b11fddfaa8b693cbc776ee0e82b0e36035543843/samples/Code-Todo-Bot/Dialogs/AddToDoDialog/AddToDoDialog.cs#L33) for an example. The first argument of TemplateEngineLanguageGenerator accepts a name label that will be included in error messages resulting from any errors in that particular template engine instance. 

@boycd2014 I suppose this issue is similar to #1996 ? If you agree, can you resolve this one as well?

**Comment by Danieladu** [comment]
use the new lg system and renderer to aviod such issues. From currently ,we suggest use 'AddFiles' interface to add .lg file or 'AddText' to add string text content. For reference: #2055
