### ISSUE TITLE
Suggested Actions stay at the bottom of the conversation while scrolling up

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [Microsoft/botbuilder-dotnet#202]
Not sure if it's a bug or a feature, but if it's a feature, it should be documented.

**Comment by Stevenic** [comment]
That's by design and it's how they work on all of the chat clients that support suggested actions.  On facebook, for instance, they're called [quick replies](https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies).

The idea is that suggested actions are only displayed for a single turn of conversation.  So these are things the bot is actively listening for the user to reply with. They're great for things like Yes/No questions or asking for a choice where you want to provide the user with quick replies but you're not going to be listening for these things in the future so you don't want to drop a card with buttons into the feed.

If you're prepared for a user to chose an action at anytime you can drop a card with buttons into the feed and this will scroll up as the feed scrolls up. The down side is the user can click a button that was presented to them months ago which is why bots tend to favor the use of suggested actions.

**Comment by cleemullins** [comment]
As @Stevenic says, this is by design. :)

**Comment by anastasiia-zolochevska** [comment]
Thanks. Would be nice to have it documented.
