### ISSUE TITLE
[Adaptive] [LG] pre-built function references without expression decoration throws incorrectly

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2042]
Something like this should not throw ..

```jsonc
{
        "$type": "Microsoft.SendActivity",

        // Although count() is a pre-built function, not wrapping it in {} should just return the text as it is. Right now, I see Object reference not set to instance of object error
       
         "activity": "You now have count(user[user.title]) items in your list!"
}
```

See [here](https://github.com/microsoft/botbuilder-dotnet/blob/5f13952d71254a6786fb7d6b9b07fc359a08b198/samples/Issue%20repros/LG%20error%20-%20ref%20to%20prebuilt%20function/Dialogs/main.dialog#L19) for a sample

**Comment by Danieladu** [comment]
This issue caused by `[user.title]`, in LG template body, `[xxx]` means reference of a template `xxx`. 
I think we could provider two solutions: 
(1) modify the text with escape character: 
`"activity": "You now have count(user\\[user.title\\]) items in your list!"`
(2) Make `[xx]` depreated, and only support with buildin function: `{lgTmplate(xxx)}`

What do you think? @boydc2014 @vishwacsena
