### ISSUE TITLE
[LG] LG Template Testing All Evaluations

### ISSUE THREAD

**Issue by jinghul** [microsoft/botbuilder-dotnet#2147]
### "getAllEvaluations" method

During testing the replies of the chatbot, I find it difficult to verify that the reply is one of the randomly selected texts in the template.

It would be great to get an evaluation method like "getAllEvaluations" so I could test that the reply is one of the strings in the evaluation list. Currently, I do exactly this feature by getting the raw string and making each line it's own "template" and separately evaluating them.

**Comment by Danieladu** [comment]
In my opinion, `getAllEvaluations` method is more like a tool api. There is a similar tool in our Butboilder-tool repo: [Expand command](https://github.com/microsoft/botbuilder-tools/tree/V.Future/packages/MSLG#expand-command) . This command will expand a template or all templates.

**Comment by boydc2014** [comment]
@Danieladu this can be useful at testing scanario, i think we need to give it a proper name.

**Comment by Danieladu** [comment]
> @Danieladu this can be useful at testing scanario, i think we need to give it a proper name.

Sure. I think vscode extension debug feature (has custom iterations of evaluation) can help and it is more lightweight.

**Comment by boydc2014** [comment]
> > @Danieladu this can be useful at testing scanario, i think we need to give it a proper name.
> 
> Sure. I think vscode extension debug feature (has custom iterations of evaluation) can help and it is more lightweight.

Yes, vscode extension can help on ad-hoc testing, here by testing, i'm refering to testing like UT.

**Comment by tomlm** [comment]
The TestAdapter has **AssertReplyOneOf()**, which is exactly for this

**Comment by boydc2014** [comment]
Hey, @tomlm, per my understanding, what Jing is asking here is not a test method. I think Jing's asking is a method to get all possible variations of a template. So that users can get total control of the output. 

There is one scenario i think this would be particular useful, that, as a LG user, i want to make sure my bot to avoid some sensitive word (or phrases) in the output, so i can use this method to exhaust the output and exam the output make sure everything is ok, then i can trust the bot to be random at the runtime. Make sense?

**Comment by boydc2014** [comment]
Closed, @jinghul , it's avaiable in latest SDK, called ExpandTemplate.
