### ISSUE TITLE
[Adaptive] Shortcuts should not require a static path to start.

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#2186]
**Is your feature request related to a problem? Please describe.**
You cannot use computed values at the root of shortcuts.  For example you cannot do %[user.name] to find options defined for a particular person.  

**Describe the solution you'd like**
Short cuts should be treated as simply that--a shortcut that you can treat like any path.  

**Additional context**
The current parser requires an IDENTIFIER after the shortcut--it should allow any valid path, i.e. IDENTIFIER, or [].  It would probably be a good idea to change the form of expression to just be the shortcut rather than a shortcut plus a property.  If we fix this, we should also fix setPathToValue to also handle it.

[enhancement]

**Comment by boydc2014** [comment]
@chrimc62 hi, Chris, I want to clarify a little bit here, because i see a little inconsistency in the form of `%foo and `%[foo]`. We can support `%[any computed result]` if we can allow such inconsitency. The issue i see is
* In %foo actually `%`  is translated (conceptually) to `dialog.options.`
* In %[foo], i expect you mean dialog.options[foo] which means % is translated to `dialogs.options` without a `.`

So the difference is the dot, which, in semantic, represent a accessProperty function, and the IDENTIFIER followed is treated at parameter. So, from a purely consistence perspective, there a few options to make it fully consistence
1. treat %\@ just as function, with the standard access pattern of funciton. For example, %("foo"), %(bar)
2. treat shorthand as a variable and do not append the `accessProperty`\'dot' in it. For example, %.foo, %[bar]

each way don't looks perfect to me. anyway, like i said at beginning, if we think we can bear with such inconsistency, it's ok to both support @foo and @[foo]. And we also want to clarify when it would be treated as accessProperty, when it's not. 

What you do think?

**Comment by chrimc62** [comment]
I'm ok with the inconsistency of @chris means ...entities.chris and @[user.name] evaluates to the same path.  I think we can build that into the semantics of shortcuts.  @foo is consistent for how other platforms refer to entities so we don't want to change that, but I do want a way to do a computed path and just doing @[user.name] seems the clearest to me.  @vishwacsena should chime in as well.

**Comment by boydc2014** [comment]
> I'm ok with the inconsistency of @chris means ...entities.chris and @[user.name] evaluates to the same path. I think we can build that into the semantics of shortcuts. @foo is consistent for how other platforms refer to entities so we don't want to change that, but I do want a way to do a computed path and just doing @[user.name] seems the clearest to me. @vishwacsena should chime in as well.

Cool, if inconsistency is ok, next thing i want to clarify is we want support 
* just one level flexibility like,  @foo, @[foo]  
* or truly free path, like @foo.bar, @foo[bar].zar, @[foo].bar[size-1].x

**Comment by vishwacsena** [comment]
@chrimc62 - great suggestion. Yes. I do agree that we should have shortcuts work with computed paths as well. I do not see an issue with the inconsistency and I believe it is palpable.

@boydc2014 - do we not already support a[b].c? Once we go down this path, I believe we should support free paths so users do not get dead ended. 

FWIW, I believe we should take this for 4.6 and not for 4.5.

**Comment by boydc2014** [comment]
> @chrimc62 - great suggestion. Yes. I do agree that we should have shortcuts work with computed paths as well. I do not see an issue with the inconsistency and I believe it is palpable.
> 
> @boydc2014 - do we not already support a[b].c? Once we go down this path, I believe we should support free paths so users do not get dead ended.
> 
> FWIW, I believe we should take this for 4.6 and not for 4.5.

Yes, we support a[b].c because it's a valid primary expression.

**Comment by boydc2014** [comment]
And the most simplest way to support free path is to treat shortcuts just as expression, just like @chrimc62 said in the description. This will instantly give us suppport for `%[foo].bar.zar`. 

But this would allow `%.foo` instead of `%foo`.  So we need some trick to make it's `%foo` not `%.foo`.  Right @chrimc62 ?
