### ISSUE TITLE
[Adaptive] dialog.*** is not working in InputDialog, because InputDialog is no longer inherited from DialogCommand

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botbuilder-dotnet#2198]
To reproduce:

{
            "$type": "Microsoft.TextInput",
            "property": "dialog.name",
            "prompt": "what is your name?",
            "unrecognizedPrompt": "prompt again",
            "invalidPrompt": "that's wrong"
        },
        {
            "$type": "Microsoft.TextInput",
            "property": "dialog.other",
            "prompt": "Hi,  {dialog.name}, what is your nick name?",
            "unrecognizedPrompt": "prompt again",
            "invalidPrompt": "that's wrong"
        },

The exception:
common.lg:Error occurs when evaluating expression ‘dialog.name’: dialog.name is evaluated to null.

**Comment by tomlm** [comment]
This is by design.  You can access your parents dialog properties by using ^ short like this: **^name** 

**$name** --> binds to **ActiveDialog.name**
**^name** --> walks caller dialog state looking for **name** property on caller dialog state.

Alternatively, you can create input binding to bind values from caller dialog state into the dialog.
