### ISSUE TITLE
[Adaptive]SetProperty step doesn't work with LUIS composite entities

### ISSUE THREAD

**Issue by zidaneymar** [microsoft/botbuilder-dotnet#2203]
## Version
4.Future branch

## Describe the bug
Any composite entities will be parsed to a complex json like this:
![image](https://user-images.githubusercontent.com/9328933/60869467-9b260b80-a261-11e9-98c5-6f0e7b0e786a.png)

     {
      "$type": "Microsoft.SetProperty",
      "property": "user.content",
      "value": "@Content" // simple entity work, "finish the demo" in the utterance
    },
    {
      "$type": "Microsoft.SetProperty",
      "property": "user.remindtime",
      "value": "@RemindTime" // composite entity not work, "tomorrow" in the utterance
    }

Currently the SDK has a special operation for composite entities in **LuisUtil.cs ExtractEntitiesAndMetadata** method, which expands the original entity to a complex json format and causes this issue.

[bug]

**Comment by chrimc62** [comment]
This is by design.  If you don't want a composite in your LUIS model, you shouldn't use one.  If you do use a composite you may need additional parts of your path.  In any case, it looks like your example is incomplete--there is no remindTime at all.  If that is a role then it is not being recognized.  If you want to reopen this, please supply the full returned result and what you expect.
