### ISSUE TITLE
IMiddleware interface is empty

### ISSUE THREAD

**Issue by starlord-daniel** [Microsoft/botbuilder-dotnet#225]
I was trying to rebuild the [filterMiddleware](https://github.com/ryanvolum/botbuilder-filter) in C#, but it seems like the IMiddleware interface is empty:

`
#region Assembly Microsoft.Bot.Builder.Core, Version=4.0.0.7, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// ...Microsoft.Bot.Builder.Core.dll
#endregion

namespace Microsoft.Bot.Builder.Middleware
{
    public interface IMiddleware
    {
    }
}
`

**Comment by drub0y** [comment]
This is "by design" right now. `IMiddleware` is just a so-called "marker" interface that is common to all middleware. You need to actually implement one or more of the "stage specific" interfaces indicating which stage(s) partake in: `ISendActivity`, `IReceiveActivity`, `IContextCreated`.

There is discussion about changing the middleware design here: #155.

**Comment by cleemullins** [comment]
Everything @drub0y said is spot on. :)
