### ISSUE TITLE
[LG] support parameters as expression to template resolution call

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2265]
We need to support parameters to a template resolution call be an expression. So something like this is possible. 

```markdown
# Suggestions (list)
- \n \[Suggestions={join(list, '|')}]

# GreetPhrase
- Hi
- Hello
- Hiya

# WelcomeUser
- [GreetPhrase], I'm the todo bot. How can I help you today? \n [Suggestions(createArray('Add Todo', 'Show Todo', 'Delete Todo', 'Help', 'Cancel'))]
```

**Comment by boydc2014** [comment]
@vishwacsena This is doable via https://github.com/microsoft/botbuilder-dotnet/pull/2271

One question i have when i'm implementing this, since we support [Suggestions(createArray("a", "b")] and we treat what's inside it an expression. Why can't I use {Suggestions(createArray("a", "b"))}, and then the quesiton is, why bother using lgTemplate function, why just {TemplateName(args)}, or @{templateName(args)}, it's all made possible by this PR.

**Comment by boydc2014** [comment]
Opened a DCR to track this https://github.com/microsoft/botbuilder-dotnet/issues/2272

**Comment by vishwacsena** [comment]
Closing this specific issue since the parametrization is now supported via #2271 

Let’s continue the remaining discussions via the other active github issues.
