### ISSUE TITLE
Inserting a blank line in Teams channel via QnA markdown

### ISSUE THREAD

**Issue by leeroy79** [microsoft/botbuilder-dotnet#2267]
## Version
4.4.5

## Describe the bug
Not able to insert a blank line in Teams messages which come from QnA markdown. The same markdown has a different result in web chat vs Teams.

If I use this QnA content (i.e. content for line one, then two newlines, then content for line 2)...

```markdown
Here's line 1\n\nHere's line 2
```

...then in the web chat there is a blank line between those two lines. In the Teams channel there is no blank line - they come one after the other.

If I try adding more newlines QnA converts them back to just two when training / publishing.

## To Reproduce
1. Go to QnA Maker which is consumed by a bot which is exposed to the Teams channel.
2. Set up an answer with the above example markdown.
3. Train and publish.
4. Go to Teams and ask the bot the triggering question.
5. There isn't a space between the lines.
6. Ask the same question via "Test in Web Chat" from the bot's settings in Azure.
7. There is a space between the lines.

## Expected behavior
The same output in web chat and Teams, i.e. two lines with a blank line between them.

[bug]

**Comment by v-kydela** [comment]
Hello @leeroy79 

Because every channel has different rendering capabilities, you shouldn't expect whitespace to be formatted the same way in each channel. Sometimes you can find a way to get the same look with the same characters in two separate channels, but I have tested in Web Chat and Teams and have not found a way to insert a blank line that works the same in both of them.

Are you targeting both Teams and Web Chat or is Web Chat just for testing? If you just want your bot to run on Teams then there are lots of easy ways to put blank lines in your QnA answer, like `<br/><br/>` for example. If you want the bot to also work in Web Chat then you'll need to modify your Web Chat client a bit or have your bot check the channel and modify the activity it's sending.

**Comment by v-kydela** [comment]
@leeroy79 - Are you still working on this?

**Comment by leeroy79** [comment]
Hi, sorry for the late reply. Understood regarding channel differences. I've tried putting <br/><br/> in my QnA content but it still appears to be skipping the blank line. I couldn't see references to any other approaches when I searched around a bit?

**Comment by leeroy79** [comment]
I'm not sure what I missed the first time but `<br/><br/>` is working as expected now. Closing this.

Thanks!
