### ISSUE TITLE
[Adaptive] Need an Expression function or steps to get Local Time Zone

### ISSUE THREAD

**Issue by ZhaoqingCui** [microsoft/botbuilder-dotnet#2293]
## Version
4.6.0-Daily-2019-07-17-01

## Describe the bug
The Current Adaptive Dialog SDK does not support getting the local time zone. 

## Additional context
This issue is blocking building user-friendly applications. All information concerning the time zone must be hardcoded, which is not convenient. 

[bug]

**Comment by Danieladu** [comment]
There are several Timezone formats like: GMT+9,  number 9, or windows timezone like `Japan Standard Time` ,  iana format like `Asia/Baghdad`

**Comment by boydc2014** [comment]
This probably not something expression can do best, because the expression will runs on server side which don't match the localTimeZone we are talking about here. 

It can be a step, or can be something (a offsite) predefined in memory which activity comes through. Anyway, it's something should be solved before expression process, time manipulation in expression should work with time zone as input

**Comment by vishwacsena** [comment]
The right way to get this information is through {turn.activity.localTimeZone}. https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#local-timezone

Note: This is really up to each client to implement and might not be available across all channels.
