### ISSUE TITLE
[Adaptive] [Expression] language requires quotes to represent string literals including empty strings

### ISSUE THREAD

**Issue by ZhaoqingCui** [microsoft/botbuilder-dotnet#2308]
## Version
4.6.0-Daily-2019-07-17-01

## Describe the bug
When we want to use SetProperty to set an empty string, we have to use "''" (A single quote inside a double quote), which is very weird. 

## Expected behavior
Just A single quote or just a double quote seems to be more reasonable. 

[bug]

**Comment by mdrichardson** [comment]
Confirming that I can repro this. Also doesn't work with `string.Empty`. 

I'm going to unassign myself from this one, however, as I'm not familiar enough with [Adaptive] to be comfortable recommending a PR.

**Comment by carlosscastro** [comment]
Hi! Please, more descriptive issue names will be extremely helpful in the future. For example: 

> Adaptive: Set property requires double quotes and single quotes to set empty string

This greatly helps triage and quick understanding ofthe bug.

**Comment by vishwacsena** [comment]
Updated issue title. We should discuss and address this in 4.6. The current behavior with empty string, types as well as string literals is confusing and could be improved.

**Comment by chrimc62** [comment]
We could easily fix this by having the expression parser return a constant string expression of string.empty when string.empty is passed in.  (Today the parser blows up on an empty string.)  What I don't see any way around is requiring single quotes to set it to an actual string--otherwise we have no way of distinguishing "3" as a number or a string.  Today the expression "3" is a number and "`3`" is a string.

**Comment by tomlm** [comment]
Or treat "3" => number, and "three" as text, and if you want "3" to be a string you have to put quotes around it.

**Comment by vishwacsena** [comment]
We should fix the empty string issue @chrimc62 calls out above. @boydc2014 per our chat, let's continue to require non empty strings to be wrapped in single quotes.
