### ISSUE TITLE
[Adaptive] Refine how input actions work with LUIS

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2320]
Our current design does not accommodate for cases where user is using LUIS for entitty extraction in turn.N of a conversation. Goal here would be to automatically save recognized entities when a specific intent fires in the containing adaptive dialog's recognizer,provide ability via steps to continue consultation bubble up as well provide ability to have the input re-process user utterance.

**Comment by Stevenic** [comment]
I'll have to think about this one some more. It's currently a little tricky because `turn.recognized` is overwritten as `ActivityReceived` bubbles up the stack.  One option would be to add an `AutoSaveEntities` property which causes the ActivityDialog to always save any entities recognized to memory on every turn.

**Comment by vishwacsena** [comment]
The core use case here is that a LUIS recognizer can recognize more than one entity. The value property on inputs at the moment does not help you persist anything but the property being actively prompted for via the input. 

Although you could have an AutoSaveEntities property, the downside to that is that validations would not be run before those entities will be persisted to memory. 

We should defer this to be considered as part of the data model definition + data binding work.
