### ISSUE TITLE
Chatbot working on emulator but not working on Web Chat

### ISSUE THREAD

**Issue by w-piotr** [microsoft/botbuilder-dotnet#2358]
Hi, when I try to deploy and test the bot on Azure I'm getting the following error:
"There was an error sending this message to your bot: HTTP status code Forbidden"

SDK Platform: C#
SDK Version: 4.5.1
Deployment Environment: Azure Bot Service

Endpoint has been configured correctly: https://my-bot-dev.azurewebsites.net/api/messages
appId and appPassword has been set correctly in the appsettings.json

Here is my Startup code:

![3](https://user-images.githubusercontent.com/49780873/61880593-7a161980-aef5-11e9-832d-3e3a26623e1a.JPG)

Here are the Application Insight Screenshots:
![2](https://user-images.githubusercontent.com/49780873/61880686-a0d45000-aef5-11e9-9109-fb2f803075cb.JPG)
![1](https://user-images.githubusercontent.com/49780873/61880811-da0cc000-aef5-11e9-982d-5ac16b2fba77.JPG)

Please let me know if there is any information which I can provide to help resolve my issue.

**Comment by mdrichardson** [comment]
@w-piotr 	Were you able to get this resolved?

**Comment by guadalupejaime** [comment]
Hello, excuse me, the empty working files folder appears to me, how do I do it?

**Comment by mdrichardson** [comment]
@guadalupejaime 	"Working Files" isn't actually a folder; it just lists the files that you have open in the editor. If your "WWWROOT" folder is empty, you need to follow [the deployment docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=newrg%2Ccsharp).

**Comment by guadalupejaime** [comment]
@mdrichardson you know why my chatbot doesn't work when I use this code
<div id = "webchat" role = "main"> </div>
<script src = "https://cdn.botframework.com/botframework-webchat/latest/webchat.js"> </script>
<script>
window.WebChat.renderWebChat (
{
directLine: window.WebChat.createDirectLine ({
secret: '(my secret)'
}),
},
document.getElementById ('webchat')
);
</script>
I created the chatbot with the template of my virtual assistant, and the web chat works and also works with the iframe, but with the code I passed it does not work, do you know why?

**Comment by mdrichardson** [comment]
@guadalupejaime Please open a separate issue so as not to hijack this one.

**Comment by mdrichardson** [comment]
@w-piotr	Were you able to get this resolved? I'll be closing this issue as we haven't heard from you recently.

**Comment by w-piotr** [comment]
@mdrichardson If it comes to the azure configuration I was able to solve the issue, thank you for help.

Do you have any suggestion about this paragraph?
"If it comes to the code improvement when I delete services.AddBot and uncomment services.AddTransient<IBot, IT_Assistant>(); my bot does not work at all in emulator."

**Comment by mdrichardson** [comment]
@w-piotr Tough to say without seeing your code as it currently stands. Are you getting error messages?

**Comment by w-piotr** [comment]
@mdrichardson I'm referring to the code available on this branch https://github.com/w-piotr/azureAppId/tree/branch1

I'm getting the error:
There was an error sending this message to your bot: HTTP status code InternalServerError

This code (as per your advise) does not work:
![image](https://user-images.githubusercontent.com/49780873/62870779-80d8c500-bd1a-11e9-89f7-1094d0230d88.png)

This code works:
![image](https://user-images.githubusercontent.com/49780873/62870854-a1088400-bd1a-11e9-96d4-abb7e4942c95.png)

**Comment by mdrichardson** [comment]
I wasn't able to get it working using the `AddTransient` method either. However, I'm not super well-versed in C#. Since you're no longer experiencing the bug and your bot is working, I'm going to close this issue. If you need additional how-to help, please post on [Stack Overflow](http://stackoverflow.com/search?q=%23botframework).

**Comment by oatsoda** [comment]
@mdrichardson Sorry to use an old thread, but in your example there is a web.config file deployed with the binaries - where does this come from and is it required?

I can see also if I create a bot service in the Azure portal it gets created also.  

But if I follow[ the deployment instructions you linked to](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#5-prepare-your-code-for-deployment) it says that 

> For C# bots and JavaScript bots, the az bot prepare-depoloy command should generate a .deployment file in your bot project folder. 

It says only Typescript bots have web.config files created.

So where does the web.config file come from?

**Comment by mdrichardson** [comment]
@oatsoda Did you need help with this? I got the notification email but don’t see your comment in the issue.

Michael Richardson
Bot Framework Support Engineer

**Comment by oatsoda** [comment]
@mdrichardson Thanks - I removed it because I immediately did a clean deploy and saw that the web.config was created as part of - I assume - the deployment of a NetCore app to the App Service.

I'm going round in circles a bit because my Bot Service will not "talk" to the Bot App Service:

- I get a 404 (Rather than a "GET is not allowed") if I visit /api/messages
- The Bot Service in the Azure Portal does not have the "App Service Settings" shortcut stuff
- The Bot Service "Test in Web Chat" does not work.

The Bot works fine running locally as debug. 

I am deploying with ARM and Azure DevOps release pipelines.

I'm working on the theory is an auth issue.  I've just noticed your comment about setting the AD App to allow Multi Tenanted access ("signInAudience": "AzureADandPersonalMicrosoftAccount")

**Comment by mdrichardson** [comment]
@oatsoda Here's [a draft of our Deployment troubleshooting](https://github.com/meetshamir/SelfHelpContent/blob/master/articles/microsoft.bot/deploymentissues.md). If none of that works, as awful as it sounds, it is often quicker than troubleshooting to just [follow the deployment docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp), ensuring that you don't miss a single step.

If you still run into an issue, I recommend opening a separate issue of your own.

**Comment by oatsoda** [comment]
Thanks @mdrichardson  - that link didn't work though :)

The deployment docs use the `az` commands - I am using Azure DevOps deployment tasks:

![image](https://user-images.githubusercontent.com/3919587/67366549-9ca6e580-f56b-11e9-9684-8405e19ea898.png)

Do you foresee any issues doing it that way rather than the Azure CLI?

My files look like they deployed ok:

![image](https://user-images.githubusercontent.com/3919587/67366653-d11aa180-f56b-11e9-9e15-e7a6d86ed6f9.png)

**Comment by mdrichardson** [comment]
Shoot! I forgot that doc was in a private repo. I'll paste it at the bottom of this comment.

I've never used that DevOps deployment, so I'm not sure if it would work well or not. Your files look fine, there. Maybe double-check your App Service and App Registration settings to make sure they match the deployment docs. Wouldn't hurt to deploy via the method in the docs, since that's what we officially support, too.

---

# Common Deployment Issues

## Recommended Steps

* Test to see if "Test in Web Chat" works from `Azure Portal > Your Resource Group > Your Bot > Test in Web Chat`.
  * If it works, your deployment was successful and you need to troubleshoot why your client cannot connect to your deployed bot
  * If it doesn't work, please follow additional troubleshooting steps from this document
* If you ran into errors while executing deployment CLI commands, ensure you have the latest version of [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest)
  * Some CLI commands will fail without much explanation. This is usually a formatting error. For your CLI commands, ensure that:
    * The entire command has appropriate spacing
    * User-provided strings are surrounded by quotes
    * User-provided strings for resource names are free of special characters (this mostly applies to App Service Plan names). See [Naming rules and restrictions](https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions) for specific details.
* Ensure that you ran [the `az bot prepare-deploy` step](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#51-retrieve-or-create-necessary-iiskudu-files) prior to deployment. Missing this step often manifests in a bot not starting or 404 errors (due to missing/incorrect `web.config`) when visiting `https://<yourBot>.azurewebsites.net`
* Ensure that the file/folder structure of `https://<yourBot>.scm.azurewebsites.net/dev/wwwroot/` looks similar to your local bot. For Node bots, it will look mostly the same as your local bot files. For C# bots, it will have a lot of `Microsoft.*.dll` files along with `<yourBot>.dll`. All deployed bots should have a `web.config` file
  * For Node bots, you also need to have `node_modules` and `.env` deployed. For C# bots, you need `appsettings.json`. If your bot is missing `.env` or `appsettings.json` you need to either upload it, or copy the appropriate keys and values in `Azure Portal > Your Resource Group > Your App Service > Configuration`
  * Expanding on [the code deployment step](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#52-zip-up-the-code-directory-manually): When deploying, zip the **contents** of your project folder and **not** the folder by itself. Your zip file should have the structure:
    * `code.zip/[each project file and folder]` and **not** `code.zip/myBot/[each project file and folder]`
* Ensure that the MicrosoftAppId and MicrosoftAppPassword that you have in `appsettings.json`/`.env`/`App Service Configuration` matches the ones found in your [App Registration](https://ms.portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade)
* Ensure that your App Registration can be accessed by "Accounts in any organizational directory" by following [these steps](https://github.com/microsoft/BotBuilder-Samples/issues/1366#issuecomment-479087524)
* Go to `https://<yourBot>.scm.azurewebsites.net/dev/wwwroot/:output`, click Run, and see if any errors present themselves in the Output window

## Recommended Documents

* [Deploy your bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0)
* For Virtual Assistants and Skills: [Manual Deployment](https://microsoft.github.io/botframework-solutions/howto/virtual-assistant/manualdeployment/)
* [Set up continuous deployment](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0)

**Comment by Flo-Anas** [comment]
Hello, I'm facing the same issue, can you explain to me what was the problem and how you did solve it please?
