### ISSUE TITLE
[Adaptive] Enable localization in Confirm and Choice Input actions

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#2387]
Today, confirm and choice input actions have pre-baked language generation logic. We should decouple LG from these input actions for better locale support and scalability.

**Comment by vishwacsena** [comment]
We GA'd with this behavior and so far there has not been many customer issues with this because we have made it super easy to build your own confirm prompt with LUIS + text input. Closing this.

**Comment by cwhitten** [comment]
Reopening in lieu of https://github.com/microsoft/BotFramework-Composer/issues/4304

**Comment by srudin** [comment]
Let me start by explaining in detail what I want to achieve (striped down from a real world scenario):

I want a simple bot built with bot framework composer. First the user should be greeted. Then we ask him if he wants to receive a mail with a joke. If he answers yes, he needs to enter his mail address; then we send him a mail. Finally we say bye. Let's say we want to support this in 4 different languages.

We create a new bot project and add the greeting. In the "Send a response" block we can just type the greeting and then translate it according to https://docs.microsoft.com/en-us/composer/how-to-use-multiple-language

Easy. Now we add a choice element. Again we can just type the question ("Do you want to receive a mail with a joke?") and translate it as described above. Then we add the choices. And now we're lost. Because there seems to be no way how the "Yes I want!" and "Leave me alone!" can be translated.

Even worse - there is no way how I can handle the IF/ELSE check after that. I can check if the user selected "Yes I want!" but what if we are in German mode and he selected "Ja ich will!"?

And it goes on like that when sending the mail. Let's say I want to send it using the SendGrid api and just issue a http request then how can I translate the body of the request?

So what seems to be a very simple and straightforward scenario turns into a complete mess. Some values in the composer elements can be translated, other not. Even after working with the composer for a while now it still remains a mistery for me when I can use special expressions such as ${SomeText()} and when not.

From my experience the fact that this is not working everywhere is preventing any effort to create a multi-language bot. Maybe I am doing something wrong or don't fully understand how I'm supposed to do this - in this case please provide some detailed instructions how I can implement the scenario described above and I'd be happy to try it out. Otherwise please admit that there is a significant flaw in the composer preventing multi-language solutions that urgently needs fixing.

**Comment by boydc2014** [comment]
Add some context to this one to help the discussion. 

Today, LG functions are available in AdaptiveDialog actions via an interface "ITemplate", which in reality means SendActivity, Prompts(prompts in TextInput, ChoiceInputs, etc) only. And by design, it does auto multi-lang binding meaning, with one single reference format in dialog like "${Hello()}", we know which LG file to look at, and pick the right location for user. 

Now in this issue, and quite a lot of other issues, with the perception of LG auto multi-lang data binding, the request is to leverage LG to achieve the same experience like SendActivity, Prompts. 

Reacting to the requests, we did move a step forward, providing "namespace + exports" notions as a way to open LG functions to other actions, which is soon been queried and adopted by many customers. That gives us a confirmation that this scenario is valid and common.  Then the gap is this step is not ideal yet, because it requires a manual processing to add "exports and namespace" statement on top of LG file, and it don't have auto multi-lang binding.  

We've had a design review meeting with some "big rocks" and decided to take a step forward to open the LG functions more to all actions and have auto multi-lang. We did the discussion in R12, but was able to catch the R12 release in terms of implementation.

**Comment by sgellock** [comment]
@boydc2014 Tom and I have another option we want to pursue.  One that addresses the issue in the ChoiceInput and ConfirmInput prompts

**Comment by boydc2014** [comment]
> @boydc2014 Tom and I have another option we want to pursue. One that addresses the issue in the ChoiceInput and ConfirmInput prompts

Sure, sounds good. 

Just to be crystal clear, ChoiceInput and ConfirmInput's **prompts** (prompt, unrecognized prompt, invalid prompt) are already IActivityTemplate, so it's already enabled multi-lang binding via LG templates. 

The customer's request is about ChoiceInput's **choices** (which i referred as other actions).

**Comment by jamesemann** [comment]
@sgellock @boydc2014 we are facing this challenge too.  We are able to support multi language bots through lg on prompts/send activities but if we want to support multi language in the choice inputs themselves our solution/workaround is to have a per-language choice activity inside a condition for each language, which is clearly not the best authoring experience.

Can you share any additional information regarding the other option, or alternatively anything I could be missing.  Thank you! 🙏

**Comment by saskialorraine** [comment]
Hello there, are there any updates on how to handle the Confirm prompt input text translation in a more scalable and practical way?

**Comment by iliosana** [comment]
Hello @saskialorraine, I am using Composer and for simple yes/no confirmation prompts, the following worked for me:

![image](https://user-images.githubusercontent.com/95961035/194811582-8e07f8fc-50bb-4046-99f7-ebd76d101387.png)

I have omitted any confirm choices suggestions, this results in the composer displaying the options: yes/no or ja/nein automatically. I can then check the value of the property (in my case: dialog.cancelConfirmed) to determine whether the user selected yes/ja or no/nein. However, in case I added some choices and removed them later on, it would no longer work. I had to delete the 'Prompt for confirmation' action and create a new action.

Below you find my simple configurations:

PS: I have enabled localization in the 'Configure' section.

![image](https://user-images.githubusercontent.com/95961035/194812024-04dc3912-1534-4b89-8f88-5c292984b467.png)

![image](https://user-images.githubusercontent.com/95961035/194812220-dd6a82be-2a6d-43aa-937f-77a9695471ae.png)
