### ISSUE TITLE
CreateConversationAsync doesn't pass the tenantId

### ISSUE THREAD

**Issue by searlin** [microsoft/botbuilder-dotnet#2480]
I created issue in #2199 , actually, i pointed two bugs  in that issue, but only one bug was fixed, the other bug is that the tenantId is not used at all in CreateConversationAsync method, see below screenshot:
![image](https://user-images.githubusercontent.com/10204632/64414228-96e16780-d0c5-11e9-95b3-a449155e8053.png)

**The eventActivity.Conversation should have tenantId value**, see below screenshot:

![image](https://user-images.githubusercontent.com/10204632/64418797-402c5b80-d0ce-11e9-963f-2814906ed1ae.png)

Then when run  the **TenantIdWorkaroundForTeamsMiddleware**, the turnContext.Activity.Conversation.**TenantId** is empty, and will try parse the turnContext.Activity.ChannelData, but the ChannelData is null, see below screenshot:

![image](https://user-images.githubusercontent.com/10204632/64418934-74078100-d0ce-11e9-9f8e-d2e305e9aae1.png)

I don't know how the contributor pass the test, can they CreateConversationAsync using the **msteams** channel to do the test ?

[bug]

**Comment by hcyang** [comment]
@EricDahlvang, this is an issue with Teams, please take a look. Thanks.

**Comment by cleemullins** [comment]
@searlin, We are doing a major iteration on the Bot Framework integration with Teams in the 4.6 cycle (shipping on Oct 31). This work involves full support for Teams in the v4 SDK and will include examples around proactive messaging. @EricDahlvang should be able to get you working in the short term, but be aware of a new version coming soon.

**Comment by mdrichardson** [comment]
@searlin I'll continue looking into this, but a quick workaround would be to either use [this override](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L826) (which that PR addressed):

```csharp
public virtual async Task CreateConversationAsync(string channelId, string serviceUrl, MicrosoftAppCredentials credentials, ConversationParameters conversationParameters, BotCallbackHandler callback, ConversationReference reference, CancellationToken cancellationToken)
```

or, [use Connector](https://stackoverflow.com/questions/57120193/how-can-my-teams-bot-start-a-new-11-chat-with-a-known-user/57150951#57150951):

```csharp
var teamConversationData = turnContext.Activity.GetChannelData<TeamsChannelData>();
var connectorClient = new ConnectorClient(new Uri(activity.ServiceUrl), _credentialProvider.AppId, _credentialProvider.Password);

var userId = <UserIdToSendTo>;
var tenantId = teamConversationData.Tenant.Id;
var parameters = new ConversationParameters
{
    Members = new[] { new ChannelAccount(userId) },
    ChannelData = new TeamsChannelData
    {
        Tenant = new TenantInfo(tenantId),
    },
};

var conversationResource = await connectorClient.Conversations.CreateConversationAsync(parameters);
var message = Activity.CreateMessageActivity();
message.Text = "This is a proactive message.";
await connectorClient.Conversations.SendToConversationAsync(conversationResource.Id, (Activity)message);
```

A Teams message **must** have `ChannelData` in order to work with Teams, so I'll look into the specific override you're using and see if there's a PR worth filing against it.

**Comment by mdrichardson** [comment]
Have a solution w/ the help of @EricDahlvang. Working on PR.

**Comment by EricDahlvang** [comment]
Hi @searlin 

Thank you for reporting this, and the clear and concise description of the problem.  

Until the fix is released, please let us know if the [workaround ](https://github.com/microsoft/botbuilder-dotnet/issues/2480#issuecomment-528964314) @mdrichardson provided unblocks you.

**Comment by mdrichardson** [comment]
@searlin

> I don't know how the contributor pass the test, can they CreateConversationAsync using the msteams channel to do the test ?

Turns out the test I wrote for that previous PR uses MockAdapter, which [overrides the `CreateConversationAsync` method that needs to be fixed and appropriately sets the `ChannelData`](https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Builder.Tests/BotFrameworkAdapterTests.cs#L128):

```csharp
public async override Task CreateConversationAsync(string channelId, string serviceUrl, MicrosoftAppCredentials credentials, ConversationParameters conversationParameters, BotCallbackHandler callback, CancellationToken cancellationToken)
{
    var activity = conversationParameters.Activity;
    activity.ChannelData = new
    {
        conversationParameters.TenantId,
    };
    await RunPipelineAsync(new TurnContext(this, conversationParameters.Activity), callback, cancellationToken).ConfigureAwait(false);

    return;
}
```

Looks like I've got some work to do and some tests to fix.

**Comment by mdrichardson** [comment]
@searlin 

PR submitted. If I may ask, why are you using `Adapter.CreateConversationAsync` instead of `Connector.CreateConversationAsync`? I believe that to do a proactive message, you'd need a reference to the `conversationId` and `Adapter...` doesn't return it, whereas `Connector...` does. Can you share how you're using it (for my own benefit)?

**Comment by searlin** [comment]
Thanks a lot for all your help, the workaround works perfect, and I will use it for short term. 
And @mdrichardson  the reason why I chose Adapter.CreateConversationAsync is that it's the most obvious method I can find to send a proactive message, and the Adapter do return the conversationId in the callback ( turnContext.Activity.Conversation ), below is how I use it:

![image](https://user-images.githubusercontent.com/10204632/64499593-46981e80-d2ec-11e9-8a08-0bbc100ed7e0.png)
