### ISSUE TITLE
DirectLine object is not adding the bot to the conversation if request sent from the teams.

### ISSUE THREAD

**Issue by Basavarajsk1992** [microsoft/botbuilder-dotnet#2503]
I am trying to chat with a bot through its direct line key from another bot which is configured on MS teams channel. Whereas same is working from the emulator.
Below is the code sample
```
DirectLineClient client = new DirectLineClient(directLineSecret);
conversation = await client.Conversations.StartConversationAsync();
```
I am getting conversationUpdate event only once in targeted bot.
`{"type":"conversationUpdate","timestamp":"2019-09-11T10:15:05.4289157Z","membersAdded":[{"id":"zBot-development@31dmTQFIR-M","name":"zBot-development"}],"text":"","attachments":[],"entities":[],"address":{"id":"KegdNRjUXQT","channelId":"directline","user":{"id":"6wpjNfDy9aLFieMDDydhq5-d"},"conversation":{"id":"6wpjNfDy9aLFieMDDydhq5-d"},"bot":{"id":"zBot-development@31dmTQFIR-M","name":"zBot-development"},"serviceUrl":"https://directline.botframework.com/"},"source":"directline","agent":"botbuilder","user":{"id":"6wpjNfDy9aLFieMDDydhq5-d"}}`

**Comment by tsuwandy** [comment]
@EricDahlvang, could you take a look and chime in?  Thanks!

**Comment by EricDahlvang** [comment]
Hi @Basavarajsk1992 

When using the secret to create a conversation with Direct Line, there is no way for the channel to know who what the user.id is until the user sends a message.  The Emulator knows the user.id, because it generates it... so when the Emulator creates the conversation it is able to send both bot.id and user.id ConversationUpdate.  In order to accomplish this with the Direct Line, it is necessary to embed the user.id in the token while exchanging the secret for a token.  More information can be found here: https://blog.botframework.com/2018/09/25/enhanced-direct-line-authentication-features/

note: exchanging a secret for a token should be server side.  The secret should not be embedded in distributed applications or web pages.

Here is an example of how to embed the user.id in the token, and use the token to connect with the DirectLineClient.

```cs
            HttpClient httpClient = new HttpClient();
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post,$"https://directline.botframework.com/v3/directline/tokens/generate");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", directLineSecret);
            fromUser = $"dl_{Guid.NewGuid()}";
            request.Content = new StringContent(
                JsonConvert.SerializeObject(
                    new { User = new { Id = fromUser } }),
                    Encoding.UTF8,
                    "application/json");
            var response = await httpClient.SendAsync(request);
            DirectLineToken dlToken = null;
            if (response.IsSuccessStatusCode)
            {
                var body = await response.Content.ReadAsStringAsync();
                dlToken = JsonConvert.DeserializeObject<DirectLineToken>(body);
            }
            string token = dlToken.token;

            DirectLineClient client = new DirectLineClient(token);            
            var conversation = await client.Conversations.StartConversationAsync();   
```

After StartConversationAsync(), the bot will receive a ConversationUpdate for both bot.id and user.id members added.

**Comment by EricDahlvang** [comment]
Does this work for you @Basavarajsk1992 ?

**Comment by EricDahlvang** [comment]
Hi @Basavarajsk1992 

I'm closing this issue and assuming the code provided works for you.
