### ISSUE TITLE
IBotContext information lost upon thread switches

### ISSUE THREAD

**Issue by wmeints** [Microsoft/botbuilder-dotnet#259]
Hi,

Last few days I've been trying out a few things with the new botbuilder SDK. I'm using Akka.NET to implement my dialog flow. I really like Akka.NET because I can easily implement an actor based on the finite state machine pattern to model different stages of the conversation that my bot is in.

I noticed however that when I pass the IBotContext as a message to my Akka actor information is lost and the call `ReplyToActivity` on IBotContext doesn't result in a message to the user of my bot.

I'm curious what happens with the IBotContext object when I pass it to another thread. Could it be that information is lost when I do this?

**Comment by drub0y** [comment]
**DISCLAIMER:** I'm familiar with a couple Actor systems and the Actor model in general, but not steeped in Akka.NET specifically.

First, to make sure I'm understanding you correctly, you're trying to pass the `IBotContext` through to your actor via a message, correct? If so, I'm relatively certain that's not going to work. Actor messages are meant to essentially be POCOs that get serialized, sent to a mailbox (in Akka.NET's case) and then delivered to an actor "in time". While `IBotContext` is technically thread safe, it is not able to be serialized and "remoted" in this this way. Besides, it would be violating the rule of passing a mutable object to an actor [which is frowned upon](http://getakka.net/articles/concepts/actor-systems.html#actor-best-practices).

You also wouldn't be able to inject it via Akka.NET "props" because the props are only resolved when an actor instance is created and if that actor "lives" throughout many activity messages from the bot framework perspective, it would need to be working with the proper `IBotContext` for each of those messages.

I do actually think actor systems are potentially a really good match for implementing bots, I just don't think the current abstractions of the v4 SDK as it stands right now are going to "fit" that kind of system naturally due to the major architectural differences actor systems present from a traditional application architectures. It would not be a stretch to imagine a more native SDK for Akka.NET (or other actor systems) at some point in the future, but, full disclosure, I'm not on the product team so I'm not promising anything. 😄 

Anyway, let's think... how could you do this right now? 🤔 I assume right now you are using some sort of API gateway leveraging ASP.NET, resolving an `ActorRef` and that's when you tried to send it over the `IBotContext` via a `Tell` based message... maybe? Spitballing here: what if, instead of sending over the `IBotContext` itself, you sent over only the `Activity` and maybe even your state, but you do so with an `Ask` and then your API gateway awaits that, takes the result of the `Ask`, which would be a respone message with maybe `List<Activity>` and your state again, and marshals those back onto the `IBotContext`???

**Comment by wmeints** [comment]
I think passing a message (the activity) to the actors is indeed a better method of working. In almost all cases I will be sending a reply to the user so that looks good too. 

Let me give it a try and see what happens :-)

**Comment by wmeints** [comment]
Here's the code that I wrote: https://github.com/wmeints/bot-actors-sample

**Comment by cleemullins** [comment]
This is nice!

**Comment by cleemullins** [comment]
@wmeints, the email address listed in your GitHub profile bounces. Are you in Redmond for the MVP Summit? If so, please join us for our Bot Round Table tomorrow morning. 9:30 AM in the Building 35 Lobby.

**Comment by wmeints** [comment]
I'm at the MVP summit, so I can join you for the round table. See you in building 35!

**Comment by drub0y** [comment]
@wmeints I'm going to close this issue now that we've sorted it out.
