### ISSUE TITLE
Reply method only available on Activity type

### ISSUE THREAD

**Issue by wmeints** [Microsoft/botbuilder-dotnet#264]
Just noticed that when you use `IActivity`, you don't have an option to create a reply from that instance directly. You first need to cast it to `Activity` and then invoke `CreateReply` on that. Is this intentional?

**Comment by cleemullins** [comment]
The Reply method has been depricated. SendActivity() is now a method found on the IBotContext that's passed into the relevant handlers. 

We now pass Activity around, instead of IActivity, so this particular issue should be resolved. 

In addition, you can:
1. Use the MessageFactory, which will create a message
2. Call SendActivity and pass in text, which will also create a message. 

Hopefully, this gets you through! :)
