### ISSUE TITLE
unauthorized error when sending to directline.

### ISSUE THREAD

**Issue by vidya091209** [microsoft/botbuilder-dotnet#2714]
## Version
What package version of the SDK are you using.

## Describe the bug
same code was working for both team channel and directline.
but this only failing for directline and works for teams. this started ha penning form last 3 days. and happening continuously.

```csharp
var bundle = new ConnectorClientMessageBundle(
                recipient.ServiceUrl, messageActivity, _microsoftAppCredentials);

            ResourceResponse resourceResponse = null;

            try
            {
                resourceResponse =
                    await bundle.ConnectorClient.Conversations.SendToConversationAsync(
                        (Activity)bundle.MessageActivity);
            }
            catch (UnauthorizedAccessException e)
            {
                Logger.Log($"Failed to send message: {e.Message} appId: {_microsoftAppCredentials.MicrosoftAppId}");
            }
            catch (Exception e)
            {
                Logger.Log($"Failed to send message: {e.Message} appId: {_microsoftAppCredentials.MicrosoftAppId}");
            }
```

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by mdrichardson** [comment]
@vidya091209 

* When you say "happening continuously", do you mean that it happens with every attempt from Directline? 

* Can you provide your `MicrosoftAppId` so I can look into this on the back end?

* What are you trying to accomplish with this? It looks a little like proactive messaging, but I can't tell for sure. If so, this sounds like it's possibly a [TrustServiceUrl Issue](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp#avoiding-401-unauthorized-errors).

If it is a TrustServiceUrl issue, you can fix it by adding your channel's ServiceUrls to the list of trusted URLs:

```
var serviceUrl = <GetThisFrom Activity.ServiceUrl>;

MicrosoftAppCredentials.TrustServiceUrl(serviceUrl);
```

[Here's a link](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Connector/Authentication/MicrosoftAppCredentials.cs) to the library, if that helps. Otherwise, [browsing these issues](https://github.com/Microsoft/BotBuilder/issues?q=label%3A%22Trust+Service+URL%22+is%3Aclosed) should help.

**Comment by vidya091209** [comment]
Thanks for your help.
