### ISSUE TITLE
UserId & SessionId not sent to Application Insights

### ISSUE THREAD

**Issue by VincentDeBie** [microsoft/botbuilder-dotnet#2716]
I connected a bot application to Application Insights via the Telemetyclient. For this I followed all the instructions on https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0. Everything seems to work fine except my session_Id and user_Id columns in the Application Insights logs are allways empty. I excpected the columns to contain values, since I added this piece of code (as stated in the documentation):

// Add telemetry initializer that sets the user ID and session ID (in addition to other bot-specific properties such as activity ID)
    services.AddSingleton<ITelemetryInitializer, TelemetryBotIdInitializer>();

![image](https://user-images.githubusercontent.com/25502665/66653473-7498b780-ec38-11e9-8278-80d3d623465e.png)

**Comment by v-kydela** [comment]
Hi @VincentDeBie - Let's see if I can help.

While I can see your `requests` table seems to be populated, bot telemetry generally goes in the `customEvents` table as seen in the [document](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0#querying-your-telemetry-data-in-application-insights-using-kusto-queries) you linked. Also, that kind of data will be found in the `customDimensions` column rather than the `session_Id` or `user_Id` columns which aren't really used for bots. You might be interested in reading my [Bot Analytics blog post](https://blog.botframework.com/2019/03/21/bot-analytics-behind-the-scenes/) for more information.

Does this resolve your issue?

**Comment by v-kydela** [comment]
@VincentDeBie - Are you still working on this?

**Comment by VincentDeBie** [comment]
Hi @v-kydela ,
Yes, I am still working on this issue.
This is what the info in the customDimensions column of my customEvents table looks like:
{"AspNetCoreEnvironment":"Test","InstanceId":"11bfb634-f325-43f3-a453-429a71447928","DialogId":"rootdialog"}
What exactly is the InstanceId? And should there be other info in this column?
Thanks!

**Comment by v-kydela** [comment]
Hi @VincentDeBie - You'll need to look at the other columns to get context for the **customDimensions** column. For example, when the **name** column says Activity, I expect the **customDimensions** column to contain information like the bot ID and user ID and conversation ID. What do you see in your **name** column?

**Comment by v-kydela** [comment]
@VincentDeBie - Do you still need help?

**Comment by VincentDeBie** [comment]
Hi @v-kydela ,
It appeared that I had a wrong configuration in my bot channels registration settings. Thereby not all information got through. Now I indeed see the conversation ID in the customDimensions column.
My problem is solved. Thanks for the help!

**Comment by v-kydela** [comment]
@VincentDeBie - I'm glad to hear that you got this resolved. Would you let us know which setting you had to fix so we can help others in the future?

**Comment by VincentDeBie** [comment]
In my Bot Channels Registrations resource at the Settings tab, you have to fill in 2 keys and an ID under the Analytics section. I didn't configure them right. I still had some old values from a previous Application Insights resource there.
