### ISSUE TITLE
When Foreach loops too many actions, runtime will got StackOverFlow exception

### ISSUE THREAD

**Issue by luhan2017** [microsoft/botbuilder-dotnet#2727]
## Version
4.Future branch

## Describe the bug
When Foreach loops too many actions, runtime will got StackOverFlow exception

## To Reproduce
1. Foreach loop an array which contains 100+ elements.
2. add a SendActivity action in the loop.
3. Run the bot.

[bug]

**Comment by tomlm** [comment]
we need to dig into this as I think this is an architectural flaw in our queue execution logic. 

We are assuming that we will only process a certain number of actions a turn, in this case, each step ends up being executed as a separate action queue that is processed via ContinueDialog(nextStep).  

because 1000 sendActivities don't end the turn, we nest 1000 deep on API calls and blow the stack.  

Normally I might think this is a corner case, but it seems highly likely that people will attempt to do this exact scenario to send notifications to all of their customers.

**Comment by tomlm** [comment]
I have added repo case to branch **tomlm/foreach** in dotnet repo
Unit test is: **TestForeachWithLargeItems**

**Comment by Stevenic** [comment]
What would you propose as a solution? We could add a max items constraint to the ForEach.  I don't know how we prevent nesting the calls...

**Comment by tomlm** [comment]
Yeah, I don't have good suggestion.  The problem is that it blows us up though. :(

**Comment by Stevenic** [comment]
I looked at the code and what we basically need to do is add a mechanism for detecting that plan changes have been queued up either locally or by a parent dialog.  This will let us switch to using a `while` loop when processing local changes.  Any queued up parent changes would still need to be executed via a recursive call but those are rare.

Since this is a P1 we can work on a fix once the other P0's are done.

**Comment by boydc2014** [comment]
If i remember correctly, in @benbrown's environment, 15 elements can blow it up, right?
