### ISSUE TITLE
OAuthPrompt Sign-in never allows to select an account

### ISSUE THREAD

**Issue by armstrong-charles** [microsoft/botbuilder-dotnet#2833]
I am using my bot(v4 Enterprise bot) from Teams where when sign-in is clicked, it launches browser with oauth sign in dialog (https://token.botframework.com/api/oauth/signin?signin=aabbccdd....), but could not allow to select an account, it automatically selects last selected account and closes.

**Comment by mdrichardson** [comment]
I can repro this with AADv2, AADv1, and Slack and can't seem to find anywhere in our code that determines whether or not to have the user fully log back in. I have a feeling that this is by design as it's significantly more convenient for a user to only need to sign in once. My best guesses are that either:

* This is controlled by the OAuth provider via some sort of token caching. Once expired, it would display the username prompt again, or
* This is controlled by Teams

This is possibly something in the Botframework, but again, I can't seem to find it.

I'll forward this to the development team to determine, 1) if this is a bug or intended design, and 2) whether it's a Botframework issue or we need to forward it to the appropriate party.

**Comment by armstrong-charles** [comment]
@mdrichardson i am using AADv2, in my case, when user successfully sign-in to wrong AAD, there is no way to sign-in him back to right AAD, is there any workaround? Thanks

**Comment by mdrichardson** [comment]
@armstrong-charles The only workaround I could find was to:

1. Chat with the bot so that it takes the user through the logout flow. In the OAuth samples, this is by simply typing `logout`

2. Sign out of Teams and restart the app

**Comment by EricDahlvang** [comment]
For AAD apps, you can go here: https://portal.office.com/account/#apps  and revoke the apps permissions.  Then you will be required to sign in again and authorize the app.

**Comment by mdrichardson** [comment]
@armstrong-charles Are you able to get either of these workarounds to accomplish what you need?

**Comment by armstrong-charles** [comment]
AADv2

**Comment by mdrichardson** [comment]
@armstrong-charles I think you may have replied to the wrong comment. Are you able to get either of these workarounds to accomplish what you need?

**Comment by armstrong-charles** [comment]
@mdrichardson, Is it possible to do it without sign-out of teams and restart the app (Step 2).

**Comment by mdrichardson** [comment]
@armstrong-charles Not that I'm aware of. It should only be a one-time thing, though, right, until they sign into the right tenant?

**Comment by armstrong-charles** [comment]
@mdrichardson, it is good, atleast app could put out information to user how to get out of the situation ---  because there are more than one reason to get into this situation, e.g.: user could sign-in to wrong tenant or he is in the right tenant but he is not seeing the resource due to some other reason (IT admin configuration).
