### ISSUE TITLE
Why are some projects excluded from the debug build?

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#2881]
On a fresh sync of master there are some projects excluded from debug builds.  This causes build errors, so I suspect not on purpose.

![image](https://user-images.githubusercontent.com/17637681/67800935-6d99e380-fa45-11e9-98ec-1d56ca90fbe5.png)

[bug]

**Comment by cleemullins** [comment]
The standard "Debug" build of the solution results in all packages *except* the WebAPI packages being built. This is simply to allow faster building/debugging in the general case. 

The "Debug with Nuget" profile builds all the Nuget packages (including WebAPI). 

This is by design, as the WebAPI projects are so rarely touched.
