### ISSUE TITLE
Adaptive Card not rendering on Slack

### ISSUE THREAD

**Issue by Anshul21** [microsoft/botbuilder-dotnet#2887]
## Version
What package version of the SDK are you using.
4.5.1

## Describe the bug
Adaptive cards (v1.0) renders as an image on slack. I am trying to use inputform adaptive card on to the slack. It works on teams and emulator

## To Reproduce
1. Take Adaptive cards bot example
2. Use InputForm adaptive card found https://adaptivecards.io/designer/ here. 
3. Publish the bot to slack

## Expected behavior
Adaptive Card should render on slack.

## Additional context

[bug]

**Comment by v-kydela** [comment]
Slack does not support Adaptive Cards. The Bot Framework Slack connector will try to convert the card to an image as well as it can, but it's probably best not to use Adaptive Cards on channels that don't support them. You can see which channels support Adaptive Cards [here](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners).

As a workaround you can have the bot gather the needed information using prompts, or you can host the input form on another web page and have the bot link to it.

I have not tried this, but it looks like Slack's [Block Kit](https://api.slack.com/block-kit/interactivity) enables a lot of the same functionality as Adaptive Cards so you could try that as well. You can use [channel data](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-channeldata?view=azure-bot-service-4.0#create-a-full-fidelity-slack-message) to implement special Slack functionality.

Does this resolve your issue?

**Comment by v-kydela** [comment]
@Anshul21 - Are you still working on this?

**Comment by Anshul21** [comment]
@v-kydela I see only one solution from here, write the custom renderer for slack on bot. thinking to do something like this 
if channel is slack, then use botkit json to render results else keep using adaptive cards. I am just curious to know if bot framework would support adaptive cards on  slack in near future of not?.]

Thanks
Anshul

**Comment by v-kydela** [comment]
Hi @Anshul21 

It's not up to the Bot Framework to support Adaptive Cards on a third-party channel. It is up to each third-party chat service to support Adaptive Cards in their client applications. I highly doubt Slack would be interested in doing that since they already have their own Block Kit system.

If you're talking about some kind of Adaptive Cards to Block Kit converter, that might be possible, but the Bot Framework team has no plans to support such a thing. You can suggest the idea in one of the [Bot Builder Community](https://github.com/BotBuilderCommunity) repos, and if you decide to make it yourself then I'm sure your contributions will be welcome.

Is this answer satisfactory?

**Comment by v-kydela** [comment]
@Anshul21 - Do you still need help?

**Comment by Anshul21** [comment]
@v-kydela i am looking into the hero card documentation and trying to see if i can use html rich text to render different elements. I am not sure if slack would support that or not.

**Comment by v-kydela** [comment]
@Anshul21 - That is correct. Anything you find in the Teams documentation should be assumed to apply to Teams specifically.

I assume you were able to get Slack's Block Kit working, so I will close this issue now. If you need more help, please open a new issue.
