### ISSUE TITLE
Adaptive Card ActionSet element removed from card body when transmitting through DirectLine

### ISSUE THREAD

**Issue by brett-1hw** [microsoft/botbuilder-dotnet#2912]
## Version
4.6.0-preview2

## Describe the bug
Adaptive Card ActionSet element removed from card body when transmitting through DirectLine channel.

## To Reproduce
1. Add adaptive card attachment containing an ActionSet element such as the example on [https://adaptivecards.io/explorer/ActionSet.html](https://adaptivecards.io/explorer/ActionSet.html)

2. Verify ActionSet rendering in emulator

3. When receiving activity messages through the DirectLine channel, the ActionSet element will be missing from the body of the card attachment.

4. Verify ActionSet element missing from activity in DirectLine https://directline.botframework.com/v3/directline/conversations/{conversationId}/activities?watermark={watermark}

## Expected behavior
DirectLine does not filter or remove adaptive card elements.

**Comment by v-kydela** [comment]
Hi @brett-1hw 

This is a known issue. [The fix is planned for deployment around 11/22.](https://github.com/microsoft/BotFramework-Services/issues/87#issuecomment-548914349) In the meantime there is a [workaround](https://github.com/microsoft/BotFramework-Services/issues/87#issuecomment-500662897) which involves using a different content type for the attachment.
