### ISSUE TITLE
Perf: LuisRecognizer blocks returning RecognizerResult on TraceActivity

### ISSUE THREAD

**Issue by shahidkhuram** [microsoft/botbuilder-dotnet#2946]
## Version
4.5.3

## Describe the bug
LuisRecognizer.RecognzieAsync sends a Trace activity as part of the operation. However, this SendActivity call is awaited and blocks returning the recognizerResult object to the caller. Depending on the Adapter and transport, this SendActivity call can be quite expensive. Sending the trace activity is unnecessarily blocking the recognizer result and delays the caller from processing the request further.

Independent from the topic of which adapters and channels forward activities, I suggest the TraceActivityAsync call in RecognizerInternalAsync not be awaited.

https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.AI.LUIS/LuisRecognizer.cs#L399

## To Reproduce
1. Start with any both that uses the LuisRecognizer
2. Enable the Direct Line Speech Channel and use the Streaming extensions packages
3. Connect to the bot (e.g. using Direct Line Speech Client application)
4. Measure the time delta between the LUIS http request completing and the LuisRecognizer.RecognizeAsync operation completing. This can be hundreds of milliseconds.

## Expected behavior
LuisRecognizer.RecognizerAsync operation call should complete as soon as the http call to LUIS finishes with the result. This method shouldn't block on any other external communication. 

[bug]

**Comment by johnataylor** [comment]
The code pointed to in this issue is correct. The LuisRecognizer code calls LUIS using the ILUISRuntimeClient and then calls Telemetry and then creates a Trace Activity. Note Telemetry is a best-effort optimized mechanism and the sending of a Trace Activity is a notification to any Middleware components and the Emulator.

You are free to use the ILUISRuntimeClient by itself. In which case you will skip the Telemetry and the sending of a Trace Activity.

The BotFrameworkAdapter _only actually **sends** a Trace Activity if the channel is the **Emulator**_:

https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L427

However, it always invokes the Middleware.

So either:

1. you have an expensive Middleware that has neglected to filter out Trace Activities or
1. the adapter you are using has a bug and attempts to actually send Trace Activities to the channel

Can you confirm?

**Comment by DDEfromOR** [comment]
FWIW in the GA version of the SDK the Streaming library interactions don't come into play until after the decision to send the trace activity has already been made, on line [433 ](https://github.com/microsoft/botbuilder-dotnet/blob/b885980d855f2386e2d617234ecbc3afe0a79ee2/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L433) so it shouldn't be causing the trace to be sent for non-emulator channels. Obviously this does not address the core issue of the slow calls though. 

I'd recommend updating to the 4.6.2 SDK, which has the Streaming library integration included as part of the existing adapters. Earlier versions of the SDK used preview versions of the Streaming integration that could potentially have bugs.

**Comment by cleemullins** [comment]
I believe, based on feedback from @johnataylor and @DDEfromOR that we can close this out.
