### ISSUE TITLE
Inspection middleware needs to be updated for Teams team chat

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-dotnet#2955]
The inspection middleware intercept check needs to be updated to handle messages coming from Teams checking specifically for messages coming from a team.

**Comment by johnataylor** [comment]
As it is today you can inspect one on one, inspect in group chat, however inside a Team you can only inpect the particular _thread_ you originally attached to.

This seems like an unreasonable limitation. We should look at a better model, for example, consider the semantics of: once you are attached from anywhere inside a Team you are attached to everywhere (i.e. all threads and all channels) in that Team.

**Comment by johnataylor** [comment]
JavaScript issue: https://github.com/microsoft/botbuilder-js/issues/1406

**Comment by johnataylor** [comment]
around here https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/Inspection/InspectionMiddleware.cs#L149

// if we are in a MS Teams Team then use the TeamId otherwise fall back to the ConversationId
var attachId = turnContext.Activity.TeamsGetTeamInfo()?.Id ?? turnContext.Activity.Conversation.Id;
if (AttachCommand(attachId, sessions, sessionId))
// etc. etc.
