### ISSUE TITLE
Adaptive Dialogs. TextInput validation works for a single string only. Validation against a list of strings fails

### ISSUE THREAD

**Issue by gbelenky** [microsoft/botbuilder-dotnet#3027]
## Version
4.6.0-preview2
## Describe the bug
Adaptive Dialogs. TextInput validation works for a single string only. Validation against a list of strings fails with an exception
 
## To Reproduce

new TextInput()
                                    {
                                        Property = "turn.phoneSelection",
                                        Prompt = new ActivityTemplate("[SelectPhone]"),
                                        Validations = new List<String>()
                                        {                                       
                                            "equals(this.value,'Samsung')",
                                            "equals(this.value,'Apple')",
                                            "equals(this.value,'Huawei')"
                                        },
                                        InvalidPrompt = new ActivityTemplate("Sorry, {this.value} does not work. Can you give me a different brand name?"),
                                        MaxTurnCount = 2,
                                        AlwaysPrompt = true                                        
                                    },

## Expected behavior
Expecting that the value validates against one from the list above
[bug]

**Comment by vishwacsena** [comment]
@gbelenky This is by design. We process the validation expressions in the order they were specified, expect all validations to pass (if a list) in order for the input to be considered valid but fail validation as soon as one of the validation expressions fail.

For your specific use case, you could get this to work -
```
Validations = new List<string>()
 {
     "contains(createArray('samsung', 'apple', 'huawei'), toLower(this.value))"
 }
```

You can always use one of the many available pre-built functions as part of the [common expression language](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/common-expression-language/prebuilt-functions.md#pre-built-functions)
