### ISSUE TITLE
ActionTypes.Call on HeroCard not working in Microsoft Teams Desktop

### ISSUE THREAD

**Issue by billbrinck** [microsoft/botbuilder-dotnet#3040]
When using Microsoft Teams on the Desktop, the ActionTypes.Call buttons are doing nothing.

On iOS app it works and aswell as in the Bot Emulator.

**Comment by mdrichardson** [comment]
@bribi093 Can you clarify, `ActionTypes.Call` *is* working in the Teams iOS app, but not in the Desktop app?

If that is the case, then the issue is with the Teams desktop client and you'll need to [open an issue in their UserVoice](https://microsoftteams.uservoice.com/forums/908686-bug-reports).

If you believe this is incorrect, please provide additional details that show why this is a Bot Framework issue, and not a Teams one.

**Comment by bribi093** [comment]
So, I have a bot in .NET which is used in Microsoft Teams and deployed in Azure. 

If a user enters a command, the bot will return a HeroCard with multiple Actions on it. These actions are ActionTypes.Call with a phone number as value. 

When I try this on iOS Microsoft Teams app, it works: So I can click on the action button and it will open a call on the iPhone. 
In the desktop application of Microsoft Teams, nothing happens. So, if I click on a action button, nothing happens.

Strange is, that in the Bot Emulator it works as well.

**Comment by bribi093** [comment]
@mdrichardson Here is the code snippet, that returns the HeroCard.

![image](https://user-images.githubusercontent.com/22788111/69785160-b9ac8500-11b7-11ea-8dc1-0cfe3f728017.png)

**Comment by mdrichardson** [comment]
Since your code looks fine and this is working in every client you've tested except Teams Desktop, this sounds like a Teams issue. Please [open an issue with them](https://microsoftteams.uservoice.com/forums/908686-bug-reports) -- there's not much we can do about it on the Bot Framework side.

You mentioned your company had a meeting with Microsoft in the past--if you have a CSA and can escalate this to Customer Service Support, that might work better than the UserVoice.
