### ISSUE TITLE
Support TTL configuration for CosmosDbStorage

### ISSUE THREAD

**Issue by bojingo** [microsoft/botbuilder-dotnet#3086]
Looking for a way to define a TTL for all Cosmos DB documents created by the Bot Framework. Ideally, this would also include defining a TTL as part of the collection creation options, as well as at the individual document level.

Not sure of the implications of such a feature to the framework overall, but in my client use case this was incredibly useful.

**Comment by mdrichardson** [comment]
Looks like this is [definitely possible](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-time-to-live). I know we've had requests for something like this before.

@bojingo I'll forward this on to the dev team.

**Comment by bojingo** [comment]
I imagine this is a matter of adding a Ttl property to Microsoft.Azure.Documents.Client.RequestOptions so that the `Microsoft.Bot.Builder.Azure.CosmosDbStorageOptions.DocumentCollectionRequestOptions` and `DatabaseCreationRequestOptions` properties can tell the CosmosDbStorage class how to define the collection during creation and the documents during write to have the desired TTL. 

Behavior semantics of defining the Ttl property in these config properties:
* If not specified at the `DatabaseCreationRequestOptions` level, the collection won't support TTL (unless subsequently changed...)
  * If the collection doesn't have a TTL defined and the `DocumentCollectionRequestOptions` has a value, the setting will be ignored by Cosmos DB.
  * If the collection got a TTL subsequently after create and the `DocumentCollectionRequestOptions` has a value, the document will successfully have the TTL applied
* If specified at `DatabaseCreationRequestOptions` level but not at the `DocumentCollectionRequestOptions` level the document will inherit the TTL from the collection. 
* If defined in both, the `DocumentCollectionRequestOptions` would take priority on individual documents. 

FYI, in my case I manually modified the collection after the Bot Framework created it to give it a default TTL of a day and have had no negative ramifications in the bot implementation or behavior. Only impact is that after a day everyone's conversation and user state is reset to empty - which was intended. :)

**Comment by gabog** [comment]
Hi @bojingo, this is a good suggestion, I am tagging it for consideration in our next iteration.

Thanks

**Comment by christopheranderson** [comment]
I'll revisit this once R8 planning is settled.

Some initial thoughts are that, for collection level, we don't need to specifically enable this in our SDK because, as you said, it can be modified later. We have automatic container creation in the SDK as a QOL feature, but you can create it on your own ahead of time/write your own container creation step on start up. You can even modify our indexing policy settings which could break our queries for the old provider. We would need to make a change to enable per document ttl.

Biggest concerns with ttl being enabled in general is the lack of debuggability that Cosmos's TTL feature offers. There is no trace in the changelog/etc. that it was removed, so if you're getting end users that are upset their state was deleted,  you'll have a hard time root causing it.

I think we should definitely provide guidance for how/when to detect you can delete state. That guidance is pretty much non-existent today. So even if we say you should just set ttl yourself, we should give some guidance as to the consequences.

Fun fact: I did some napkin math and I think it works out that it costs 3x to delete a document than it does to store it for an hour (or deleting a document breaks even after the 3rd hour post-deletion). I'm not certain on the frequency of the billing metering for storage, so I'm not sure how it would pan out in reality. There's a good chance I missed a unit conversion here, though. Need to break out excel.

@bojingo - a few scoping questions:
1. Do you mind sharing what scenario you have where you want your state reset every day?
2. Why do you need it available at the document and collection level? Would you want to be able to say, for a given operation, how long it should be persisted, if we do document level?

**Comment by bojingo** [comment]
1. The scenario is using a bot to assist people working through tasks at a job site. The state of the job can change such that after a period of time elapses (1 day) we want to treat any continuation of work at the job like a brand new job/conversation. We certainly could have built in a lot of logic related to comparing timestamps and such to start over and discard past state, but in the interest of keeping it simple thought "what if the bot just forgets everything about past conversations?" That ended up proving to be trivial to implement with a TTL, and effective.
2. I suppose collection level would be sufficient. Not sure I have a reason to have distinct TTLs for different documents within the same collection. My description above was just my attempt at shortest path to getting this capability at all by simply extending `RequestOptions` to have a TTL property. And if we extend RequestOptions, the property would be available both for collection creation and all subsequent Cosmos operations, like writing individual documents. 

My problem domain's use case aside, Cosmos DB's TTL functionality is just awesome for cleaning up old data, anyway. I see that as reason enough to let the bot managed its own collection with a configurable TTL.
