### ISSUE TITLE
Cards not working on FaceBook messenger and in Web-chat

### ISSUE THREAD

**Issue by achrafbenalaya** [microsoft/botbuilder-dotnet#3175]
Hi ,
I'm trying to build a new bot , after Working a year ago with v3 , tried now with V4.

But i'm really disappointed , cards are not rendering and some other functions too .

Here is a picture in the emulator :

![image](https://user-images.githubusercontent.com/13398378/71259283-6356e000-2338-11ea-8619-da08d09207c9.png)

but , in the webchat : 

![image](https://user-images.githubusercontent.com/13398378/71259434-b9c41e80-2338-11ea-95e5-b49284c98c9a.png)

and in messenger  it become like a picture : 
![image](https://user-images.githubusercontent.com/13398378/71259478-d6f8ed00-2338-11ea-8b35-0825f5576243.png)

source code for json file   

```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.0",
    "body": [
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": 2,
                    "items": [
                        {
                            "type": "TextBlock",
                            "text": "PIZZA"
                        },
                        {
                            "type": "TextBlock",
                            "text": "Tom's Pie",
                            "weight": "bolder",
                            "size": "extraLarge",
                            "spacing": "none"
                        },
                        {
                            "type": "TextBlock",
                            "text": "4.2 ★★★☆ (93) · $$",
                            "isSubtle": true,
                            "spacing": "none"
                        },
                        {
                            "type": "TextBlock",
                            "text": "**Matt H. said** \"I'm compelled to give this place 5 stars due to the number of times I've chosen to eat here this past year!\"",
                            "size": "small",
                            "wrap": true
                        }
                    ]
                },
                {
                    "type": "Column",
                    "width": 1,
                    "items": [
                        {
                            "type": "Image",
                            "url": "https://picsum.photos/300?image=882",
                            "size": "auto"
                        }
                    ]
                }
            ]
        }
    ],
    "actions": [
        {
            "type": "Action.OpenUrl",
            "title": "More Info",
            "url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        }
    ]
}
```

**Comment by v-kydela** [comment]
@achrafbenalaya - Thank you for the feedback.

With regard to you Web Chat issue, it looks like you're using the iframe version of Web Chat. If you use [the latest version of Web Chat](https://github.com/microsoft/BotFramework-WebChat) as its meant to be used according to [these instructions](https://github.com/microsoft/BotFramework-WebChat#how-to-use), your card should render just fine:

![image](https://user-images.githubusercontent.com/41968495/71280261-9042cd00-230f-11ea-9955-2ec1fc7dfa9d.png)

With regard to your Facebook issue, this is expected behavior. Adaptive Cards are not supported on Facebook and you should not be using them on Facebook, but if you do then the Facebook channel connector will try its best to render the card and an image is the best it can do. You can see a list of official Adaptive Card host applications [here](https://docs.microsoft.com/en-us/adaptive-cards/resources/partners).

You can also read [my latest blog post](https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/) if you want to better understand how to use Adaptive Cards with the Microsoft Bot Framework.
