### ISSUE TITLE
RecognizerResult is unnecessarily serialized + deserialized

### ISSUE THREAD

**Issue by abharath27** [microsoft/botbuilder-dotnet#3176]
**Is your feature request related to a problem? Please describe.**
This is a performance concern. `AdaptiveDialog` sets the `RecognizerResult` object in the `turn.recognized` property. I see that we try to set the recognizer result as a primitive JSON object, so it is [first serialized and then deserialized](https://github.com/microsoft/botbuilder-dotnet/blob/3502f50f0e34a68e49c27ac1f998338f61a13780/libraries/Microsoft.Bot.Builder.Dialogs/ObjectPath.cs#L466) before the set happens. 

When I read the `Properties` from `turn.recognized`, I need to deserialize the `JObject` into my class. This feels unnecessary.

**Describe the solution you'd like**
Add an optional parameter (`bool json=true`) to [DialogManager.SetValue](https://github.com/microsoft/botbuilder-dotnet/blob/3502f50f0e34a68e49c27ac1f998338f61a13780/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Memory/DialogStateManager.cs#L243) where callers can specify if the object should be set as primitive JSON objects.

**Comment by christopheranderson** [comment]
@tomlm, can you please take a look at the proposed perf optimization and whether we should take it for R8?

**Comment by tomlm** [comment]
This behavior is by design.
There are a number of architectural reasons we want our memory system to always be JToken based.  
1. it reduces brittleness of the underling type system changing.
2. it reduces the brittleness of groveling over memory from expression libraries, etc. because everything is in uniform shape without having to resort to using reflection.
3. it ensures that different disperse components aren't taking dependencies on a specific typed version of an object.
