### ISSUE TITLE
[Ms Teams][C#] - MessageReaction- Unable to get the text for which User has reacted to the bot message 

### ISSUE THREAD

**Issue by Chekrii** [microsoft/botbuilder-dotnet#3189]
## Unable to get the text for which User has reacted to the bot message 

- Whenever a user reacts to the Bot response, we are unable to get the message for which the user has reacted.
-We are just getting "Like or Laugh" when user reacts but not the message.
-Can we get the message in any other way like Graph API?

Thanks.

**Comment by christopheranderson** [comment]
@johnataylor - should this be a sample maybe? This is really more of a question (potentially feature request).

**Comment by EricDahlvang** [comment]
@Chekrii If the reaction is to a message in a Team channel, you could query the roster and probably get the user's name based on a comparison of roster results with the activity.From.Id

An example of querying the roster for a Team can be found here: https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/57.teams-conversation-bot/Bots/TeamsConversationBot.cs#L103

`var members = await TeamsInfo.GetMembersAsync(turnContext, cancellationToken);`

@christopheranderson Teams does not send the user name with the MessageReaction (which is why our current samples do not include it: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/25.message-reaction https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/25.message-reaction )

**Comment by EricDahlvang** [comment]
@Chekrii I apologize for mis-reading the issue here.  

There is currently no built-in way to correlate incoming message reactions with previously sent messages.  The Message Reaction sample stores previously sent messages, and uses the activity.ReplyToId to find the previously sent message in the log: https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/25.message-reaction/ActivityLog.cs  This is the recommended approach.

**Comment by clearab** [comment]
If you're interested in using Graph, you can also use this endpoint to retrieve the message: https://docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&tabs=http.
