### ISSUE TITLE
Scope variable to know the current active dialog in the dialog stack

### ISSUE THREAD

**Issue by eduardmartos** [microsoft/botbuilder-dotnet#3210]
**Is your feature request related to a problem? Please describe.**
Since Bot Composer can easily become complex with many dialogs and flows, it would be very useful (at debug time) to know what the current active dialog is.
We try many combinations like:
dialog.name
this.dialog.name
this.dialogs[0].name
[...]
But none worked. As we have not been able to find the documentation on the properties of each scope variable, trying to find the solution by test and error can be crazy.

**Describe the solution you'd like**
Our workarround is to have a custom user.dialogPath variable that we set on each dialog first step with the current dialog name.
It would be nice to know if there is a var scope in bot composer that indicates the name of the current active dialog and, if it does not exist, create a new one.

**Describe alternatives you've considered**
Having a visual dialog stack for debug it could be amazing too.
If we have something like:
dialog.currentName = “IdentifyUserDialog”
dialog.currentStack = [ “IdentifyUserDialog”, “AssistanceDialog”, “MainDialog” ]
It means:
Current active dialog is “IdentifyUserDialog”
that was called from “AssistanceDialog”, that was called from “MainDialog”.

**Comment by vishwacsena** [comment]
@eduardmartos Thanks for the feedback. We will consider supporting in the core SDK and will use this ticket to track any work related to this ask as a DCR.

**Comment by vishwacsena** [comment]
@eduardmartos - does this resonate and meet your needs? 

At the core of this ask is the need to know the dialog stack. 

**Scenarios:** 
1. Debugging
2. Interruption handling
    a. I'm in an active prompt and using an intent to extract entities. I need to be able to tell within an OnIntent handler within that dialog what the active input action is? Without this, developer will need to write assumption logic that looks at filled/ unfilled properties to determine what the entity is for (or use LU concept like `role`).
    b. I'm in a parent dialog that is being consulted. I need to know what is the active child dialog to determine the type of interruption to allow. E.g. if the child dialog is about booking flight and the user is asking for a joke as an interruption, I want to execute an EditAction plan with appendActions. In other cases, I need to execute a `replaceActions` plan change. Knowing the leaf dialog that is initiating consultation is critical for this decision making.

**Proposal:**
`turn.currentDialogStack` holds the actual dialog stack. Since every action within adaptive dialog is also a dialog, the stack will not include the active action dialog in it (e.g. sendActivity) 

Let's assume this stack - Dialog A -> Dialog B -> Input action A. 
    - In an action within a trigger in Dialog B, `turn.currentDialogStack` will hold ['dialog B', 'dialog A'] 
    - In an interruption intent handler within Dialog B while input action A is still on the stack will result in ['input action A', 'dialog B', 'dialog A']
    - In an interruption intent handler within a parent dialog A while input action A is still on the stack will result in ['input action A', 'dialog B', 'dialog A']. **Note:** this requires special handling of the stack in case of consultation. So the proposal actually calls for different semantics in the normal execution path .vs. in the consultation flow.

**Comment by eduardmartos** [comment]
@vishwacsena, this sounds good. I think this proposal is perfect for now and would be a very useful option for composer programming.
Nice, thank you

**Comment by Stevenic** [comment]
Postponing to R9

**Comment by eduardmartos** [comment]
Hi Stevenic. One question related to this... This postposing change would be implemented as part of BotFramework v4 Base Library (I mean, it would work on Bot “normal” .Net Core projects and Bot Composer projects or only at BotFramework Composer?
We need a flag on Activity Object to know if the Activity was created as a part of a Dialog or Not and I think this evolutive its a little bit related.

**Comment by vishwacsena** [comment]
@Stevenic last we spoke, we would just do this through a prebuilt function rather than a memory scope. Can you share bit more info so we can get this wrapped up in R9?

**Comment by vishwacsena** [comment]
@stevenic to implement JS version and would reach out to @tomlm for C# help.

**Comment by cleemullins** [comment]
@vishwacsena, this is a P0 bug from December. How best to push this forward?

**Comment by vishwacsena** [comment]
@Stevenic was tp draft up an implementation for this. @Stevenic any updates?

**Comment by tomlm** [comment]
This has existed for forever. 
What is wrong with 
* **dialogclass** => current AdaptiveDialog properties 
* **class** => current ActiveDialog (typically action)

**dialogclass.id** is the id of the current AdaptiveDialog
**class.id** is the id of the current action

**Comment by vishwacsena** [comment]
@tomlm that does not work. We discussed this well, in December..
 The reason those do not work is because this DCR is looking for a solution to [these scenarios][1]

For [scenario #2.a][1]. if I use class.xxx inside the OnIntent trigger on consultation, would that not match the `xxx` properties for the active action? What I need is the `id` of the action that initiated consultation. 
For [scenario #2.b][1], using `dialogClass` does not work since that would be the parent, active adaptive dialog's properties. What I need is my child's properties because this is in consultation flow. 

What @Stevenic suggested was a `isDialogIdInstack(dialogIdToCheck)` or a similar pre-built function that will be injected into expressions function table by adaptive dialog that will provide this information.

[1]:https://github.com/microsoft/botbuilder-dotnet/issues/3210#issuecomment-571352064
