### ISSUE TITLE
Retry Prompt Is Not Working In Composer

### ISSUE THREAD

**Issue by CoHealer** [microsoft/botbuilder-dotnet#3298]
@rajeshyalamarthi commented on [Wed Jan 22 2020](https://github.com/microsoft/botbuilder-dotnet/issues/3291)

Hi, I am working on composer. I just created one dialog flow in which user needs to upload an file attachment as input. So that In Dialog I am Asking user to upload an attachment by selecting **Ask a Question of Type File or Attachment**.
Till here it is fine. If user uploading an attachment it is working fine. But Instead of uploading file if user types a text then it needs to ask user again by displaying the message in retry prompt or Unrecognized prompt.
But, here composer is not displaying retry prompt or unrecognized prompt. It is displaying the normal prompt which it ask user for the first time in order to upload attachment.
Please Look into this Issue.

**Comment by christopheranderson** [comment]
While this issue was found via Composer, Vishwac believes this is a bug in the SDK itself and should be investigated first from the SDK side.

**Comment by vishwacsena** [comment]
The issue here seems to be that the `RecognizeInput` call in `InputDialog` will always look at attachments which will be `null` when user sends in a message. Although the user's expectation is that the AttachmentInput will issue its `UnrecognizedPrompt`, we will continue to render the `Prompt`. 

https://github.com/microsoft/botbuilder-dotnet/blob/765ed6c96b5287c079cb19c20f653fca0e9cf3ea/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/InputDialog.cs#L418

@tomlm @Stevenic thoughts?
