### ISSUE TITLE
How To Deserialize DialogManager Obejct of Assembly Microsoft.Bot.Builder.Dialogs.Adaptive

### ISSUE THREAD

**Issue by rajeshyalamarthi** [microsoft/botbuilder-dotnet#3301]
Hi, here i have one scenario. I m working on composer. In startup.cs I am using services.AddTransient<> inorder to load the constructor which loads the dilaog manager by reading the root dialog file. But here I just want to load the Dialog Manager When I want. So Iam Trying to store this dialog manager object in RedisCache by serializing it. But When I am Trying to Deserialize it it is throwing error like (**Could not create an instance of type Microsoft.Bot.Builder.Dialogs.Dialog. Type is an interface or abstract class and cannot be instantiated. Path 'RootDialog.id', line 1, position 20.**). Please look into this.

**Comment by v-kydela** [comment]
@rajeshyalamarthi - Can you provide relevant code samples and screenshots so that we can better understand what you're trying to do and why?

**Comment by rajeshyalamarthi** [comment]
Yeah @v-kydela . Exactly what i am trying to do is, basically in Composer Solution the way it is loading the constructor is in below way
![Capture11](https://user-images.githubusercontent.com/31951690/73342939-9b413380-42a5-11ea-8d8a-02278c215e91.PNG)
=>So, as it is under single ton it is initiating only once at start.
But here what i am trying to do is, I am including the adaptive dialogs generated by composer into my solution. So for that I have Installed all the required packages in my echo bot and integration is done. And it is working.
=>But here my issue is i am using The following way in order to load the constructor
![Capture22](https://user-images.githubusercontent.com/31951690/73343421-a34da300-42a6-11ea-9a29-a08cdcd1148a.PNG)
So, here as it is Transient, It is initiating every time and loading the below constructor
![Capture33](https://user-images.githubusercontent.com/31951690/73343634-f32c6a00-42a6-11ea-96b9-b953f95c101e.PNG)
Because of this,**LoadRootDialogAsync();** method is loading every time and my dialog manager is loading my root dialog file every time.
So for some scenarios in my composer adaptive dialog, I can not able to maintain the context of my dialog manager because it is loading every time.
So here what i am trying to do is, Instead of loading every time i want to load the **LoadRootDialogAsync();** when ever i required and Trying to Store my Dialog Manager in RedisCache.
=> So when it is in context instead of loading the dialog manager again i just want to use my
 dialog manager which i m storing in cache.
=> So for that i m serializing my Dialog Manager Object and storing that in rediscache. When ever it required i m trying to fetch it and Trying to deserialize in order to use that.
=> But whenever im trying to deserialize it is throwing the error
**Could not create an instance of type Microsoft.Bot.Builder.Dialogs.Dialog. Type is an interface or abstract class and cannot be instantiated.** As i mentioned in my first comment.
In the following ways i tried to serialize and Deserialize the DialogManager Object..
![Capture444](https://user-images.githubusercontent.com/31951690/73344757-ec065b80-42a8-11ea-9ea6-2ebaf5f89c98.PNG)
![Capture555](https://user-images.githubusercontent.com/31951690/73344764-f0327900-42a8-11ea-80b0-356cf06732a6.PNG)
..So Please Look into this

**Comment by v-kydela** [comment]
@rajeshyalamarthi - When I said to provide code samples _and_ screenshots, I didn't mean for you to provide code samples _as_ screenshots. You should never post screenshots of your code because that prevents people from copying it. You should post code using the appropriate formatting (GitHub Markdown in this case).

There are still some things that aren't making sense. You're registering the `IBot` type in your dependency injection twice, `ComposerBot` as a singleton and `BotProject` as a transient. Then you go on to describe `ComposerBot` as though it's the transient and not the singleton. Can you explain what's going on there?

In general, it would be nice to know more about what you're trying to do and why. Are you building the bot in Composer or writing the bot in C#? What do you need the dialog manager for? I suspect your solution will need to involve some reworking since you're not using adaptive dialogs the way they're supposed to be used.

**Comment by rajeshyalamarthi** [comment]
sure @v-kydela . First thing I am not registering the IBot type in my dependency injection twice. The first screenshot is from the project solution that generated by the composer. And the second screen shot is from my echo bot v4 solution where i am trying to integrate the adaptive dialogs working flow .
`        public BotProject(ConversationState conversationState, UserState userState, ResourceExplorer resourceExplorer, ISourceMap sourceMap, IBotTelemetryClient telemetryClient, IConfiguration configuration)
        {
            this.conversationState = conversationState;
            this.userState = userState;
            this.dialogState = conversationState.CreateProperty<DialogState>("DialogState");
            this.sourceMap = sourceMap;
            this.resourceExplorer = resourceExplorer;
            this.telemetryClient = telemetryClient;
            this.Configuration = configuration;
            //this.LoadRootDialogAsync();
        }`
=> This is the code sample of my echo bot solution. As i regiestering my IBot service using Transient. It loads the above constructor for each request.
=> Beacuse of that **LoadRootDialogAsync();** method executes for every turn.
`        private void LoadRootDialogAsync()
        {
            var rootFile = this.resourceExplorer.GetResource("Main.dialog");
            this.rootDialog = DeclarativeTypeLoader.Load<AdaptiveDialog>(rootFile, this.resourceExplorer, this.sourceMap);
            this.dialogManager = new DialogManager(this.rootDialog);
        }`.
=> if the above method executes each time, then the **this.dialogManager** object could not maintain context of the dialog.
=>Because of that some dialogs(composer generated adaptive dialogs) which iam trying to use in echo bot solution is not working as expected.
=> For that if you notice I commented **//this.LoadRootDialogAsync();** in above constructor. I dont want to load my dialog manager object in every turn.
=> So i am loading it when ever i need to use composer dialogs instead of my conversation handlers like qna maker and my Kb responses
=> So, first time when i trying to use composer dialogs i will call the above method **this.LoadRootDialogAsync();**. So i have my dialogmanager object loaded. And then it execute the below code inorder to send response from composer dialogs
`            this.telemetryClient.TrackTrace("Activity:" + turnContext.Activity.Text, Severity.Information, null);
            await this.dialogManager.OnTurnAsync(turnContext, cancellationToken: cancellationToken);
            await this.conversationState.SaveChangesAsync(turnContext, false, cancellationToken);
            await this.userState.SaveChangesAsync(turnContext, false, cancellationToken);`
=>So, in next turn because i m registering my IBot service as Transient my dialogmanager object will become null. So here i need to call **this.LoadRootDialogAsync();** in order to load dialog manager.
=> If i load it again it wont maintain the context. So here what i am trying to do is, instead of loading it again until it completes the dialog flow, i just want to store the dialog manager object in redis cache or some other thing.
=> So, finally i can able to serialize the dialog manager object and store it in redis cache. But when i am trying to get that by deserializing it , it is throwing the error i mentioned in above comment.
i m trying in this way
`                                                    string dm = JsonConvert.SerializeObject(this.dialogManager);
                                                    DialogManager dialogManager = JsonConvert.DeserializeObject<DialogManager>(dm);`

=> The error it is throwing is **Could not create an instance of type Microsoft.Bot.Builder.Dialogs.Dialog. Type is an interface or abstract class and cannot be instantiated.**

**Comment by rajeshyalamarthi** [comment]
thanks @v-kydela. I saw that you replied for my question in stack overflow. As you mentioned that to serialize correctly. I Already tried serializing it with **type-name handling** information. And not only that i also tried with **NullValueHandling**,**Formatting** and in some other ways. when I am trying with this while deserializing i got some other error like **Unable to find a constructor to use for type Microsoft.Bot.Builder.AI.Luis.LuisRecognizer. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'RootDialog.Recognizer.recognizers.en-us.LogPersonalInformation', line 6554, position 35.**
=> And also you mentioned i can't depend on JSON to contain all the information a dialog needs to work. So i mentioned the flow how i want to do. So is there any other way?.

**Comment by v-kydela** [comment]
@rajeshyalamarthi - Is there any other way to do what? You still haven't asked a specific question that I can answer. You've just said that what you're doing doesn't work, but you haven't said why you're trying to do it. What are you hoping to do with your `DialogManager` instance?

It looks kind of like you're trying to use adaptive dialogs outside of Composer in an ordinary C# bot solution, and you're using the builtin Composer bot as a sort of guide for how to do that. Is that the case? If so, you should not be using the Composer bot as a sample for building your own adaptive dialogs. There are samples you can use [right here](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-dialog).

From what I can see, the samples add the bot class to DI as a singleton, so why are you adding it as a transient? If you really want to use a transient, you can still add the `DialogManager` itself as a singleton given that your root dialog is also in DI and doesn't need to be reloaded like it does in the Composer bot.

When you say something like "I've already tried that," that means you haven't been providing as much relevant information as you could have. In order to get the help you need, you need to be able to ask good questions. Part of asking good questions involves saying what you've already tried so far, because that shows respect for the time of the people you're expecting to help you so they don't duplicate your effort.

Another part of asking a good question is to explain what you're actually trying to do rather than just the way you think you're supposed to do it, i.e. instead of talking about how you can't deserialize JSON you should be talking about what you're trying to achieve by deserializing that JSON. This is because you might be making faulty assumptions and going down the wrong path, and people can't help you find the right path unless they know where you're trying to get to. I can tell you that you can't do what you're doing all day, but I'll never be able to tell you what to do instead unless I know what your ultimate goal is.

Also, you should always provide any relevant links, such as links to the tutorials you've been following or [other posts you've made](https://stackoverflow.com/questions/59983508/unable-to-deserialize-the-object-of-type-dialogmanagermicrosoft-bot-builder-dia). Please remember to accept my answer on Stack Overflow because it addresses your post according to the information you gave.

**Comment by v-kydela** [comment]
@rajeshyalamarthi - Are you still working on this?

**Comment by rajeshyalamarthi** [comment]
Yes @v-kydela. I m still working on this. I m looking in Bot builder-Declarative samples which you mentioned above

**Comment by v-kydela** [comment]
@rajeshyalamarthi - Do you want to clarify this issue with a specific question or do you want to close this issue and ask a new question if you still need help?

**Comment by rajeshyalamarthi** [comment]
@v-kydela - I am still working on this. Please close this issue. I will come with new one.
