### ISSUE TITLE
MS Bot - Teams Channel - Typing indicator not showing when bot added to a teams channel

### ISSUE THREAD

**Issue by roshanparmar11** [microsoft/botbuilder-dotnet#3512]
## Version
4.7.2

## Describe the bug
When we create a bot with ms bot framework c# and add the bot to ms teams channel, at this time when bot is added as a seprate app, than it is showing the typing indicator. But when the bot is added in the channel (example general channel in side any team). and when we use the bot by @mention, At this time, bot is not showing the typing indicator.

## To Reproduce
1. Add the bot to any of your team's channe;. i.e. General channel
2. use the bot by doing @ mention. and start the conversation with the bot
3. Typing indicator will not show ip.

## Expected behavior
It should show typing indicator

## Additional context

[bug]

**Comment by stevkan** [comment]
@roshanparmar11, thank you for bringing this up. Please be patient while I research the issue. In the meantime, can you tell me if this was working previously (and, if so, which version of BotBuilder you were using) or is this something you came across thru a new implementation?

**Comment by roshanparmar11** [comment]
No. I have not tested this feature before.

**Comment by stevkan** [comment]
I have tested this and noted that when the typing activity is sent, it is respected in a 1:1 and group conversation, but not (as you noted) in a Teams channel threaded conversation. However, any associated delay in the typing indicator _is_ respected. This indicates the bug is in Teams and not the BotFramework.

I have created an issue [here]() for the Teams group to track and triage. Please consider adding to it as more names will give it greater weight for consideration.

Closing this issue as resolved.
