### ISSUE TITLE
Expressions  ReturnType and validations should include Array

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#3615]
Today in expressions you can only check for or return primitive values and "object".  As a number of expressions explicitly require or return arrays we should add array as ReturnType.  This will help on error checking and make the information more explicit.
[enhancement]

**Comment by tomlm** [comment]
can you provide more details?  In C# we support ExpressionProperty<T> and T can be an array.

**Comment by cleemullins** [comment]
@chrimc62 Can you provide an answer to @tomlm before we take the PR that @Danieladu provided?

**Comment by boydc2014** [comment]
To @tomlm @cleemullins 

@chrimc62  is not talking about we don't support return an array. He is referring to the static checking process in prebuilt functions, in which we require each function have a return type declaration, which can be ReturnType.Number | Object | Boolean, but we didn't defined ReturnType.Arrary before. This DCR to add array into that. 

it's like previous
`function skip(x: any, y:number): any`
now
`function skip(x: array, y: number): array`

so that things like `skip(1, 2)` will result in an error in parsing and validation phase, not have to wait until runtime phase
