### ISSUE TITLE
DCR: .dialog resource binding should fallback to non-hardcoded extensions.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#3641]
We should add fallback for string reference binding "foo.xxx" => looks for "foo.xxx.dialog" and if not found attempts to bind to "foo.xxx",
The point of these changes is that it allows new extensions to be added to the resource explorer, and if there are object bindings for those extensions they will be used. If a file is valid json but NOT a dialog file (Such as .schema files) then they can be used directly without having to have .dialog extension.

For example, this captures the 2 scenarios:

1. **"recognizer":"foo.lu"** => will bind to attempt to bind to "foo.lu.dialog" 
2. **"schema":"foo.schema"** => will attempt to bind to foo.schema.dialog, and then fall back to foo.schema, which is a valid JSON object to bind and it will load it. (Thus removing the need to have schema file be foo.schema.dialog.

PR is #3640

**Comment by boydc2014** [comment]
i didn't fully get this short-term fix, i mean i understand what it does, but seems not align with long term goal.  By fall-backing to resource.id, we are implying that we are encouraging using different file extension to distinguish types.  How about we just fallback from resource.id.dialog to resourc.id.json, and start encouraging people to serialize stuff other than dialog into json, and use "name" instead of "extension" to distinguish, like "recongizera.json"? 

I means we are easily go from recongzier_a.json to a.recoginzer, but probably not the vice versa

**Comment by tomlm** [comment]
This is about allowing you to refer to a json file (regardless of extension) without having to add .dialog on to the reference.
