### ISSUE TITLE
Need base64() to support byte[]

### ISSUE THREAD

**Issue by ssss141414** [microsoft/botbuilder-dotnet#3674]
**Is your feature request related to a problem? Please describe.**
When I make a httpget to get a image, the response.content is like this:
![image](https://user-images.githubusercontent.com/18118994/78330956-a4a58f80-75b7-11ea-9549-1d38b207383a.png)
I think they are byte arrays. (Maybe they aren't, but please support converting this type)

Use base64() won't get correct base64 string.
![image](https://user-images.githubusercontent.com/18118994/78331164-0f56cb00-75b8-11ea-9fd7-e7f90c50fe69.png)

**Comment by Danieladu** [comment]
Expression may should output byte array for the `binary format output function` instead of the binary string, such as `Base64ToBinary`, `DataUriToBinary`, `Binary` .etc.
for example, expression `binary('hello')` would output `"0110100001100101011011000110110001101111"`
But the real binary is a byte array.

And Expression should support byte array input for the corresponding conversion. e.g. `Base64`, `DataUri` .etc.

**Comment by vishwacsena** [comment]
We need to tend to this ASAP to get the skills/ composer effort unblocked.
