### ISSUE TITLE
replacedialogasync vs BeginDialogAsyc

### ISSUE THREAD

**Issue by gtejeda** [microsoft/botbuilder-dotnet#3685]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

Greetings.
I did not find a clear answer to this question, so I post it here in case any of you have the time to answer

thanks tons,
Geo

**Comment by v-kydela** [comment]
Hello @gtejeda 

It looks like you're trying to ask a question. I'm happy to help, but we prefer to keep how-to questions on Stack Overflow. Please read [this help document](https://stackoverflow.com/help/how-to-ask) to know how to ask a good question to make sure you can get a good answer.

In the meantime, I can tell you that the difference between ReplaceDialogAsync and BeginDialogAsync is that ReplaceDialogAsync ends the current dialog on the stack so that it will not be resumed after the new dialog, while BeginDialogAsync adds a new dialog on top of the current dialog on the stack so that it does get resumed afterward. You can read more about dialogs here: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-dialog

I'm closing this issue now.
