### ISSUE TITLE
[DCR][LG]Improve the robustness of templates CRUD

### ISSUE THREAD

**Issue by Danieladu** [microsoft/botbuilder-dotnet#3692]
Nowadays, customers of LG library (e.g. Composer) use Templates CRUD method to modify the original templates. 

The process of each modification is like: modify the original content according the parse tree, and then override itself by parsing the  new LG content. So, there exists such situation:
Something is wrong with the content, maybe with some syntax errors during the parsing, this may cause the template itself is not very accurate. But the customer also want to use the CRUD method to revise the incorrect templates. So, maybe LG should provide a robust way to parse out all template content correctly. 

Here I have a draft solution that LG uses string operator (use # as the template mark) to parse out all the template content and then use Antlr to parse them into the parseTree.

Welcome discussion.

[enhancement]

**Comment by vishwacsena** [comment]
@Danieladu do we need this in R9?

**Comment by Danieladu** [comment]
> @Danieladu do we need this in R9?

Yes, We are about to work on this issue.

**Comment by boydc2014** [comment]
Just FYI, we discussed this offline, the solution i proposed is a two-phase parsing. 

phase 1 will be parsing the structure, aiming for identify the boundary of template, this phase will be way robust than current, by not knowing the details of various template body format and only focusing on dealing with "#". 
phase 2 will be parsing the template body, it could be also simplified, because some work have been done in phase 1 knowing the boundary, we could simplified the lexers and rules and improve readability.
