### ISSUE TITLE
Expression createObject syntax not working as expected

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botbuilder-dotnet#3761]
The curly bracket syntax implementation in master only support   {user: "John"}, we need to support {user: ${somepath)} to also be supported. 

More cases
```
assume memory = { user: {name: John, age: 12}}

{name: ${user.name}}.name == "John"
{"name": ${user.name}.name == "John" 
{age: ${user.age}}.age == 12
json({age: ${user.age}}) ==  { "age": 12 }  

// note, this is not correct syntax to create object, because in string interpolation, we are actually only interpolate ${user.age} here
json(`{age: ${user.age}}`)  == exception of json conversation 

```

**Comment by cosmicshuai** [comment]
I thinsk it is due to the limitation of setProperty function. 
Plan to add a new function, createObject to handle this '{}' to do the conversion.
For using a variable in createObject, we could use its variable name directly instead of using an expression like ${user.name}.
Therefore,  {name: user.name}.name will be evaluated to "John".

**Comment by boydc2014** [comment]
Close this, due to my misunderstanding.
