### ISSUE TITLE
Missing Files in project folder for Deployment

### ISSUE THREAD

**Issue by Ada-develop** [microsoft/botbuilder-dotnet#3795]
## Version
What package version of the SDK are you using.

## Describe the bug
Hi, I have created Bot that perefectly works in BotFramework Emulator, and I ready to deploy it to Azure , but when I tried to deploy I have recognized that I have missing files in my project as web.config etc. that needed to deployment I created Bot by tamplate EmptyBot in VisualStudio 2019, I tried another method for deployment by Git in Azure > App Service > Deployment Center, Bot reacts only on MembersAdded with Greeting message and than send error messages.  Please help. I attached some photos.

## Screenshots
Should look like, files : 
![61910864-a4aea500-aeea-11e9-88fe-1d3d5b4f230e](https://user-images.githubusercontent.com/58919290/80133264-a6a2b300-85a5-11ea-8e5e-5d6e45001a2f.png)

I my project it looks like : 

![BotDepExp](https://user-images.githubusercontent.com/58919290/80133329-b91cec80-85a5-11ea-969e-1fc6b6205ac1.PNG)

Azure : 

![azure](https://user-images.githubusercontent.com/58919290/80133345-bf12cd80-85a5-11ea-90e5-4c73260d472a.PNG)

## Additional context

[bug]

**Comment by Zerryth** [comment]
Hey @Ada-develop! Did you try following the[ deployment instructions](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp) that are linked in EmptyBot's README?

I just created a new EmptyBot from scratch, followed those deployment instructions, and prospered!

<details>
    <summary> Click to view command-line commands that I ran </summary>

`az ad app create --display-name "AshEmptyBot" --password "..." --available-to-other-tenants`

`az deployment create --template-file "DeploymentTemplates/template-with-new-rg.json" --location centralus --parameters appId="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" appSecret="..." botId="AshEmptyBot" botSku=S1 newAppServicePlanName="AshEmptyBot" newWebAppName="AshEmptyBot" groupName="AshEmptyBot" groupLocation="centralus" newAppServicePlanLocation="centralus" --name "AshEmptyBot"`

`az bot prepare-deploy --lang Csharp --code-dir "." --proj-file-path "./EmptyBot1.csproj"`

`az webapp deployment source config-zip --resource-group "AshEmptyBot" --name "AshEmptyBot" --src "./code.zip"`
</details>

So just follow the zip deployment instructions, taking note to include the values that are pertinent to your bot, and you should be able to deploy.

![image](https://user-images.githubusercontent.com/35248895/80238357-25820500-8613-11ea-9567-cbc3dc10e21b.png)

**Comment by Ada-develop** [comment]
> Hey @Ada-develop! Did you try following the[ deployment instructions](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp) that are linked in EmptyBot's README?
> 
> I just created a new EmptyBot from scratch, followed those deployment instructions, and prospered!
> 
>  Click to view command-line commands that I ran
> So just follow the zip deployment instructions, taking note to include the values that are pertinent to your bot, and you should be able to deploy.
> 
> _EmptyBot Deployed to Azure_
> ![image](https://user-images.githubusercontent.com/35248895/80238357-25820500-8613-11ea-9567-cbc3dc10e21b.png)

Hello Zerryth! Thank you for your response, I tried do by your instructions, and struggled on the last step with zip,curl step , dont really understand what values should I write in Curl-step , like username it mean email? sitename it means my webapplicaiton name? 
![deploy](https://user-images.githubusercontent.com/58919290/80263948-0cbd3200-869b-11ea-8e4a-55f148e8771d.PNG)

**Comment by Zerryth** [comment]
@Ada-develop where are you getting these curl instructions? 

I didn't use any curl myself--they're not in the [deployment link instructions](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp) I posted to you, nor do the that the readme link to mention a "username"

**Comment by Ada-develop** [comment]
> @Ada-develop where are you getting these curl instructions?
> 
> I didn't use any curl myself--they're not in the [deployment link instructions](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp) I posted to you, nor does the readme/link in readme mention a "username"
> 
> The deployment instructions use az cli

Hello again! I have successfully deployed Bot to Azure, but now I faced another problem, when I set Microsoft AppID and Password to appsetting.json file and deployed to Azure , my Bot faced a problem HTTP Unauthorized. I attach pics, any suggestions how can I fix this problem?


Thank you Zerryth for your answers.

![git1](https://user-images.githubusercontent.com/58919290/80369200-8c632080-8896-11ea-93f7-7fdd0dc2afe0.PNG)


![git2](https://user-images.githubusercontent.com/58919290/80369207-91c06b00-8896-11ea-8d69-7e9352ba48a4.PNG)


![git2](https://user-images.githubusercontent.com/58919290/80369213-9553f200-8896-11ea-9449-f9484e37f778.PNG)

**Comment by Zerryth** [comment]
So...last you mentioned, you were just trying to deploy an EmptyBot to Azure, filing a bug report. Then we find that you can indeed deploy EmptyBot just fine, following the instructions provided in the README.

Now you come back saying that the deployed bot is unauthorized...and I'm only *guessing* from your screen shot, since you don't provide any code or mention what samples you're using, that you're using 13.corebot + QnA Maker.

I actually ran through the steps of deploying a corebot with qna maker added to it just in case, and can successfully talk to the deployed bot in Test in Web Chat.

![image](https://user-images.githubusercontent.com/35248895/80446800-a9b2e180-88cc-11ea-8e3e-5f95347ac7f1.png)

___
Going to close this issue out, as our GitHub repositories are for filing bugs with our framework that our team must fix or asking for feature enhancements of the product. Please post your how-to question on [Stack Overflow](https://stackoverflow.com/questions/tagged/botframework), where you can leverage the help of our Support Engineers and the whole community at large. 

Be sure to provide more details as well (what you've done, your bot code or sample you're using, etc.) so the community can be of better help.

For now, with the given information I can only leave off with this:
* It is possible to deploy corebot with qna maker added
* Double check that your values in your appsettings are correct (for example, does your bot need `westus` as the `LuisAPIHostName`? Or does it actually need `westus.api.cognitive.microsoft.com`? Do you need to pass in `MicrosoftAppId` and `MicrosoftAppPassword` into your bot or can they remain empty?, etc.)
