### ISSUE TITLE
[Expressions] Add prebuilt functions for adaptive cards

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-dotnet#3873]
Discovered this via partner validation (adaptive cards team). We need to add two prebuilt functions to enable one of the adaptive card teams core samples (stock card)

1. formatNumber(value, precision) -> formatNumber(20, 2) = 20.00; formatNumber(0.53, 1) = 0.5. With this you could do formatNumber(value * 100, precision) to achieve your scenario.

2. formatEpoch(value, format?) -> behaves similar to `formatDateTime()` except first param is Epoc time stamp 

@boydc2014 

@emgrol for docs impact.

**Comment by Danieladu** [comment]
- `formatNumber(1.55, 1)` would be `1.5` or `1.6` ?
- Currently, `formatDateTime()` accept number or string as the first parameter, if the first parameter is number, treat it as unix timestamp, otherwise treat it as a normal date string.
Can I think that, after the change, `formatDateTime()` would also accept number or string type as the first parameter, if the first parameter is number, treat it as unix timestamp. If it is a string type, and can be parsed into ticks, treat it as ticks input, else treat it as normal date time string. Is that right?

**Comment by boydc2014** [comment]
@vishwacsena  the formatNumber is straighforward and i put @cosmicshuai on this.

To suppoprt "ticks" the thing is it's not distinguishable from epoch, i mean, if formatDateTime see an int, how does it know to treat as millionSecondsFromepoch or window ticks. 

We can either 
1. extend the interface as formateDateTime(int, epoch=true), 
2. just create two new functions like 
* formateEpoch
* formateTicks
or whatever names we want. 

I will recommend 2 for simplicity.

**Comment by cosmicshuai** [comment]
@vishwacsena 
for formatNumber, I got a question. The returned value should be a string or a number? Since I met some difficulty with returning a number, the trailing zeros will disapper. Therefore, my current solution is returning a string to do the format.

**Comment by vishwacsena** [comment]
@boydc2014 I like `formatEpoch` and `formatTicks` for clarity. Let's go with that.

**Comment by sgellock** [comment]
making mods to priority label.  I've changed this to P0.  But to be clear, we have 1 shot at this in R9.  If we miss something or AC wants additional functionality beyond what this and JS PR provides, I won't hold R9 for it.  We'll have to give it to them in R10.
