### ISSUE TITLE
Unknown intent trigger is not called when an intent trigger is rejected by a condition

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#3930]
## Describe the bug

Although technically it makes sense I would think functionally this seems like a bug. When you have an intent with a condition to reject false triggers, like: turn.recognized.score > 0.7
It does not trigger the Unknown intent trigger. I would expect this to happen.

## Version

latest today

**Comment by benbrown** [comment]
@cxbuilders we are unable to reproduce this behavior.

Do you happen to have a condition set on the unknown intent trigger that might be causing it to fail to trigger?

**Comment by cxbuilders** [comment]
@benbrown I created a fresh bot and I could not replicate this now as well. The bot I am working on also does not show the Trigger phrases textbox on the Intent triggers, so I guess it has been corrupted between the many different version changes of Composer. I will need to see if I can create a fresh bot and copy the dialogs etc over.

**Comment by cxbuilders** [comment]
@benbrown I ran into this issue again and figured what the problem is. 
The rootdialog contain the intent triggers, including the Unknown Intent trigger. After the greeting trigger I move the user to the MainMenu dialog form which they can move to other dialogs and come back to the MainMenu dialog.

In this MainMenu dialog the intents from the root dialog are nicely triggered and an interruption takes place, except for the Unknown intent trigger. This basically leaves the user hanging with no response.

Below the setup of this test bot. No Conditions here whatsoever.

![image](https://user-images.githubusercontent.com/49873947/84373340-ba00f080-abdc-11ea-94fa-be2bf9a4faf6.png)
![image](https://user-images.githubusercontent.com/49873947/84373375-c422ef00-abdc-11ea-8c11-65981b34231c.png)

![image](https://user-images.githubusercontent.com/49873947/84373429-d9981900-abdc-11ea-8fd9-fa29f26ae953.png)


![image](https://user-images.githubusercontent.com/49873947/84373400-cf761a80-abdc-11ea-8554-65b932961edf.png)

![image](https://user-images.githubusercontent.com/49873947/84373466-e6b50800-abdc-11ea-9b0e-c03a44c0e8ce.png)

![image](https://user-images.githubusercontent.com/49873947/84373478-ec125280-abdc-11ea-83da-ac66b4e62c95.png)

**Comment by a-b-r-o-w-n** [comment]
@cxbuilders are you able to share the *.dialog files for this project? We can take a look at this.

**Comment by cxbuilders** [comment]
@a-b-r-o-w-n Just send the export of the bot to your email.

**Comment by vishwacsena** [comment]
@cxbuilders - are you using LUIS or regex recognizer? Also to clarify, is this what you are expecting? 

```
bot: weclome (rootdialog)
bot: here is the main menu - option 1 | option 2
user: blah 
bot: nothing recognized (rootdialog)
```

**Comment by cxbuilders** [comment]
@vishwacsena I use Luis. And yes, that is what I expect. If intents are triggered from the root dialog when the user is in a child dialog, so should the no intent recognized trigger from the root dialog. 

When the active child dialog also has a no intent recognized trigger that should take precedence.

**Comment by vishwacsena** [comment]
@cxbuilders a workaround for you is to add a 'None' intent handler in your parent. See attached.

[EmptyBot-0.zip](https://github.com/microsoft/botbuilder-dotnet/files/4794257/EmptyBot-0.zip)

**Comment by vishwacsena** [comment]
@cxbuilders I investigated this a bit more and here's what is going on. The default behavior in adaptive dialog is to not fire the `unknown` intent trigger on consultation. This is essential because the child at this point has not made a call if it wants to take the input user utterance or not. So in case where you are not using a LUIS recognizer for a child adaptive dialog, you can simply use an `EmitEvent` in your default path to let the parent know that the child does not want to (or know how to) process this incoming request. Here is an example bot that shows how to do this where the child dialog does not have its own recognizer. 

[NoRecognizerInChild.zip](https://github.com/microsoft/botbuilder-dotnet/files/4794622/NoRecognizerInChild.zip)

![image](https://user-images.githubusercontent.com/20918136/84939655-81a55a80-b093-11ea-94a0-d1a4ea9d56f6.png)

You can also use the same technique in your bot with a child that has LUIS recognizer configured. See below. 

![image](https://user-images.githubusercontent.com/20918136/84940299-7dc60800-b094-11ea-8649-6b4747292471.png)

[childWithLUIS.zip](https://github.com/microsoft/botbuilder-dotnet/files/4794649/childWithLUIS.zip)
