### ISSUE TITLE
Slack adapter doesn't render choice prompts

### ISSUE THREAD

**Issue by haacked** [microsoft/botbuilder-dotnet#3974]
## Version
4.80 (with `Microsoft.Bot.Builder.Dialogs` v`4.9.1`

## Describe the bug

I wrote a bot that does a sequential conversation flow. When I connect the bot to slack, it renders the choices as text even though Slack supports choice buttons.

The code for my bot is an exact copy of the code from [Implement Sequential Conversation Flow](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp).

When I run 

## To Reproduce
1. Go to https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp and implement a bot according to the instructions. (In my case, I just copied the code from the samples directory).
2. Use Azure Bots Channel Registration to connect the bot to Slack [per these instructions in the "Configure Slack in Azure" tab](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs).
3. Make sure to enable interactivity.
<img width="725" alt="Screen Shot 2020-05-22 at 10 08 48 AM" src="https://user-images.githubusercontent.com/19977/82692280-4f2f4b80-9c14-11ea-8f80-9197d1e0edb3.png">
4. Install the bot in the workspace.
5. Say hi to the bot.

Here's what I get.

![Screen Shot 2020-05-22 at 9 58 11 AM](https://user-images.githubusercontent.com/19977/82692339-6c641a00-9c14-11ea-9d90-4ba2aa698c48.png)

## Expected behavior
I expected to see buttons for each of the choices.

[bug]

**Comment by v-kydela** [comment]
@haacked - Thank you for the feedback.

Choice prompts will try to render choices as hero cards or suggested actions or text depending on what the channel supports. However, that only applies to Bot Framework channel connector services because the Slack API and the Slack adapter don't know anything about Bot Framework cards or suggested actions. When your choice prompt evaluates the capabilities of the channel, it's assuming you're using the Azure Bot Service.

The ABS Slack channel connector should be your first choice. The adapters should be considered previews and should only be used if you have a good reason to use them and you know what you're doing. If you use the Slack adapter, you won't be able to use Bot Framework cards and that includes the cards generated by choice prompts.

**Comment by haacked** [comment]
> When your choice prompt evaluates the capabilities of the channel, it's assuming you're using the Azure Bot Service

@v-kydela I am using Azure Bot Service for my bot. I was a bit confused about how the `SlackAdapter` plays into everything. I thought the `SlackAdapter` was used by ABS to translate choices into Slack choices.

So to recap, I am using ABS to connect my bot to Slack. I followed the tutorial exactly. Slack renders the choices as text. I want to confirm, that's not the expected behavior, correct?

**Comment by v-kydela** [comment]
@haacked - Your title says you're using the Slack adapter. I'm sorry for the confusion, and I will try to make this as clear as possible. If you are using ABS, you should not be using the Slack adapter. If you are using the Slack adapter, you should not be using ABS. ABS and the Slack adapter are incompatible.

If you are unsure of whether you are using the Slack adapter or a Bot Framework adapter, you should be able to see what kind of adapter you have configured in Startup.cs and your controller class. In order to avoid using the Slack adapter, you should completely ignore the instructions in the Slack adapter tab of [this page](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?tabs=adapter).

> I thought the SlackAdapter was used by ABS to translate choices into Slack choices.

That is incorrect. The Slack adapter and ABS are separate and incompatible. You must choose one or the other, and if you have any doubt about which one you want then you should just be using ABS.

> I followed the tutorial exactly. Slack renders the choices as text. I want to confirm, that's not the expected behavior, correct?

There are many tutorials out there, but I certainly don't think you could be following any tutorial exactly if you're trying to use both the Slack adapter and ABS.

**Comment by haacked** [comment]
> Your title says you're using the Slack adapter. I'm sorry for the confusion, and I will try to make this as clear as possible. If you are using ABS, you should not be using the Slack adapter. If you are using the Slack adapter, you should not be using ABS. ABS and the Slack adapter are incompatible.

The title of my issue is incorrect and reflects my earlier confusion. I updated the title. I can confirm __I am not using the Slack Adapter. I am using ABS.__

> There are many tutorials out there

I'm referring to the one I linked to in the [write-up for this issue](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp).

So there's two things left for me to understand.

1. Is the expected behavior I mentioned correct? Should I expect that I get choice buttons in Slack if I followed this tutorial correctly and am using ABS.
2. If so, the issue is not in the Bot Framework and I should open an issue elsewhere.

Can you confirm?

**Comment by v-kydela** [comment]
@haacked - Sorry for the misunderstanding. You are correct that this is an actual bug in the .NET SDK, but since I raised the bug nearly a year ago it would be better for you to comment on the issue rather than raising a new one: https://github.com/microsoft/botbuilder-dotnet/issues/2291

Your issue should remain closed. The workaround is to use the `HeroCard` list style instead of auto: https://github.com/microsoft/BotFramework-Services/issues/82#issuecomment-513384847

**Comment by haacked** [comment]
> You are correct that this is an actual bug in the .NET SDK, but since I raised the bug nearly a year ago it would be better for you to comment on the issue rather than raising a new one: #2291

Will do! Thanks for pointing me to it. And thanks for the workaround.
