### ISSUE TITLE
OauthScope null when using DL Speech

### ISSUE THREAD

**Issue by pedrocunha87** [microsoft/botbuilder-dotnet#3995]
## Version
v4.9.1

## Describe the bug
This problem was already reported in here:
[(https://github.com/microsoft/botbuilder-dotnet/issues/3844)]

## Additional context
On ProcessActivityAsync, BotFrameworkAdapter, you are setting the OAuthScope on TurnState.
But on ProcessStreamingActivityAsync, BotFrameworkHttpAdaptarBase, used by DirectLineSpeech that is missing, i believe.

Can that be the problem?

Thanks
ProcessActitivyAsync
![image](https://user-images.githubusercontent.com/3627634/83137887-d3d10c80-a0e1-11ea-9c11-f37bef4450e0.png)

CosmosDB
![image](https://user-images.githubusercontent.com/3627634/83137689-80f75500-a0e1-11ea-8a3a-f63dcc55d97f.png)

**Comment by tracyboehrer** [comment]
@gabog What is the status of this?

**Comment by gabog** [comment]
Hi @pedrocunha87, DL speech requires websockets that doesn't use the connector client to respond, it uses the WS connection so the OAuthScope is not required to authenticate the response. 

Makes sense?

**Comment by pedrocunha87** [comment]
I'm not having problems connecting to the bot.
The problem happens when handling a response from a Skill.
The SkillHandler, doing the ProcessActivityAsync will get the ConversationReference and there the skillConversationReference.OAuthScope is null.
Then on ContinueConversationAsync, BotFrameworkAdapter, the parameter audience is null.

**Comment by vishwacsena** [comment]
@gabog can you help take a look and comment?

**Comment by srinaath** [comment]
@gabog Could you take a look at this ticket?

**Comment by gabog** [comment]
Hi, the workaround for DL speech is to use clone the incoming activity, set ExpectReplies and then send it to the skill, something like:

```
var activityClone = ObjectPath.Clone(turnContext.Activity);
activityClone.DeliveryMode = DeliveryModes.ExpectReplies;
```

We do have a bug around not setting OAuthScope but this is low priority. DL speech uses affinity because of the WebSockets connection so you need to ensure the skill replies back to the calling server (that is achieved using ExpectReplies).

If you post a snipped on how are you trying to use the skill I can provide additional details.

**Comment by pedrocunha87** [comment]
Ok.
I'll try that approach for now.

Thanks.
