### ISSUE TITLE
Should escape backquote in lg/expressions errors

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-dotnet#4003]
When an expression/lg has an error and the expression includes backquote the corresponding blocks appear as code.  There might be other markdown escaping we should do as well.  This would normally be fine, but does make it harder to understand error messages.  In the below you can see the backquote have different fonts.

![image](https://user-images.githubusercontent.com/17637681/83300941-b49fb100-a1ad-11ea-8b6d-f24c762b2759.png)

[bug]

**Comment by chrimc62** [comment]
@mrivera-ms not sure why this is assigned to me.  The fix is as simple as just changing backquote to simple quote in the error messages from LG.

**Comment by Danieladu** [comment]
One option is to change the onError middleware in Adapter.
Original is:
```
 this.OnTurnError = async (turnContext, exception) =>
{
       await turnContext.SendActivityAsync("Sorry, it looks like something went wrong.");
       await turnContext.SendActivityAsync(exception.Message);
}
```

Make this change:
```
 this.OnTurnError = async (turnContext, exception) =>
 {
       await turnContext.SendActivityAsync("Sorry, it looks like something went wrong.");
        var activity = MessageFactory.Text(exception.Message);
        // Set the error message format to plain to avoid the markdown rendering.
        activity.TextFormat = TextFormatTypes.Plain;
        await turnContext.SendActivityAsync(activity);
}
```

**Comment by boydc2014** [comment]
The 
![image](https://user-images.githubusercontent.com/3829387/98080129-e715ae80-1eaf-11eb-8b26-b22d28c171d8.png)

is caused by previous we are using `__temp__` as the name. in latest release we are not using this notion. And we confirmed are not adding any extra character to the error message after checking the code. 

Also, hongyang gave a solution to fully disable markdown render. So, at this point, i don't think we need take action for this.
