### ISSUE TITLE
Skype Bot doesn't response in group channel

### ISSUE THREAD

**Issue by lunyi** [microsoft/botbuilder-dotnet#4027]
hi all 
as the title 
is it allowed to send messages with PDF or word files?

**Comment by anusharavindrar** [comment]
@lunyi, sending attachments such as PDFs is not supported yet due to [security concerns](https://github.com/microsoft/botframework-sdk/issues/4047#issuecomment-359482543). Skype allows you to send only media attachments such as audio and video. As Skype blocks you from sending PDFs as attachments in any form (links, local file or Base64Strings), you can still send them as links by simply embedding the link in your text.

**Comment by anusharavindrar** [comment]
@lunyi, sending attachments such as PDFs is not supported yet due to security concerns. Skype allows you to send only media attachments such as audio and video. As Skype blocks you from sending PDFs as attachments in any form (links, local file, or Base64Strings), you can still send them as links by simply embedding the link in your text.
