### ISSUE TITLE
DCR: BotFrameworkAdapter.continueConversation() and createConversation() should create 'event' activities.

### ISSUE THREAD

**Issue by Stevenic** [Microsoft/botbuilder-dotnet#420]
Currently `BotFrameworkAdapter.continueConversation()` mocks up an activity of type `message` and `BotFrameworkAdapter.createConversation()` mocks up an activity of type `conversationUpdate`.  I'd argue that both of these are somewhat dangerous as they can easily trigger unexpected behavior in the bot and it might be safer to mock up an 'event' activity of some sort instead.

The potential issue with `message` is that it could cause the bot to call a service like LUIS unnecessarily or even worse it could cause a logger to log that the user sent a message with empty text when it was actually the bot initiating the flow.

For `conversationUpdate` the issue is it could cause a GreetingMiddleware to send an extra greeting to the user which on the surface doesn't sound too bad but what if the bot developer doesn't want this extra greeting?  The middleware has no way of telling if the `conversationUpdate` was generated because the user started a conversation with the bot versus the bot starting the conversation with the user so filtering to only sending a greeting when the user starts the conversation with the bot could be impossible.  In fact the GreetingMiddleware could actually intercept the `conversationUpdate` activity such that the bots logic doesn't event run.

By switching to an `event` activity that has a name of either `continueConversation` or `createConversation` the bots middleware can clearly identify the context in which its being run and there's no accidental running of unexpected behavior.  In the GreetingMiddleware case a bot developer can now configure the middleware to respond to just one or even both scenarios since they're still well know activity types.

**Comment by drub0y** [comment]
Wow, strange timing because yesterday afternoon I started writing an issue that I was tentatively titling `DCR: Rethinking the "proactive" messaging endpoint in integration libraries` which dovetails almost perfectly with this. Specifically, after working side by side with @ovishesh and seeing him try to port a "real world" scenario from V3 to V4, I realized that the endpoint that the integration libraries expose for what has been called "proactive" messaging is really supposed to be an endpoint for posting `event` activities. Right now it only takes a `ConversationReference` which, on its own, doesn't really get you anwhere because you can't submit an additional payload representing your custom event, so I was going to talk to you guys about changing that endpoint to expect an `event` activity instead.

**Comment by vishwacsena** [comment]
Done.
