### ISSUE TITLE
can't parse array in appsettings.json; can't handle number string as key in object

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#4200]
## Version
What package version of the SDK are you using.

61e4e5dde95f7fa1dca8330ae3d833b622ca22c6

## Describe the bug
Give a clear and concise description of what the bug is.

- When there is array in appsettings.json, it is not treated as array.
- When a json object uses number string as key, it is not handled

## To Reproduce
1. clone https://github.com/xieofxie/botbuilder-dotnet/tree/hualxie/array_bug
2. start Microsoft.Bot.Builder.TestBot.Json
3. type 2

## Expected behavior
Give a clear and concise description of what you expected to happen.

value|current|expected
-|-|-
settings.array|object|array
settings.object|System.Object[]|object
settings.array['1']|use '1' as key|use 1 as key i.e. array
json({'123':'234'})|crash|work correctly

## Additional context

[bug]

**Comment by compulim** [comment]
@cleemullins Could you take a look at this?

**Comment by vishwacsena** [comment]
Per @tomlm the issue probably is in settings memory scope.

**Comment by Danieladu** [comment]
Hi, I have made some investigations on this issue. Here are some achievements:
1. `appsettings.json`  does not support direct reading of array data. [reference](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.2#bind-an-array-to-a-class)
There are several workarounds [here](https://rimdev.io/avoiding-aspnet-core-configuration-pitfalls-with-array-values/), but they are not suitable for the dynamic data in this situation.
So, currently, the logic of BotBuilder is: if the last key of data is number, treat it as an array item.
For example:
```
  "object": {
    "123": "456"
  }
```
The original data is:"object:123" -> "456"
The last key can be parsed into integer, so the value of `object` is an array with 124 items, and the first 123 elements are `null`, the 124 item is string `456`. just like: `[null, null, ..., "456"]`

Another example in your case:
```
  "array": [
    "e1",
    {
      "obj": "e2"
    }
  ]
```
The original data from reading the configuration is:
```
   "array:0" => "e1",
   "array:1:obj" =>  "e2"
```

The key point is that it is impossible to distinguish whether this is a list or an object with an int as the key.

As the result, `settings.array` -> 
```
{
“1”: {
"obj": "e2"
},
“0”: “e1”
}
```
`settings.object` -> object[] but not object,
and 
`settings.array['1']` -> `{"obj": "e2"}`

2. The `json({'123':'234'})` issue
You may misuse the `property` of `Microsoft.SetProperty`.
The `Property` is `StringExpression`, So, if the expression does not start with "=", SDK would treat it as the string interpolation of Expression. The result of "${turn.data}" is an empty string, because `turn.data` is null. However, the empty string is not a valid key in dailogstatemenager.
The solution is to change it to "turn.data".
Another tip:`"value": "${json({'123':'234'})}"` is not a common usage, it would convert the result to string. If you want to set a json value into a certain property, could use `=json({'123':'234'})` instead.

Thanks

**Comment by xieofxie** [comment]
@Danieladu Thanks!
But comparing these two, I think it is better we treat the first one as object with key 123, so they are the same logic
```
  "object": {
    "123": "456"
  },
  "array": [
    "e1",
    {
      "obj": "e2"
    }
  ]
```
The SetProperty is my fault..

**Comment by Danieladu** [comment]
@xieofxie that will drop all list feature totally. For example:
```
 "array": [
    "e1",
    "e2"
  ]
```

Originally, the `array` property would treat as a real array => ["e1", "e2"]
If we disable this feature, all the plain array would be treated into object.
hmm. I have no idea about this one..

**Comment by xieofxie** [comment]
@Danieladu Another thought is that we require the user not to use number as key so we can easily treat number key as index in array.
I think **array of objects** is a more common usage than **number of object key**.

**Comment by Danieladu** [comment]
@xieofxie  this is a breaking change. Maybe @tomlm  can give some suggestions?
```
{
"option": {
  "1": "a",
  "2": "b"
 }
}
```
Would be treated into :
```
{
"option":[
  "a", "b"
]
}
```

**Comment by xieofxie** [comment]
@Danieladu right.. I think you missed a null here. The root cause is the way that dotnet treats appsettings, sad story.

**Comment by boydc2014** [comment]
The result after triaged is try to reverse the flatten result as array as possible, otherwise turn it into dict.
