### ISSUE TITLE
Refactor AdaptiveExpressions method GetStandardFunctions()

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botbuilder-dotnet#4208]
Method GetStandardFunctions  in _[libraries/AdaptiveExpressions/ExpressionFunctions.c](https://github.com/microsoft/botbuilder-dotnet/blob/43d91bfdf17fe1f08943c3fe5dbe16e66ad69731/libraries/AdaptiveExpressions/ExpressionFunctions.cs#L2764)s_ is 1881 lines long. It needs to be refactored. Please consider using an appropriate design pattern.

**Comment by cleemullins** [comment]
@boydc2014 During code reviews, we've been unable to reason over this method due to complexity. As many new PRs make changes to that method, the complexity needs to be reduced so that we can maintain agility. 

Myself, @mrivera-ms and @tomlm are very hesitant to take any new PRs in this area until the code has been refactored along with tests, so we can more concretely reason over the code.

**Comment by boydc2014** [comment]
> @boydc2014 During code reviews, we've been unable to reason over this method due to complexity. As many new PRs make changes to that method, the complexity needs to be reduced so that we can maintain agility.
> 
> Myself, @mrivera-ms and @tomlm are very hesitant to take any new PRs in this area until the code has been refactored along with tests, so we can more concretely reason over the code.

Thanks, like i present in some PR comments, i feel like it's more of a data table than a code, but i totally understand this could be confusing for two major issues, 1 is is a table for lambada function and 2 we used some high-order function wrappers around an specific function implementation. 

I will call a check-in of this issue on dev side soon to get a fix for this.
