### ISSUE TITLE
don't set context.Responded for trace events (such as LUIS trace events) and other events that aren't messages to user

### ISSUE THREAD

**Issue by DeniseMak** [Microsoft/botbuilder-dotnet#423]
Just discussed this with Tom. The SDK shouldn't set `context.Responded` for trace events (such as LUIS trace events) and other events that aren't messages to the user.

We use `context.Responded` for fallback processing to see if middleware has already sent a response, and execute fallback logic if not. So setting `context.Responded` to `true` for non-message events will break this scenario when you have LUIS middleware and are running the bot in the emulator.

To repro, if you're using the emulator and getting LUIS trace events, and have added both QnA and LUIS middleware, (like add LUIS to https://github.com/Microsoft/botbuilder-dotnet/tree/master/samples/Microsoft.Bot.Samples.Ai.QnA) the following fallback code in your bot's `OnTurn` will never get hit.

```cs
switch (context.Activity.Type)
            {
                case ActivityTypes.Message:
                    if (context.Activity.Type == ActivityTypes.Message && context.Responded == false)
                    {
                        // add fallback logic when QnA Maker middleware doesn't find an answer
                        await context.SendActivity("No good match found in the KB, so let's use LUIS intents.");
                        // display LUIS intents here as fallback to QnA
                        var luisResult = context.Services.Get<RecognizerResult>(LuisRecognizerMiddleware.LuisRecognizerResultKey);
                        await (string key, double score) topItem = luisResult.GetTopScoringIntent();
                        await context.SendActivity($"The top intent was: '{topItem.key}', with score {topItem.score}");
                    }
 // ...
```

**Comment by cleemullins** [comment]
Great point. Fixing now.

**Comment by AndreMantas** [comment]
We have this exact issue but when sending typing activities.

For example, adding a middleware that sends a typing activity when the incoming activity is of type message.

This completely ruins all kind of `ChoicePrompt`, `NumberPrompt` and so on if you don't send custom error messages from your validation methods. The user types an invalid value and there's no reprompt simply because the `TurnContext.Responded` is already true although no message indicating the error was sent.

As a workaround, our typing middleware sets `TurnContext.Responded` back to false through reflection (which sucks).

Any chance there could be a better alternative for this?

Currently using BotBuilder 4.5.3
