### ISSUE TITLE
Dialog Abstraction

### ISSUE THREAD

**Issue by hawkpgl** [microsoft/botbuilder-dotnet#4260]
**Is your feature request related to a problem?** Yes.
The current Dialog structure is highly dependable on implementations, and not on abstractions. I.e.: If I want to add child dialogs into a Waterfall Dialog, I have to provide a Dialog instance to the method ComponentDialog.AddDialog(Dialog dialog). That prevents me to inject the Child Dialogs into the Parent Dialog constructor, to be used in the AddDialog() method.

**Describe the solution you'd like** To abstract the Dialog class into an IDialog interface.
Create a public Interface called IDialog, and implement it on Dialog.cs. The interface should contain all the public members that are currently in Dialog.cs. DialogSet.cs should then have IDictionary<string, IDialog> _dialogs, and all other references to Dialog.cs should be abstract, pointing to IDialog instead. Then extend the method `ComponentDialog AddDialog(Dialog dialog)`, by adding `ComponentDialog AddDialog(IDialog dialog)`, this will prevent breaking changes. 

Now it's possible to create IMyCustomDialog, implementing IDialog, and register it on my DI container. Then I can inject my child dialogs on my parent dialogs without having to concern about their dependencies. On my Parent Dialog constructor, I change the `MyCustomDialog.Id` to what I want, and use it in `AddDialog(MyCustomDialog)`.

**Describe alternatives you've considered**
To solve this technical dept with the current implementation, I had to opt by the Factory pattern. Having a Factory for each of my Dialogs, then injecting my Dialog Factories into my Parent Dialogs, and getting an instance from them to be used in the AddDialog(Dialog dialog) method.

**Additional context**
I've made the changes myself and opened a PR for them. Ran all the tests without any issues, and tested the generated packages with my own project currently using V4.9.3. Everything working as expected and no breaking changes detected.

**Comment by compulim** [comment]
@gabog a PR is opened, could you take a look at this approach?

**Comment by gabog** [comment]
Hi @hawkpgl, thanks for the suggestion but interfaces are problematic for backward compatibility and we try to favor base classes rather than interfaces (we have some legacy interfaces but we keep them around for backward compat too). 

The `Dialog` class is abstract and I think you should be able to implement what you need using that (I don't know the details of your implementation but if you create a abstract `MyCustomDialog` that derives from `Dialog` may work). 

C# 8.0 introduces default implementation methods but we can't use that because we need to support other versions of the framework that don't support it. 

I think your approach of creating a factory is a good solution for this problem, using the options pattern and passing a set of child dialogs to your parent without blowing up the constructor could work too for DI. 

Hope that helps.

Let me know if you have any other comments and thanks again for the feedback.

**Comment by hawkpgl** [comment]
Thank you for the feedback @gabog . I'll stick with the Factory pattern for now then. 

Pardon my ignorance, but since you mentioned "too many breaking changes", could you give me a simple example on something that would break by merging that PR? I'm asking because not a single unit test from more than 4.5k failed, and I kept both implementations of the AddDialog method to not affect previous implementations.

As a fan of the [Dependency Inversion Principle](https://en.wikipedia.org/wiki/Dependency_inversion_principle), I'm afraid this lack of abstraction will give people more headache in the near future. It's like on V3, when we had to cast our messages as an `Activity` when using SendToConversationAsync(), even though `IMessageActivity` implemented `IActivity`, just because the method was expecting an implementation of `Activity`, instead of an `IActivity `object.

**Comment by EricDahlvang** [comment]
Closing, please open a new issue if you are still having trouble.  Or, direct questions to StackOverflow.

Thanks.
