### ISSUE TITLE
IStorage should return IDictionary<string, object> instead of IEnumerable<string, object>

### ISSUE THREAD

**Issue by tomlm** [Microsoft/botbuilder-dotnet#428]
No reason to make people grovel over the data structure.

**Comment by drub0y** [comment]
If you feel strongly enough about this it's of course easy enough to change, but I have a philosophy of not spinning up expensive data structures until someone needs really needs them. Right now, if someone really wants/needs to work with this data in an actual `Dictionary<K, V>`, a dev need do little more than wrap the returned `IEnumerable<KeyValuePair<string, object>>` using the `Dictionary<K, V>(IEnumerable<K, V>)` constructor. In fact, I did this in a couple tests.

A few more thoughts:

1. I would just point out that the typical developer does not work at this API level. Developers writing middleware/bots working with `BotState<TState>` layer of abstraction. Thus, I think it's more important to focus on optimizations at this level. Not allocating dictionaries when _nothing actually needs dictionaries_ is one such optimization.
2. The interim goal in this PR was to eliminate the dynamic stuff, specifically the `StoreItems` "bag" in this case, from the API, but I think we all agree there is still work to be done here. Whether it's the current proposed DCR (#375) or some other approach, I don't think will be the exact API for much longer.
3. Overall I tend to favor using `IEnumerable<T>` as it allows for deferred execution/processing which enable all manner of optimizations. It also never forces any specific allocation model either. For example, I would almost always choose to take/return `IEnumerable<T>` by default. For example, method signatures that _force_ allocating an array are a huge red flag IMHO. The one big missing feature for .NET is still the lack of `IAsyncEnumerable<T>` (aka "async streams") which allows the underlying stream to be realized asynchronously rather than _having to be buffered_ into some in memory storage mechanism. Fingers crossed for vNext.

**Comment by cleemullins** [comment]
For me the simplicity of the IDictionary<K,V> semantics of the more complex semantics of the IEnumerable<KeyValuePair<string, object>> seem like a win. 

I think this is something to consider post-build, as we consider other potential state mechanisms.

**Comment by drub0y** [comment]
Yeah I think my point 2 is probably the biggest thing to changing this right now. 

How much more do we want to invest in the interface design right now if we're going to have a broader review of all state management post build? This isn't going to kill anybody and it doesn't prevent any scenarios, so I wholeheartedly agree with pushing this to post build/post state management API review.
