### ISSUE TITLE
Coalesce and the datetimeV2 entity

### ISSUE THREAD

**Issue by Trubzzz** [microsoft/botbuilder-dotnet#4378]
I'm having an issue with extracting user input from a triggering utterance, specifically when it comes to the datetimeV2 entity. I'm currently working on a process with multiple entities required and an open-ended initial intent trigger. For example, 
1) User: I want to book an appointment
2) User: My name is John and I'd like to schedule an appointment
3) User: My name is John and I'd like to schedule an appointment for Thursday at noon

Ideally, the process should trigger the following results based on the input above
1) Bot: Can I have a name for the appointment?
2) Bot: When would you like to schedule the appointment?
3) Bot: Ok, let me see if this time is available.

For the name entity, I'm using the coalesce expression to see if the entity had been filled previously in the conversation to skip the name question. However, if I use the same technique for the datetimeV2 entity, the value is always filled as null and the bot responds with "When would you like to schedule the appointment?" if I type "My name is John and I'd like to schedule an appointment for Thursday at noon". 

Am I missing something here? Since datetime is a more complicated entity value, is my syntax incorrect here?

Intent trigger
![image](https://user-images.githubusercontent.com/64170617/87270162-f43c0700-c494-11ea-91b4-0437c2861847.png)

Set properties task
![image](https://user-images.githubusercontent.com/64170617/87270190-08800400-c495-11ea-98cc-25019f086063.png)

**Comment by vishwacsena** [comment]
@chrimc62 @tomlm can we converge on the shape of entity recognition result across LUIS + the date time recognizer used by datetime input?

**Comment by peterinnesmsft** [comment]
@vishwacsena any follow up here to define requirements per DCR ask?

**Comment by vishwacsena** [comment]
We will need to consider a fix here in a future release. It will be good to align the local entity recognition result for inputs with the structured returned on LUIS result.

**Comment by GeoffCoxMSFT** [comment]
@vishwacsena - Please resolve

**Comment by vishwacsena** [comment]
Not resourced for R11. Will keep in backlog for possible fix in a future release.

**Comment by mrivera-ms** [comment]
@garypretty, could you please take a look and prioritize this item? Should we consider this for R12?

**Comment by garypretty** [comment]
I think it would be good to address this issue, as it has been open for a while and this certainly can be a source of frustration.  I have marked as a P2 for R12, given we don't know the size / shape of this yet and it is not higher priority that the other things we have in plan right now. 

I think it would be a good start to sync with @lauren-mills to get some feedback on how the above problem surfaces and is ultimately handled within the calendar skill.  The ultimate solution here may not be a change in the recognition result (especially as other recognizers may be used in the future for date time recognition and we have no guarantee that they will adhere to the same shape), but could be providing a package containing assets to help with date time resolution.

**Comment by compulim** [comment]
DRI, please look at this issue next week as R13 planning start.

**Comment by mrivera-ms** [comment]
@lauren-mills, can you comment on this?

**Comment by lauren-mills** [comment]
In the calendar skill, I do not use either the LUIS recognized date time (because I don’t have a way to provide the user’s time zone for relative dates like tomorrow at 3pm) or the date time prompt (because it has limited recognition support and configuration options). I ended up writing my own dialog that sends the user utterance through the Microsoft.text.recognizers lib directly and then has default disambiguation logic based on the recognized date time type. 

What I’ve built works well for calendar, but would need to go through a more thorough review before I’d say it’s a good date time input replacement. 

Another option is to surface support for passing in the time zone to LUIS in composer. I think this is possible with their sdk, it’s just not feasible for me get to it with the current options.

I also think @chrimc62 has a work stream going to look into date time more.

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
