### ISSUE TITLE
QnAMakerOptions using StrictFilters how to check "contains" for metadata filters

### ISSUE THREAD

**Issue by saikiran521** [microsoft/botbuilder-dotnet#4437]
Hi,

I using QnA Maker API to get response for StrictFiletrs as

{
    "question": "qna maker and luis",
    "top": 5,

    "strictFilters": [
    {
        "name": "category",
        "value": "api"
    }]
}

getting response if metadata key and value matches with given input. (if metadata key is "category" and value is equal to "api" getting response)

Please let me know is there any way to check given input contains in metadata (if metadata key is "category" and value contains "api")

Thanks in advance

**Comment by jwiley84** [comment]
@dmvtech

**Comment by dmvtech** [comment]
Hi @saikiran521,

My apologies, but could you clarify a little bit further? I'm not quite clear on what you are asking. Are you wanting to check that the strictFilters you supply in the request match the strictFilters you get in the response?

**Comment by saikiran521** [comment]
Hi @dmvtech 

Using strict filters data checks equals with metadata key value pair. For example if metadata is "category:api" we can retrieve by strict filters as 

"strictFilters": [
{
    "name": "category",
    "value": "api"
}]

I need an example if metadata is "category: api response" I need to get response using same strict filter as

"strictFilters": [
{
    "name": "category",
    "value": "api"
}]

need a solution if value of the strict filter is a sub-string of the metadata value, how to give the input and get the response

**Comment by dmvtech** [comment]
I believe the strictFilters are meant to be pretty strict. That's why it doesn't work that way.

If you have specific scenario/situation where you have a a set list of values, you could (conceivably) add logic in your code before [applying strictFilters](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/metadata-generateanswer-usage#use-qna-maker-with-a-bot-in-c) to QnAMakerOptions to handle that. For example, a function that would strip the ` response` from the value before setting the metadata.

Otherwise; (since this isn't an bot feature, but QnAMaker), you could open a request to have this added changed. Do this by creating a [UserVoice ticket for QnAMaker](https://cognitive.uservoice.com/forums/578689-qna-maker-api).

**Comment by saikiran521** [comment]
thank you for your response @dmvtech, will raise a ticket in QnAMaker
