### ISSUE TITLE
Support for ASP.NET Core 2.1?

### ISSUE THREAD

**Issue by nrandell** [Microsoft/botbuilder-dotnet#448]
What are the plans for supporting this on ASP.NET Core 2.1?

Given the takeup of ASP.NET Core 2.0 when it came out, I guess most people will be upgrading to 2.1 as soon as it is ready.

**Comment by cleemullins** [comment]
@nrandell, I think it depends on the compatibility story. 

If it's easy to "Multi-Target", then supporting both seems like a great idea. If we have to have a 3rd integration library (ASP.Net WebAPI, Core 2, Core 2.1) then it's something we'll need to evaluate. 

Personally, I suspect @drub0y will have an ASP.Net Core 2.1 integration PR submitted very soon after 2.1 is released.

**Comment by drub0y** [comment]
So, this is a bit of an overloaded question. The short answer is: it should "just work". 

First, .NET Core has declared they are using a "roll-forward" approach to their major versions, so whatever works on 2.0 should work on all 2.x. So that means if you were to spin up a new project and target .NET Core 2.1, you will be able to use all of our libraries. Not only that, but, since the libraries are targeting .NET Standard 2.0, they should continue to run anywhere that supports that standard subset of APIs.

Next, from a runtime perspective, we will automatically gain from any JIT/CLR optimizations in the 2.1 obviously. Additionally, if you wanted to configure your ASP.NET 2.1 host with something like the new Socket transport to benefit from it's performance gains over the libuv version, you could do that and the BFSDK wouldn't know the difference.

Finally, from a perspective of leveraging new APIs (e.g. `HttpClientFactory`), obviously we would need to upgrade the codebase to utilize newer APIS . This would take a little longer as it would mean bumping dependency versions and, as always, that's a delicate game that takes a good amount of consideration.

**Comment by nrandell** [comment]
That's what I thought. I've had it running on 2.1, but found some issues running on Azure where I kept on getting 502.3 errors when sending activities at certain times.

However - and this is a big however - I think it may have been down to user error on my part, which is why I wanted to ask the question about should it work rather than a specific problem.

Now I've got my scenario working under 2.0, I can try again with 2.1 to see if the problems still exist and update this thread.

**Comment by drub0y** [comment]
Great, let us know!

**Comment by nrandell** [comment]
So I created a new test repository (https://github.com/nrandell/botbuilder-dotnet-issue-448) - and guess what - it all works ok!

I then switched the original version back to 2.1 and it worked ok.

This may be something transient that is down to the roll out of 2.1

I'll close the issue for now.
