### ISSUE TITLE
Accessing UserState/ConversationState properties

### ISSUE THREAD

**Issue by Rouvo** [microsoft/botbuilder-dotnet#4500]
Hi all,

I'm trying to set up a little bot architecture, where botframework composer will act as the leading part (easy deployment + set up). Im coding my own directline chat at the moment and trying to pass data objects around via webviews that will also be used by the facebook chat.

I came up with a little "middleware" concept, where I'm using azure functions for creating endpoints (such as for sending pro active messages to certain users) together with botbuilder js in order to use "adapter.continueConversation" for communicating with my deployed bot. 

The communication works without any problem, I can for instance send pro active messages upon clicking a button in a webview. Now I want to pass more complex data into my conversation flows from the mentioned "middle ware".

I'm using Cosmos DB as a storage and created two dataAccessor objects, as I knew it from other tutorials in the past

```
const conversationState = new ConversationState(storage);
const userState = new UserState(storage);
let conversationDataAccessor = conversationState.createProperty("conversationData");
let userProfileAccessor = userState.createProperty("userProfile");
```

Now I'm struggling with accessing the "UserState" + "ConversationState" in botframework composer, what is the best way to achieve it? Does the approach via ConversationState and UserState even makes sense in this context or is there an easier way to achieve this shared data scenario?

Sorry for my bad English, I hope that I wrote it clearly and understandable, if there are open questions feel free to ask.

Best regards

**Comment by tdurnford** [comment]
@vishwacsena Can you follow up?

**Comment by vishwacsena** [comment]
@Stevenic @tomlm any suggestions?

**Comment by EricDahlvang** [comment]
Hi @Rouvo 

If I'm understanding correctly, you are trying to save something in UserState within middleware which should then be available in composer.  But, the middleware is currently storing values differently.  Is that correct?

The difference in your middleware's saved state, and composer, appears to be due to the fact that the internal state storage implementations will store type information by default.  It looks like your middleware is not storing type information?  Also, composer is storing a dictionary of key and object.  Have you tried changing the middleware to store a dictionary of key and object?

**Comment by EricDahlvang** [comment]
Hi @Rouvo 

Are you still working on this?  Or, should we close the issue?

**Comment by Rouvo** [comment]
> Hi @Rouvo
> 
> Are you still working on this? Or, should we close the issue?

Hi @EricDahlvang, I was on holidays and just saw the new replies. 
We are now using a different platform in order to implement our conversational user interface, so closing the issue was the right decision.
