### ISSUE TITLE
delay text output

### ISSUE THREAD

**Issue by LucaCerina** [microsoft/botbuilder-dotnet#4509]
## Is your feature request related to a problem? Please describe.
When trying to fake the interaction with a real human, the user expects that the other end needs some time to write the response. The send response settings should allow a non-zero delay in the answer.

## Describe the solution you'd like

Either allow `new Activity { Type = ActivityTypes.Typing }` and `new Activity { Type = "delay", Value= xxx }` as separate dialog elements, or add a parameter in the send an activity UI to include this

## Additional context

The framework allows the use of a typing indicator https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-send-messages?view=azure-bot-service-4.0&tabs=csharp

**Comment by vishwacsena** [comment]
Consider a general purpose delay action that can be added prior to specific bot operations.

**Comment by tsuwandy** [comment]
@jwiley84, any update on this?

**Comment by ninggao** [comment]
@jwiley84, any update on this?

**Comment by stevengum** [comment]
@reinoldus it sounds like you're asking for an Action that sends a Typing Activity, which would be called before each message activity is sent. Is this correct?

**Comment by EricDahlvang** [comment]
Incoming calls from a channel have a timeout of 8 to 15 seconds depending on channel.  This limitation inhibits most thread wait or long processing scenerios, without background activity processing.   A dotnet experimental example of this, with various ways of pausing and resuming processing of bot activities, can be found here: 

https://github.com/microsoft/BotBuilder-Samples/tree/main/experimental/immediate-accept-adapter/csharp_dotnetcore

Once incoming activities are processing on a background thread in the exported runtime of composer, implementing a "WaitAction" dialog with a configurable timer period would work for the purpose of the use case described above (if i'm understanding the problem correctly).

The dialog could determine the length of the last message, and wait an appropriate amount of time based on length of text sent perhaps.

**Comment by reinoldus** [comment]
I switched to writing the bot in code entirely in the meantime.

What I am doing in my "code bot" is the following:

```
async def send_message(context, message: Dict[str, str]):
    if isinstance(context, WaterfallStepContext):
        context = context.context
    text = message['text']
    await context.send_activity(MessageFactory.text(text))
    sleep_time = (len(text.split(" ")) / 5)
    await asyncio.sleep(sleep_time)
```

In conjunction with:
`ADAPTER.use(ShowTypingMiddleware(delay=0.5, period=2.0))`

So after each message has been sent, the bot waits `len(text.split(" ")) / 5` seconds. The reasoning behind that is: 
This time frame is approximately the time an average reader needs to read the message just sent (https://capitalizemytitle.com/reading-time/1000-words/). In my tests that worked pretty well, because you do not want to wait for the bot to type, you just don't want to be flooded with messages. So this is pretty much what @EricDahlvang described.

With all my new experience with implementing the bot in code, I would have loved to see these features in the composer:

- Have a general option that does what @EricDahlvang described.
- Have the option to delay each activity individually, because if you "quiz" a user about something, it feels more natural if the next question is delayed by a second or something (just my UX-experience)
- It would probably be helpful if one could set all these options by message type, so you can globally set a delay of e.g. 1 second for every "Prompt"-type.
- It is vital that all of these delays can be disabled easily so you can test it quickly without any waiting time.

I hope that clears up what I was looking for.

Thank you for your support!

**Comment by EricDahlvang** [comment]
I've re-read this thread, and tested out the 'delay' activity type from composer.  This works as expected on channels, but not the emulator (i think because the emulator is holding the calling thread, and waiting for completion):

```
[Activity
    Value = ${3000}
    Type = ${"delay"}
]
```

![image](https://user-images.githubusercontent.com/11055362/96386948-a3067800-1153-11eb-9133-d9f537f6c305.png)

The typing indicator does not include a delay, as it is a client side indicator that something is occurring on the server side.  However, the delay activity type will pause server processing for the specified number of milliseconds before proceeding.

Dotnet:
https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L530

Javascript:
https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/botFrameworkAdapter.ts#L1230

@reinoldus The delay activity type is also provided in the Python sdk:
https://github.com/microsoft/botbuilder-python/blob/main/libraries/botbuilder-core/botbuilder/core/bot_framework_adapter.py#L692

I hope this helps.  I think we can close this, since the sdk does provide a method for accomplishing the desired goal.  We could potentially improve support for this, by providing a 'delay' time period to SendActivity, which would just queue up a 'delay' activity, enabling a pause afterwards.

**Comment by EricDahlvang** [comment]
Re-opening this.   

@garypretty can we consider simplifying and supporting some form of this more directly from Composer?

**Comment by mrivera-ms** [comment]
@garypretty, there is a workaround from the SDK. There is an issue in Emulator that needs to be resolved. Please see the history. Could you please add a priority to this item?

**Comment by garypretty** [comment]
@EricDahlvang This does work as expected in Emulator today by specifying in Composer. Not sure if we changed something?  The below works for me.

![image](https://user-images.githubusercontent.com/3900649/110098609-47eac000-7d98-11eb-9e31-2a8831071ad6.png)

@LucaCerina could you try the above please and see if this works for you?

**Comment by piechk** [comment]
When attempting to use this type of delay, SMS does not respect this activity.
