### ISSUE TITLE
DialogManager OnTurnAsync does not call OnMembersAddedAsync, whereas ActivityHandler does

### ISSUE THREAD

**Issue by Rufus1123** [microsoft/botbuilder-dotnet#4518]
## Version
4.10.0

## Describe the bug
Coming from the [Virtual assistant template](https://github.com/microsoft/botframework-solutions/tree/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample), I am now trying to add composer dialogs as adaptive dialogs into the solution. Following the steps [here](https://microsoft.github.io/botframework-solutions/skills/handbook/experimental-add-composer/), and looking at the way composer dialogs are implemented in [this sample](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/adaptive-dialog/09.integrating-composer-dialogs/Bots/DialogBot.cs), I am replacing the line:
```
            await base.OnTurnAsync(turnContext, cancellationToken);`
```
to
```
            await _dialogManager.OnTurnAsync(turnContext, cancellationToken);
```
in the `OnTurnAsync` method of `./Bots/DefaultActivityHandler`. 
In the virtual assistant template, there is also a method `OnMembersAddedAsync`. The `base.OnTurnAsync` method makes sure this method is called for appropriate activities, however the `OnTurnAsync` that was implemented in the DialogManager class does not. The latter seems to take a completely different approach to handling `BotOnTurnAsync`s (see https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs#L375)

To conclude, I'm not really sure that this is a bug then, but I don't understand why the two implementations of OnTurnAsync are incompatible. Is the DialogManager indeed the recommended way to include composer dialogs into your bot? And if so, how do you handle ConversationUpdates and other events when using the dialog manager?

## To Reproduce
See above

## Expected behavior
I expected OnMembersAddedAsync to run for ConversationUpdate activities, even after switching to the dialog manager in stead of the default activity handler

## Edit
I have played around a little bit and found the code below to work for me. I would still like to know if this is the intended way, as I didn't find any documentation on this.

```
            await _dialogManager.OnTurnAsync(turnContext, cancellationToken);
            if (!turnContext.Responded)
            {
                await base.OnTurnAsync(turnContext, cancellationToken);
            }
```

**Comment by vishwacsena** [comment]
@tomlm can you comment/ clarify?

**Comment by tomlm** [comment]
This is by design, as it's all under under your control. 

DialogManager.OnTurnAsync() will take any activity and route it to the dialog stack.  This gives every dialog in the system the ability to respond contextually to non-message activites, for example, the user typing, or a message like, or event when a person joins the conversation.  Say you are playing a game, you want the dialog for the game to say "welcome, John, you can't join the game until we start the next round. I'll add you in to the game then."  To do that you want the logic for that to be in the GameDialog that is driving the game.

The ActivityHandler class has a bunch of virtual helper methods which is designed to make it easy to work different activity types _without a dialog system._ Meaning, if you just want to respond to various activities you can implement the virtual method for that activity and write your code.  This is a useful paradigm because not everyone wants or needs a dialog system.

The way the ActivityHandler class is written is that OnTurnAsync(Activity) is called. The _default_ implementation of that virtual method inspects the activity and calls the appropriate virtual method per activity type.

```
OnTurnAsync(activity)
   => OnMessageActivity(activity as IMessageActivity)
   => OnConversationUpdateActivity(Activity as IConversationUpdateActivity)
   => etc...
```

Some handlers like OnConversationUpdateActivity() will actually break the activity up into individual OnMemberAdded() or OnMemberRemoved() calls. 

So...given all of this, if you override the virtual method 

```
OnTurnAsync(activity) => dm.OnTurnAsync(activity); 
```

You are disabling all of the virtual methods because you are routing ALL activity types to the dialog system via the dialogmanager.

But that's not the only you could do it.  If you leave OnTurnAsync() alone, it will call the other virtual methods.  In those methods you can decide to process the activity, or pass on the dialog system at your discretion.

```
OnMessageActivity(activity) => dm.OnTurnAsync(messageActivity)
OnMemberAdded(member) => do what you normally do, 
OnTyingActivity(activity) => dm.OnTurnAsync(typingActivity)
```

etc.

To make the layering super clear, DialogManager is completely independent of the ActivityHandler class.  They can work together, or they can work independently. For example, it is completely normal to not use the ActivityHandler at all, you can simply do this:

```
        [HttpPost]
        public async Task PostAsync()
        {
			// call the dm.OnTurnAsync directly as the handler for the turn
            await adapter.ProcessAsync(..., (tc, ct) => dm.OnTurnAsync(tc, ct), ...);
        }        
```

**Comment by tomlm** [comment]
One more note:  the layering of libraries gives you a hint here too.

**ActivityHandler** is defined in **Microsoft.Bot.Builder** which is the library that defines everything you need to respond to activities **without a dialog system.**

**Dialog/DialogContext/DialogManager etc** is defined in **Microsoft.Bot.Builder.Dialog** which is a dialog library on top activities as  protocol, which defines a dialog system mechanism for organizing your responses to activities.
