### ISSUE TITLE
How can I configure hostconfiq for adaptive card in botbuilder-dotnet

### ISSUE THREAD

**Issue by Shivang007-del** [microsoft/botbuilder-dotnet#4549]
How can I configure hostconfiq for adaptive card in botbuilder-dotnet

**Comment by v-kydela** [comment]
Thank you for the question, @Shivang007-del 

The Bot Builder SDK is for building bots. [HostConfig](https://docs.microsoft.com/en-us/adaptive-cards/rendering-cards/host-config) is something only Adaptive Cards renderers are concerned with, and bots can only author Adaptive Cards and not render them. As my blog post explains, your bot is not supposed to have any control over the Adaptive Cards renderer: https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/

If you are using [Web Chat](https://github.com/microsoft/BotFramework-WebChat/issues/2034#issuecomment-501818238) then you will have control over the renderer, but you have to supply the host config on the client side and not the bot side so that's still irrelevant to botbuilder-dotnet. If you're using any channel other than Direct Line then you will not be able to provide your own host config.

We do prefer to have how-to questions asked on [Stack Overflow](https://stackoverflow.com/questions/ask) instead of GitHub. This reaches a larger audience, allowing more people to possibly answer the question and more people to be helped by the answer. If you use the [`botframework`](https://stackoverflow.com/questions/tagged/botframework) tag then my team will be sure to see the question.

I am closing this question as answered.
