### ISSUE TITLE
Create additional unit tests for TokenResolver

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-dotnet#4679]
Regarding testing, adding negative tests to this code area would be great. Not mandatory for this PR but something I'd love to see in R11 as part of our investment to make this more solid.

_Originally posted by @carlosscastro in https://github.com/microsoft/botbuilder-dotnet/pull/4675#discussion_r492309250_

**Comment by denscollo** [comment]
Hi @mrivera-ms, we reviewed the issue and it's parent PR, and some concerns arose.
A concern we have is that all the exceptions from PollForTokenAsync() are caught with a single catch with no output besides a logError. Because no specific error is expected, our only way to assert them would be through the logs, which is not a consistent approach to tests errors. 
Another concern is validating for empty or null attachments in CheckForOAuthCards(), since the method returns void, without providing any output that we could assert.
Please, let us know what you think about these observations.

**Comment by mrivera-ms** [comment]
Thank you for the review, @denscollo . @stevengum , after reviewing the code, I believe it is best to push this item and prioritize refactoring for testability. I will create an issue to track that work for a future cycle.

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
