### ISSUE TITLE
Some types are internal or private, instead of public

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#472]
The following types are suspiciously not public:
```csharp
namespace Microsoft.Bot.Builder.Ai.LUIS
    internal interface ILuisRecognizer : IRecognizer
```
```csharp
namespace Microsoft.Bot.Builder.Dialogs
    delegate Task<O> PromptValidator<R, O>(TurnContext context, R value);
```
```csharp
namespace Microsoft.Bot.Builder.Integration.AspNet.WebApi.Handlers
    internal sealed class BotMessageHandler : BotMessageHandlerBase
```
- [The corresponding BotMessageHandler for ASP.NET Core is public.]

**Comment by drub0y** [comment]
*RE: BotMessageHandler* - oops, yeah I made the Core one public, I guess I just missed the WebAPI one. Honestly it's debatable that these should be public, but I know a lot of people tend to be upset when things are marked internal/private so, barring any discussion, I was just erring on the side of caution and making it open until we discussed otherwise.

**Comment by JonathanFingold** [comment]
I don't really mind as long as it's intentional. With one BotMessageHandler public and one internal, this looked like an oversight.
