### ISSUE TITLE
ArrayChangeType value names are not standard and don't make sense in English

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-dotnet#4822]
## Version
What package version of the SDK are you using: _R11_ (main) as of 10/20/2020

## Describe the bug
Give a clear and concise description of what the bug is:
- Provided enumeration values are: push ("to end"), pop ("from end"), take ("from front"), remove ("regardless of location"), and clear.
- **Bug**: I'm not sure what the semantics of **Remove** are: all matching elements, first matching element (from front or from end)?
- Pseudo-bug: push and pop are common terms, take and remove are not.
- Common array manipulation operations are: insert at back, insert at front, remove from back, remove from front, examine first element, examine last element.

## To Reproduce
1. Look at the [ArrayChangeType enumeration](https://github.com/microsoft/botbuilder-dotnet/blob/74198edbd90d1ee93e68e416271ccca5f658cda2/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EditArray.cs#L79-L109) and how it's used in the [EditArrary](https://github.com/microsoft/botbuilder-dotnet/blob/74198edbd90d1ee93e68e416271ccca5f658cda2/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/EditArray.cs#L28-L36) action.
1. Error: Try to predict what the behavior of EditArray is when `changeType` is set to `ArrayChangeType.Remove`.

## Expected behavior
I shouldn't have to write test code (or dive deep into the SDK code) to figure out how this actually works and whether it is even working as expected.

**Comment by mrivera-ms** [comment]
@garypretty please review and let us know what the expected behavior is. Thank you.

**Comment by garypretty** [comment]
@mrivera-ms I don't know what the actual / expected behavior is here (I wasn't involved in the adaptive development). You would need to either dig into the code itself or reach out to the original developers to understand that. Suggest that either you / @EricDahlvang dig in to understand what the action is doing today, or reach out to @tomlm / @Stevenic.

Once you have clarity, this feels like a code docs / MS docs issue for @JonathanFingold to add clarity.

**Comment by mrivera-ms** [comment]
@JonathanFingold, please see if #5045 resolves this.
