### ISSUE TITLE
Remove references to Trusted Service Url throughout the code.

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-dotnet#4833]
In R11 we obsoleted and disabled the Trusted Service Url behavior in the AppCredentials class. All references shoudl be cleanup through the remaining parts of the code.

**Comment by johnataylor** [comment]
Refer to https://github.com/microsoft/botbuilder-dotnet/pull/4827

**Comment by alexanderyakuba** [comment]
Hi guys, do your changes somehow related to this check?
Because the token I provide doesn't contain that claim. 
https://github.com/microsoft/botbuilder-dotnet/blob/bfa307619f5456d4ff5b7d4dd074433012aada9d/libraries/integration/Microsoft.Bot.Builder.Integration.AspNet.Core/BotFrameworkHttpAdapter.cs#L294

I obtain the token using this approach:
https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0#step-1-request-an-access-token-from-the-azure-ad-v2-account-login-service
