### ISSUE TITLE
SDK throws error "System.ArgumentException: The key already existed in the dictionary."

### ISSUE THREAD

**Issue by thehundred** [microsoft/botbuilder-dotnet#4837]
## Version
4.9.2

## Describe the bug
Sometimes when channel tries to establish web socket connection with bot, it fails because the bot SDK throws the following exception
System.ArgumentException: The key already existed in the dictionary. at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.IDictionary<TKey,TValue>.Add(TKey key, TValue value) at Microsoft.Bot.Builder.Streaming.StreamingRequestHandler.<ProcessRequestAsync>d__17.MoveNext()

This typically happens after there has been a service restart. It is possible that the service might be tad bit slow to respond and if there are 2 activities that arrive at the same time, both of them are trying to add the key to the dictionary

## Expected behavior
SDK shold not throw exception

**Comment by EricDahlvang** [comment]
This appears to be due to how the ConcurrentDictionary is not being used correctly: "The key already existed in the dictionary" <-- this really should not happen with a concurrent dictionary.

Looking at the code, it is created as a concurrent dictionary: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Streaming/StreamingRequestHandler.cs#L85 but then just the IDictionary interface is used to add items:

```cs
if (!HasConversation(activity.Conversation.Id))
{
     _conversations.Add(activity.Conversation.Id, DateTime.Now);
}
```

There is a race condition between multiple threads and line: !HasConversation and line: _conversations.Add ... this should be either .GetOrAdd, .TryAdd, or .AddOrUpdate
