### ISSUE TITLE
Combined Url / Messageback CardAction

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#5001]
Currently when using an URL CardAction in an activity the bot does not know when the user clicked this link. However often a follow up activity is required when user clicks the link to inform them when they return, ask if it was helpful etc.

To overcome this I typically change the initial action to a post button and then display the link with additional information, which is more code and also it's an extra click for the user, which is often not welcomed by the business.

Having an URL Cardaction that messages back when it is clicked would be a big improvement for flows like these.

This is probably limited by Clients, but just throwing it out here, as our main channels are web & teams (both controlled by MS)

**Comment by axelsrz** [comment]
@garypretty could you provide some input or direct this to correct person? Thanks.

**Comment by EricDahlvang** [comment]
This would be a protocol level DCR, since it would require returning a redirect status code (307).

However, this can currently be accomplished with a redirect controller, and passing the actual url as a parameter.  Here is a relatively simple example: https://github.com/EricDahlvang/OpenUrlRedirectBot  This is using an adaptive card, but could be used for CardAction urls also.

**Comment by cxbuilders** [comment]
@EricDahlvang Thanks for the update. This would be a nice and useful addition to the CardActions. Having a custom redirect controller is not really worth it for us with the change of Urls, changing Teams allowed domains etc, customizing the Composer WebApp just for this etc..

**Comment by EricDahlvang** [comment]
The SDK team discussed this, and determined we will not support this internally.
