### ISSUE TITLE
[MCS-DE-GO] Unknown Intent not triggering in Prompt Actions (Ask a question)

### ISSUE THREAD

**Issue by goergenj** [microsoft/botbuilder-dotnet#5071]
Whenever we set any Prompt Action with "allow interruptions" the triggers of the dialogs which have benn confirguren work except the "Unknown Intent" trigger.

Please enable that also the "Unknown Intent" triggers an interruption.

@joaollq @goergenj @sgellock @benbrown @bindsi

**Comment by garypretty** [comment]
@EricDahlvang @mrivera-ms could you please take a look into this issue.  No implementation changes right now, I would just like to understand if the above is by design or not. Even if not, it feels like making this change could have unintended consequences on previously implemented bots, so we need to be careful how we proceed.

**Comment by mrivera-ms** [comment]
@boydc2014, could you please comment on this?

**Comment by boydc2014** [comment]
> @boydc2014, could you please comment on this?

Looks like it's by design, but will double confirm and report back soon.

**Comment by mrivera-ms** [comment]
@boydc2014, could you please comment on this? Per @garypretty, we are not to make implementation changes right now.

**Comment by Stevenic** [comment]
This behavior is **BY DESIGN.** The "Unknown Intent" trigger ONLY fires if the bot is not actively engaged in a conversation with the user. If you're in a prompt you're having a conversation with the user.  If we let the "Unknown Intent" trigger fire then every single turn would result in an interruption and you would never make it past a prompt without doing extra work.

If you truly want to do something on every turn before your prompt runs then you can register an Intent trigger that listens for the "None" intent. Just be careful because as I said you can easily get stuck within a prompt.  To avoid getting stuck you should use a `SetProperty` action to set "turn.interrupted" = false. This should at least give the prompt a chance to process the utterance (note this didn't work until we fixed a recent bug so you'll probably want to wait until the upcoming release of composer that's based on the R13 runtime.

Can I ask what you're trying to do as there may be an easier way of doing it?

**Comment by goergenj** [comment]
@Stevenic We use the "None"-Intent currently as the "Unknown" does not work. For us this is the fallback, for cases where we could not validate an input and need to present interruption data, e.g. from QnAMaker results or similar, as a fall-back instead of just saying "Sorry, I did not understand" which makes the Conversation much more engaging and flexible.
I don't agree with your comment that this would be too instable based on the "Unknown"-Intent as it works already with None and you have options to add validation rules which will be a higher priority anyway and also set rules on when Interruptions are allowed. Further you can add properties within "Unknown" which can be used to control, if elements in this trigger are skipped or not.
Also, in my opinion, it would be easy to add an option to the properties where you could turn "Unknown"-Interruption on and off as well. We have also tested this design in our older FlowDesigner tooling quite well in a couple of projects.

Using the None-Intent has a couple of disadvantages; you need to have LUIS active plus you need to have a very well trained None-Intent that triggers in the right cases. Other than the "Unknown" it does not handle "all else" but only things where "None"-Intent is the topscoring Intent so it's only second best as a fall-back.

If you want we can do a session where I walk you through our design and what we are doing. If you are interested get in touch vie e-Mail or Teams using "jan.goergen@microsoft.com".

**Comment by QaisAlkhateeb** [comment]
As a chatbot developer I need to mention an issue if the Bot will Always Interrupting the Prompts if it's Unkown, this will cause us an issues in cases that we prompt user to enter free text (like feedback, ticket number, some data checked by backend code) in this scenarios the chatbot will always interrupt and fallback to Unkown

**Comment by goergenj** [comment]
@QaisAlkhateeb Why not make this configurable to allow more flexibility. Instead only having the option to select "true" and "false" for interruption and some expressions, add the selection "Unknown Interruption" "ture/false" to the Composer Action.

**Comment by tamasschmolcz** [comment]
Having such an option @georgenj mentioned would really a such an plus and keep the control.

**Comment by mrivera-ms** [comment]
@goergenj, thank you for submitting this issue. We are not taking feature requests at this time for this feature. We will keep this in mind for future releases.

**Comment by goergenj** [comment]
@mrivera-ms  This is your response after this has been open for more than a year!?

**Comment by mrivera-ms** [comment]
Unfortunately, this is the only response we can offer at this time. As indicated above, the behavior you describe is by design and we are not working on new features for this library. If you wish to discuss further, we can do it offline.
