### ISSUE TITLE
Unable to link bot built using bot framework composer with Twilio

### ISSUE THREAD

**Issue by aksh-h** [microsoft/botbuilder-dotnet#5094]
We are building a bot using Bot Framework Composer and able to test it using Bot Emulator or Web Chat.
After publishing the app we followed the steps given in the [doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-4.0) to connect and run it through to Twilio, but it didn't work.

Same issue has been raised in [stackoverflow](https://stackoverflow.com/questions/65629466/unable-to-link-the-bot-built-from-bot-composer-with-twilio)
If there are anyway to register published bot with Twilio, that would help us a lot.

Thanks!

**Comment by v-kydela** [comment]
Thank you for the report, @aksh-h. I would like to help and I have a few questions.

1. Are you using the Twilio adapter or the Twilio connector?
2. What didn't work?
3. What are the repro steps?

Please provide screenshots where applicable

**Comment by ashwin9627** [comment]
Hi @v-kydela, 
1.We are using Twilio connector for integrating bot and Twilio.
2.We are getting 400 status.
3.We have followed the same steps as given in this [https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-4.0](url)
![issue1](https://user-images.githubusercontent.com/45839692/104868564-b18a4880-5969-11eb-8e45-3d65db2deefa.png)

![issue1](https://user-images.githubusercontent.com/45839692/104868534-9d464b80-5969-11eb-82f3-8a269a1ea41a.png)

**Comment by v-kydela** [comment]
@ashwin9627 - That doesn't answer questions 2 and 3. You've explained that you're getting an error, but you haven't explained what you're doing to produce that error. Just knowing that you've followed the instructions to set up the bot doesn't tell me at what point in those steps you're encountering the error, and it also doesn't help me reproduce the error.

You say you're using the Twilio connector, but I can see in the screenshot that Twilio is trying to send messages to your bot's messaging endpoint instead of to the Twilio connector. That certainly makes it look like you're trying to use the Twilio adapter and not the Twilio connector. I wonder if that's the problem.

I'll go ahead and close this here so it can be addressed on Stack Overflow.

**Comment by hsachinraj** [comment]
I am trying the same - I am using Twilio Adapter to connect to the bot. Steps followed:

1. In Bot Composer - **project settings** - include **custom runtime**
2. added a new controller for twilio (followed the instructions given [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-twilio?view=azure-bot-service-4.0#connect-a-bot-to-twilio-using-the-twilio-adapter))
3. deployed the bot to Azure App Service
4. Updated the App Service configuration with twilio information (account SID, auth token, from Number and validation URL)
5. Registered Twilio channel in the **Bot Channel Registration**
6. Update Twilio WhatsApp Sender profile to add a webhook (pointing to https://mybotapp/api/twilio)

Now when I test the bot in the **Web chat**, it works properly. However when I try it on Twilio side using WhatsApp, I am getting a 500 Error

Appreciate if someone can help
