### ISSUE TITLE
Set locale on conversation level

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#5101]
This is related to #4983, as that one was closed, but did not fix what I was actually after.

I want to be able to set the locale on conversation level which would override the turn locale.
Often the locale is only determined after login and getting user preferences whereby the turn locale is already determined by the client. If the conversation.locale would take presedence over the turn.locale this would make for a flexible system. Also users could easily change their language during a conversation.

**Comment by carlosscastro** [comment]
Hello @cxbuilders, thanks for reporting. Agreed that changing language and using actually any memory scope of your choosing for locale precedence should be supported. I did a bit of investigation on this:

- First, this should be possible with the current version. I built a small prototype of language switching to attach to this bug, and to my surprise turn.locale was not being honored. I'll debug it a bit more and attach it here today anyways so me and other engineers can debug. 
- The prototype is still a bit clunky because there is one thing that we don't have in composer right now, which is the ability to add an action before the turn starts, and after the turn is done. We're still thinking about this so it's more of a longer term thing.

Sending an update in a bit after further debugging.

**Comment by cxbuilders** [comment]
@carlosscastro For the pre and post activity triggers I submitted a request quite some time ago: #4928

Also I think it would be good that if eg user.locale is set it automatically overrides the turn.locale without the need to change the turn.locale for each turn, same would go for conversation.locale

**Comment by carlosscastro** [comment]
Completely agreed on the pre and post triggers. We're working on that.

Regarding the locale precedence, it is fair to say that the business logic varies, even though personally I kind of like this precedence to compute the effective locale that goes into turn.locale.

- conversation.locale
- user.locale
- activity.locale
- default locale

The logic being, the default locale is hit or miss, the activity locale is a good first approach because that locale information can come from the client which likely interacted with the user (i.e. teams, browser, etc). The user locale is more specific, in that it is an explicit choice of the user on how to interact with the bot in general. The conversation locale is something I'd ask to change when I'm having a conversation in spanish with my family from argentina. However, all of this framing changes completely if you think about an airport kiosk or other scenarios where the priorities may change.

But yes, having a reasonable default and easy setting of precedence is in our priority list.

**Comment by carlosscastro** [comment]
Going back to the bug -- I tried creating the following bot:

- Unknown intent: Echo bot behavior
- 'english': sets conversation.locale to en-us
- 'spanish': sets conversation.locale to es-ar
- Activity trigger: on activity received, executes once to set `turn.locale = conversation.locale ?? turn.activity.locale`. Then calls repeat with processed activity false and sets a flag so it executes only once, and the intent triggers catch the repeat.

Unfortunately, the runtime is not honoring the turn.locale change. @cosmicshuai the test you linked in your PR https://github.com/microsoft/botbuilder-dotnet/pull/5019 works for me, however this simple bot I just put together does not seem to honor the turn locale when I change it. Moreover turn.locale comes out empty in the debug traces I left (see attached bot assets) Could you please take a look at the attached bot, @cosmicshuai ? To repro: just say hi with locale en-us, then say spanish and the bot keeps answering in english. conv locale is es-ar but turn.locale shows up empty. Am I missing something? Why is turn.locale coming out empty? Tried with the R11 release of composer.

[languageSwitchRepro.zip](https://github.com/microsoft/botbuilder-dotnet/files/5908801/languageSwitchRepro.zip)

**Comment by cosmicshuai** [comment]
Sure, I will look into the bot and see what caused turn.locale not working.

**Comment by cxbuilders** [comment]
@carlosscastro Completely agree with the presedence. 

Have been thinking about user vs conversation whereby a bot could respond to different users in their own language in one conversation, but that really defies the whole purpose of a conversation where you expect everyone in it to understand the rest.

So your presedence list would be best imo

**Comment by cosmicshuai** [comment]
Hi @cxbuilders
I created a PR for this senario. Adding conversation PR as the highest priority for determining the locale. 
You can check the bot sample to see whether it is the way you want.

**Comment by cxbuilders** [comment]
@cosmicshuai Thanks. I browsed through the code and the comment and I am wondering are you now overwriting the turn.locale on any incoming activity if the conversation.locale is set? I would expect the turn.locale to be a fixed property and a possible candidate for the final locale that is used, when conversation.locale is set it will use conversation.lcoale for the final locale, same for user.locale. This would give you the option to still check on the incoming turn.locale  and be sure that is not altered.

**Comment by carlosscastro** [comment]
Thanks for the work and investigation @cosmicshuai, glad you found those areas where we were not honoring turn.locale. 

Thanks @cxbuilders for the comments and thoughts, I'll spend some time on this today and tomorrow and update.

**Comment by carlosscastro** [comment]
Reopening this one since the code to support this is now in the main branch, however I need to provide @cxbuilders with a sample on how to have conversation and user level locale preferences and manage the priority in a custom way. @cxbuilders - I'll work on this sample tomorrow and attach it here to close the loop.

**Comment by daveta** [comment]
@carlosscastro : Are there any updates here?

**Comment by carlosscastro** [comment]
Yup, here is a minimal example: that shows language selection and storage in conversation state: https://github.com/microsoft/botbuilder-dotnet/blob/main/tests/Microsoft.Bot.Builder.Dialogs.Adaptive.Tests/Tests/MultiLanguageGeneratorTests/SwitchLanguageConversation.test.dialog

Happy to provide help if anybody is trying this out, just tag me. In the next months we plan to move this further forward and have it be more automatic but for now this gives full flexibility and allows us to know how our users use it before implementing features.
