### ISSUE TITLE
Resolving Locale for different countries

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botbuilder-dotnet#5108]
I ran a test whereby I created an additional language Dutch (Netherlands) -> nl-nl When setting the locale in emulator to nl-be it responded it the default language en-us

So some questions come to mind;
- Should the locale not be resolved to match the language if there is no exact locale match

I then expected I needed to use Dutch without a country -> nl , however it then gives a warning that the locale nl is not supported by Luis.

How am I supposed to just provide any user their language independent of their country, so portugese to Portugal & Brazil, dutch to the netherlands & belgium without Luis complaining? If Luis needs to have nl-nl to function then I do need nl-be to resolve to that as well, I mean it's the same language. Even better would be to just be able to set only languages without the country. 

I have now a bot with 6 languages and I do not want to add any country that might use that language as a seperate locale and make a copy of that.

**Comment by cwhitten** [comment]
Hi @cxbuilders. Transferring to the SDK project for triage and discussion

**Comment by LeeParrishMSFT** [comment]
@luhan2017  Can you take a look at this, or suggest someone who can?

**Comment by boydc2014** [comment]
The LanguagePolicy in SDK is designed to customzied the fallback order of languages, i'm expecting you can use this policy to create a policy like

nl-be => nl-nl => en-us,

so that you can bypass the issue that LUIS doesn't support nl, and you don't have to create both nl-nl and nl-be. You can only have nl-nl, that would be good.

**Comment by srinaath** [comment]
@boydc2014 Do we have a sample for this scenario?

**Comment by Danieladu** [comment]
[EchoBot-0.zip](https://github.com/microsoft/botbuilder-dotnet/files/6000058/EchoBot-0.zip)
hi @srinaath  I have upload a sample to show how to custom the language Policy by changing the runtime code.
The key code change is here:
```
            var languagePolicy = new LanguagePolicy();
            languagePolicy["nl"] = new string[] { "nl-nl", "nl-be", "nl" };   // reerite the policy for 'nl' to 'nl-nl', 'nl-be' and  'nl'
            var rootFile = resourceExplorer.GetResource(rootDialogFile);
            var rootDialog = resourceExplorer.LoadType<Dialog>(rootFile);
            this.dialogManager = new DialogManager(rootDialog)
                                .UseResourceExplorer(resourceExplorer)
                                .UseLanguageGeneration()
                                .UseLanguagePolicy(languagePolicy); // apply it
```

Maybe in the next step Composer would enable the feature to customize the language policy.

**Comment by boydc2014** [comment]
@srinaath Hongyang uploaded a sample above and called out the key changes here. 

@cxbuilders please refer to the sample above that shows how to create a customized language policy that can enable you to route your lg from language to language.  For now, you have to modify the code ejected to do so, in the future, we are considering exposing this policy object in settings, so that you don't have to touch code for tasks like this. 

Let us know if you get any questions

**Comment by cxbuilders** [comment]
@Danieladu thanks for the sample, that works. For now all good and indeed having this in the settings would complete things nicely 😊

**Comment by munozemilio** [comment]
Hi @cxbuilders seems this issue can be closed now. Feel free to reopen if needed
