### ISSUE TITLE
add abs and float.Epsilon in adaptive expression

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-dotnet#5114]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

When submitting this pr https://github.com/microsoft/BotFramework-Composer/pull/5575/files, I found we lack these two in adaptive expression

**Describe the solution you'd like**

Add them like C# https://docs.microsoft.com/en-us/dotnet/api/system.math.abs?view=net-5.0, https://docs.microsoft.com/en-us/dotnet/api/system.double.epsilon?view=net-5.0

**Describe alternatives you've considered**

**Additional context**

**Comment by Danieladu** [comment]
Thanks for the feebback.
For the Math function, 'abs', LG team decide to add some commonly used math functions, including:
`abs`, `sqrt` and `log`

For the mathematical constants, we recommend user restore their own constant value in memory with "setProperty" in Adaptive Dialog or standalone template.
Because:
- Adaptive-expression provides the pure function logic only, would not pollute the memory storage.
- Some constants themselves are ambiguous. `float.Epsilon` is `1.401298E-45` but `Double.Epsilon` is `4.94065645841247E-324`.

Feedback is welcome.

**Comment by xieofxie** [comment]
Hmm.. I check the code https://github.com/microsoft/botbuilder-dotnet/blob/183166160e5110cb688f81a842d4744140b3ae9b/libraries/AdaptiveExpressions/BuiltinFunctions/Equal.cs#L49 and since we convert them to double, wouldn't it be better to use Double.Epsilon? (this will be a breaking change though)

**Comment by Danieladu** [comment]
> Hmm.. I check the code
> 
> https://github.com/microsoft/botbuilder-dotnet/blob/183166160e5110cb688f81a842d4744140b3ae9b/libraries/AdaptiveExpressions/BuiltinFunctions/Equal.cs#L49
> 
> and since we convert them to double, wouldn't it be better to use Double.Epsilon? (this will be a breaking change though)

That's a good suggestion. We would investigate it and consider adopting it.
