### ISSUE TITLE
Support referencing LG templates by name in test scripts

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botbuilder-dotnet#5120]
**Is your feature request related to a problem? Please describe.**
When writing out declarative test scripts, it is time consuming to include all the hardcoded variations for an LG response and will be difficult to maintain as the LG templates change over time. I would like to be able to provide the LG template name in the assert step so that I do not have to include all the variations manually and I don't have to update the tests for every template change. 

This is the current format in the test script for an LG response with multiple variations:
```
    {
      "$kind": "Microsoft.Test.UserSays",
      "text": "create a meeting"
    },
    {
      "$kind": "Microsoft.Test.AssertReplyOneOf",
      "text": [
        "What is the title of the meeting?",
        "What is the title?",
        "What is the meeting about?",
        "What do you want to add as a title?"
      ]
    },
```

I would like something like this (with whatever syntax makes sense):
```
    {
      "$kind": "Microsoft.Test.UserSays",
      "text": "create a meeting"
    },
    {
      "$kind": "Microsoft.Test.AssertReplyOneOf",
      "text": "${TitlePrompt()}"
    },
``` 

Or like this:
```
    {
      "$kind": "Microsoft.Test.UserSays",
      "text": "create a meeting"
    },
    {
      "$kind": "Microsoft.Test.AssertReplyOneOf",
      "LGTemplate": "TitlePrompt"
    },
```

**Comment by chrimc62** [comment]
I love this idea--it solves a real pain point in an elegant way in combination with randomseed/randomvalue.  

We could just make text so that you can specify a normal text string, i.e. something like "Would you like a ${promotion(1)} to your ${orderName('foo')}?".  This would require implementing an ExpandText method for LG that corresponds to ExpandTemplate where all possible expansions are generated.  There is still one edge case though--the expand all templates only corresponds to the top-level LG choices--not to expressions inside i.e, 
```
# foo
- a random number ${rand(1, 10)}
- another random number ${rand(1, 10)}
```
ExpandTemplate would generate ["a random number 3", "another random number 5"].  And if you ran again: ["a random number 9", "another random number 7"].  We can control this with randomValue/randomSeed, but I'm not sure how that would interact with ExpandTemplate especially recursively i.e., if I had a randomvalue of 4 and expanded this template:
```
# blah
- here is ${foo()}
- presenting ${foo()}
```
Would I get ["here is a random number 4", "presenting a random number 4", "here is another random number 4", "presenting another random number 4"]?  or only the first two?  @boydc2014 @Danieladu @feich-ms ?

I suspect in the test infrastructure this would also require a delegate to do the template expansion similar to what was done for memory assertions.

**Comment by feich-ms** [comment]
@chrimc62 for your question about ExpandTemplate above, I think the result would be ["here is a random number 4", "presenting a random number 4", "here is another random number 4", "presenting another random number 4"]
