### ISSUE TITLE
[Adaptive expressions] Date() method does not return date in valid format

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botbuilder-dotnet#5127]
**Is your feature request related to a problem? Please describe.**
I would like to use the date function to get the end of the current day by using this expression:

```
addMinutes(addHours(date(utcNow()), 11), 59)
```

However, I get the following error because the date method does not return a valid datetime object that can be used with the other datetime functions:

```
"Expression evaluation resulted in an error. Expression: =addMinutes(addHours(date(utcNow()), 11), 59). Error: 1/27/2021 is not standard ISO format."
```

**Describe the solution you'd like**
I think the date method should return a valid timestamp with 00:00:00 for the time rather than as a display method. This would align more with System.DateTime and be more useful since FormatDateTime can already be used to get a display string for a date in a particular format.

**Comment by mrivera-ms** [comment]
@boydc2014, could you please triage this issue? If accepted, please add milestone. Thank you.

**Comment by cosmicshuai** [comment]
Hi @lauren-mills, as my understanding, you were trying to add some minutes and hours to the starting of current date. 
I have two suggested solution for this, 

1.  use startOfDay instead of date function.
   `addMinutes(addHours(startOfDay(utcNow()), 11), 59)`  this will return ` 2021-02-03T11:59:00.000Z` as my current date is Feb 3rd today
2. wrap the result of date with a formatDateTime function
   `addMinutes(addHours(formatDateTime(date(utcNow())), 11), 59)`  this will  also return ` 2021-02-03T11:59:00.000Z` .

Hope these two solutions would help you. If you have further question, please let me know.
