### ISSUE TITLE
SkillHandler.ProcessActivityAsync Should allow more activity types to be sent to a bot OnTurn/Handler 

### ISSUE THREAD

**Issue by JeffCordes** [microsoft/botbuilder-dotnet#5132]
**Is your feature request related to a problem? Please describe.**
We are upgrading one of our clients large enterprise bots to the skills framework.  We have discovered that when a skill sends Activities back to our root bot only events and endOfConversation are sent to our event handler.  All other activities are sent directly to the user with turnContext.SendActivityAsync from the framework itself..

This is limiting because message activities returned then bypass important pieces of logic in our system for transcript logging, analytics, livechat handoff, etc.  In may cases we use channel data to store information about the channel, and make decisions how exactly how/what the final message is sent to the user.   The SkillHandler sending these to the user without giving us the ability to look at them in code is problematic.

**Describe the solution you'd like**
I would like to see the skill handler switch case [here](https://github.com/microsoft/botbuilder-dotnet/blob/152ad50ac31ac45c663622298e1cc6036346c3f6/libraries/Microsoft.Bot.Builder/Skills/SkillHandler.cs#L235) apply all activity types to the turn context, then send them to the bot's OnTurn.

A nice to have would be a skill version of [ActivityHandler.cs](https://github.com/Microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/ActivityHandler.cs) that can then automatically forward the other ActivityTypes that typically need to be forwarded to the user, but allow a developer to override a virtual method add their own logic for processing and sending the Activity.

**Describe alternatives you've considered**
For a few things we are sending events from the skills to the root bot after sending other activity types.  IT seems like we are sending redundant messages to do so since the first activity sent has a property with the same information.

We are considering replacing the entire skill controller, and skillhandler with our own.  But we would prefer to keep the framework security implementation in place.

We created a system of eventHubs, functions, and databases for transcript logging since we can not get all messages in the rootbot.  (all skills write to one eventhub, and a function commits all that data to cosmos, then datafactory does ETL and joins them all back together)

**Additional context**
Thanks for your time,  Let me know if there is something I am missing here.

**Comment by gabog** [comment]
Hi @JeffCordes, would using a custom middleware solve your issue? For logging purposes, skill responses should be processed by middleware and you can catch them and apply your logic there, the only thing to consider is that you need to ignore the ContinueConversation events (which are internally used so the bothost can register OnSendActivity handlers).

[Here](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/81.skills-skilldialog/DialogRootBot/Middleware/LoggerMiddleware.cs) is a simple example for simple logging middleware that excludes ContinueConversation messages but logs incoming user activities and outgoing ones (independently of them coming from a skill or the root bot)

Let me know if this helps with your scenario.

**Comment by JeffCordes** [comment]
Hi @gabog ,

Using middleware in exactly what I would like to be able to do, however...

In the SkillHandler.cs you would need to call _bot.OnTurnAsync().. to start the execution of any middleware and activity handlers for that IBot.  In the bot callback defined that is only done for "event" and "endOfConversation" Activities.  The default in the switch/case statement is to bypass any developer defined middleware and logic.  [source](https://github.com/microsoft/botbuilder-dotnet/blob/799022e7fa16d3062a0f2b10d019df5cea43a81c/libraries/Microsoft.Bot.Builder/Skills/SkillHandler.cs#L246)

So the underlying issues is that in the skillHandler is not sending certain message types to the middleware I have written.

**Comment by gabog** [comment]
Not really, all the messages will go through the middleware. 

This is what happens when an activity is received by SkillHandler.
1. [ContinueConversation](https://github.com/microsoft/botbuilder-dotnet/blob/799022e7fa16d3062a0f2b10d019df5cea43a81c/libraries/Microsoft.Bot.Builder/Skills/SkillHandler.cs#L252) will be called
2. The processing pipeline will get executed and you'll see a ContinueConversation event in your middlewares that you should ignore (what I point out in [this](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/81.skills-skilldialog/DialogRootBot/Middleware/LoggerMiddleware.cs#L31) sample).
3. Step 2 will also help register your OnSendActivity handler ([this one](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/81.skills-skilldialog/DialogRootBot/Middleware/LoggerMiddleware.cs#L38))
4. After all this happens, then the [skill handler callback](https://github.com/microsoft/botbuilder-dotnet/blob/799022e7fa16d3062a0f2b10d019df5cea43a81c/libraries/Microsoft.Bot.Builder/Skills/SkillHandler.cs#L229) will get executed.

Here is where there's a branch in the logic:
  4a. If the activity is of type Event or EndOfConversation, then the bot's OnTurnAsync will be called and the activity is routed to your bot.  If your bot sends anything at this point, you'll see it in your middlewares ([OutgoingHandler](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/81.skills-skilldialog/DialogRootBot/Middleware/LoggerMiddleware.cs#L44) will be called and you can log or do anything with the activity before it goes out).

  4b. If the activity is anything else, then it will be sent straight back to the caller, but since the middleware outgoing handler has been registered as part of step 3, then you will also see the outgoing message in [OutgoingHandler](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/81.skills-skilldialog/DialogRootBot/Middleware/LoggerMiddleware.cs#L44)  and you can log your message here.

Makes sense?

**Comment by gabog** [comment]
Also, in case it helps, I think there's a bug in the sample, I think [this](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/81.skills-skilldialog/DialogRootBot/Middleware/LoggerMiddleware.cs#L31) line should be really:

```
if (!(turnContext.Activity.Type == ActivityTypes.Event && turnContext.Activity.Name == "ContinueConversation"))
```

**Comment by JeffCordes** [comment]
Ok, So I can work through the way this sample is running and see the activity sent from the skill on the outputHandler.  However, it seems unfortunate to have to see this through an output event and not through middleware and ActivityHandler/IBot.

We have made some similar workflows of having a controller and adapter to receive activities from another source, most commonly Live chat handoff integrations.  When messages are posted to the API and we know know what conversation they should go to we use:

ConversationReference.GetContinuationActivity();

Then we merge the data from the incoming activity and the continuation activity simmilar to what you do [here](https://github.com/microsoft/botbuilder-dotnet/blob/799022e7fa16d3062a0f2b10d019df5cea43a81c/libraries/Microsoft.Bot.Builder/Skills/SkillHandler.cs#L172)

Then we call await _adapter.ProcessActivity()  instead or _adatper.ContinueConvesationAsync()

In doing so the full activity Payload instead of just a blank ContinueConversation event goes through the middleware set and Ibot associated to the adapter.

Another key to making that successful is that each controller gets its own adapter, and therefore its own middleware set.  In virtually all cases I have encountered the traffic coming in from api/messages, api/skill, and api/liveagent never need the same exact middleware set of logic.  So in Startup.cs we ensure the Ibot for api/messges resolves the adapter with its middleware set, and the SkillHandler resolves a separate adapter for its middleware set.  I have seen that setup missing in most of the microsoft samples where everything shares one adapter.  I it is more common in enterprise applications to have one adapter per controller than merging them together.

I guess at the end of the day my original request still stands.  I would love to see a way to process all activities that come in through api/skills with a middleware set and Ibot.  The proposed solution of using OnSendActivity() changes the order of operation, limits the re-usability or existing middleware for api/skills without refactoring, and makes the workflow of messages entering on api/skills greatly different that those on api/messages.  I guess I do not see a reason to why api/messages and api/skill should behave so differently.

That said, my world is not on fire here, we can code around the limitations.  But I would love to see this be a feature request in a future build.

**Comment by daveta** [comment]
@mrivera-ms : Should we slot this to a future milestone?

**Comment by daveta** [comment]
@gabog is evaluating for future release..

**Comment by tracyboehrer** [comment]
We will not be addressing at the moment.
