### ISSUE TITLE
Operation returned an invalid status code 'NotFound' when calling TeamsOperations.FetchChannelListWithHttpMessagesAsync

### ISSUE THREAD

**Issue by ipraveenMS** [microsoft/botbuilder-dotnet#5191]
#### What project is affected?
latest BF 
#### What language is this in?
C#
#### What happens?
Operation returned an invalid status code 'NotFound'
   at Microsoft.Bot.Connector.Teams.TeamsOperations.GetResponseAsync[T](String url, Boolean shouldTrace, String invocationId, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.Teams.TeamsOperations.FetchChannelListWithHttpMessagesAsync(String teamId, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.Teams.TeamsOperationsExtensions.FetchChannelListAsync(ITeamsOperations operations, String teamId, CancellationToken cancellationToken)
   at GetChannelList(CancellationToken cancellationToken) in C:\...\TeamsContext\TeamsContext.ChannelExtensions.cs:line 46

#### What are the steps to reproduce this issue?
Called the above function to retrieve some teams info and hit this error.
#### What were you expecting to happen?
Success.
#### Can you share any logs, error output, etc.?
Above.
Also 
This is the post from previous UpdateActivity that was successful (from ngrok)
POST /api/skills/v3/conversations/19:74344caa321c411591735f7122d017ac@thread.tacv2;messageid=1611212147390-l_Icm-msteams-skillconvo/activities/1611212147390   
200 OK
This corresponds to the failure (above)
GET /api/skills/v3/teams/19:74344caa321c411591735f7122d017ac@thread.tacv2/conversations    
404 Not Found

**Comment by Virtual-Josh** [comment]
For a bit of context this is a known issue. The `TeamsInfo` class doesn't currently work with skills. @gabog we should look into fixing this during the next cycle.

**Comment by ipraveenMS** [comment]
@Virtual-Josh @gabog what is the timeline for the fix? What is the workaround till then to unblock ourselves? This worked in the previous versions of BF code we have so this is broken code.

**Comment by Virtual-Josh** [comment]
@ipraveenMS as far as I'm aware the `TeamsInfo` class has never worked with skills in any version of the SDK. If you have an example of a version of the SDK where it does work can you tell us what version so we can take a look. The reason it doesn't work is due to the delegated turn context not having the required pieces to use `TeamsInfo`. This means there aren't any simple workarounds currently available. 

If you're determined to do a work around I have one idea which seems reasonable, but I have not tested to confirm it works. You could setup some logic so the skill calls back to the parent when it wants to use the methods in `TeamsInfo` and have the parent forward the data back. If you wanted to follow this path then the parent would need to be installed in Teams so it would have access to data. 

As for timelines that's a good question. We are currently wrapping up our current cycle and will start planning work for our next cycle imminently. It's possible that this gets picked up in our next cycle, but I'm not in a position to tell you it will definitely be in the next release.

**Comment by EricDahlvang** [comment]
ChannelServiceController needs to have the 'v3/teams/' endpoints from TeamsOperations.

**Comment by clearab** [comment]
We've been tracking the work to implement support for this here: https://github.com/microsoft/botbuilder-dotnet/issues/4931

**Comment by clearab** [comment]
I'm going to go ahead and close this as a duplicate, but thank you for calling this out. For now, @Virtual-Josh's answer above it correct, the TeamsInfo helper methods will not work from a skill. If you need to work around this limitation, you'd need to consumer bot send the request, and then pass the results back to the skill.

**Comment by ipraveenMS** [comment]
>>If you're determined to do a work around I have one idea which seems reasonable, but I have not tested to confirm it >>works. You could setup some logic so the skill calls back to the parent when it wants to use the methods in TeamsInfo >>and have the parent forward the data back. If you wanted to follow this path then the parent would need to be >>installed in Teams so it would have access to data.

@clearab @Virtual-Josh can you give more details about the workaround? We have parent installed in teams.

How to handle it again in the skill after the parent forward the data back? How to redirect from parent to skill (example would be great)
