### ISSUE TITLE
Guidance on Storage for State

### ISSUE THREAD

**Issue by gabog** [Microsoft/botbuilder-dotnet#531]
Hello @cleemullins , is there any guidance one when to use Azure Tables, Azure Blobs or DocumentDB for persistent bot state? 
What needs to be considered and it what circumstances is one preferred to the other?
Also, is there any guidance on how to handle old state? As it is right now, old sessions will be stored indefinitely, what would be a "clean way" of removing old data in each case?

Thanks

**Comment by gabog** [comment]
Hi, from looking at what gets stored in state, I don't see a last modified field in the data (unless I'm missing something). It would nice to add that to the state providers so we can build tools to delete stale state that hasn't been used for a while.

**Comment by drub0y** [comment]
Yes, it's true there is nothing in the bot state abstraction that represents the last modified (right now), but if you consider something like the Azure Table Storage implementation, each row that's stored there has an implicit timestamp column in the backing store so you can always use that. Blob Storage and File System both have a concept of last modified, etc. Knowing that, you could go against those backing stores directly to do cleanup.

There has also been some discussion of auto-cleaning up of conversation state based on the conversation ending, so if you think that would be valuable please let us know.

Finally, I should point out that providing an abstraction for _querying_ state storage is not a goal of the abstraction because each backing storage implementation is going to have drastically different capabilities for what kind of querying they might be able to support and trying to build an abstraction for that would certainly come up short. That said, I'm of the opinion that the specific providers could/should offer their own specific APIs to enable this.

**Comment by gabog** [comment]
Thanks, if I use CosmosDB, the timestamp is not there either, I haven't used FileSystem but I think those attributes can be altered unintentionally if you move or copy the files. My preference would be to have the timestamp as part if the data itself in all the providers to make it more consistent across the board.

**Comment by Stevenic** [comment]
Answering this in a little different way... I think ideally you'd use a Redis based storage provider for your conversation state and then something more durable like Tables or CosmosDB for user state.  

The reason I suggest Redis is that a) it's has significantly higher throughput (20k RPS for Tables vs 180k RPS for Redis), and b) you can set individual rows to automatically expire after a period of time.  Redis is more volatile than other storage mechanisms but for conversation state tracking I think that's fine.  We don't enforce concurrency anyway so you should always be prepared for your state to get clobbered or disappear.

For user state I think you can choose whichever storage construct suits your needs. From a cost/performance perspective Tables or Blobs would be your best choice. But if you need to run other queries against your user data then CosmosDB might be the best choice.

To be honest... With user state I'm not sure I would actually use our state management stuff.  Given that we don't do any concurrency checks your playing with fire if your storing anything more then simple preferences, the users name, or the last thing they ordered.  You should probably **never** store critical business data using our state constructs.

**Comment by yochay** [comment]
@Kaiqb please create a doc issue for tracking. 

POR (for now): Cosmos and inMemory and all other providers as samples 

@vishwacsena for vetting plan with partners

**Comment by Kaiqb** [comment]
@yochay added to VSTS for tracking doc issue.

**Comment by Kaiqb** [comment]
@Stevenic - the guidance you provided was back in May. Is it still accurate with the state changes that were made since then?

**Comment by Kaiqb** [comment]
Added note from Steve to the state topic.
