### ISSUE TITLE
CoreBotAdapter is missing EoC logic (Skill bot)

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-dotnet#5335]
We should check the adapter code in the runtime but it is important to note that we need additional logic to handle error that may happen in skills. If a bot is a skill consumer we should take a look at the error handling logic in AdapterWithErrorHandle. If the bot is running as a skill, then we should make sure we support the logic that is implemented in SkillAdapterWithErrorHandler

See https://github.com/microsoft/botframework-components/issues/689

**Comment by tracyboehrer** [comment]
This is probably the same as #5330

**Comment by johnataylor** [comment]
Yes it think this is the same issue. Closing for now at least.

**Comment by tracyboehrer** [comment]
@johnataylor We kept it as two issues.  One for EoC for a skill (this issue), and the other for the root bot (which we don't have an answer for right now).

**Comment by johnataylor** [comment]
It might make things simpler if we moved some of the error handling logic into the bot implementation and out of the adapter. The adapter's error handler is really the error hander of last resort.

We need to be careful about the logic that goes into the adapter because the root adapter could be a custom adapter. We want scenarios to work with custom adapters.

The distinguishing factor between a catch all around the bot execution and the adapter's error handler is that the adapters error handler does cover the middleware, however, this might not be an issue because the ambiguous nature of middleware inherently limits what can effectively be done with it anyhow.

The advantage of handling errors within the bot's OnTurn is that more context, such as the state of the Dialog stack, is naturally available.

**Comment by johnataylor** [comment]
See preview comment. Add error handling logic to the bot.

**Comment by johnataylor** [comment]
Incidentally error handling logic should not reference global constants that are specific to a particular cloud environment such as public Azure.

**Comment by tracyboehrer** [comment]
@johnataylor Well the CoreBotAdapter is always created.  Are you proposing we apply the error handler to all adapters created, even custom ones?

**Comment by tracyboehrer** [comment]
@Nevermind.  I see your comment in the Teams thread about adding to the bot.
