### ISSUE TITLE
ConnectorClient init does not honor DelegatingHandler being passed unless UseSharedHttpClient is set to false.

### ISSUE THREAD

**Issue by RamjotSingh** [microsoft/botbuilder-dotnet#537]
```cs
 public bool UseSharedHttpClient
        {
            get { return this._originalHttpClient != null; }
            set
            {
                if (value == false)
                {
                    this.HttpClient = this._originalHttpClient;
                }
                else
                {
                    if (this._originalHttpClient == null)
                    {
                        this._originalHttpClient = this.HttpClient;
                        this.HttpClient = g_httpClient.Value;
                    }
                }
            }
        }
```

The above code replaces the HttpClient thus resulting into DelegatingHandler not being honored unless UseSharedHttpClient is set to false. And since it is by default set to true, thus making it very hard to discover this without looking deep into code and understanding the Swagger generated code pattern.

**Comment by drub0y** [comment]
To be frank... the usage of `ConnectorClient` is flawed at the moment and that flawed usage is what seems to have lead to `UseSharedHttpClient` even being added.

How is it flawed? Well, first we need to make sure we understand that `ConnectorClient` derives from `ServiceClient<T>` from the `Microsoft.Rest.ClientRuntime` SDK/NuGet package. `ServiceClient<T>` itself is just an abstraction over/around an `HttpClient`. Now, if you do not use any of the overloads of  `ServiceClient<T>`'s constructor that actually pass through a fully baked `HttpClient` each time, it's going to instantiate a new `HttpClient` instance under the covers. So, when you're using a `ServiceClient<T>` in this way, you are implicitly creating a new `HttpClient` instance each for each `ServiceClient<T>` instance. Now, there are actually two ways to remedy this:

 1. Knowing that a `ServiceClient<T>` is but a thin veil over `HttpClient` anyway, you could treat it with the same, appropriate lifetime semantics which is that it should be held onto as a singleton (or at least a per unique configuration singleton). This is, in fact, the "right way" to use this API.
 2. You should always use the `ServiceClient<T>` constructor overload that takes a fully baked `HttpClient` so that it never tries to instantiate its own. Additionally you would need to make sure to set the `disposeHttpClient` parameter to `false` (default is actually `true`) so that the instance doesn't assume ownership over the `HttpClient`.

Ok, so that's all about `ServiceClient<T>` which, as mentioned, `ConnectorClient` is a subclass of. So the flaw is that `BotFrameworkAdapter` actually instantiates a new `ConnectorClient` (thus a new `HttpClient`) on each turn when it calls its `CreatorConnectorClientAsync` either from `ProcessActivity` or `ContinueConversation`. At some point (I remember discussions going on back in Feb) the team realized this when they started running into the situation where, under sufficient enough load they were starving themselves of TCP connections (the telltale sign of the `HttpClient` anti-pattern) and apparently that's when `UseSharedHttpClient` was introduced as the solution. Now, it works, but it's obviously not the "right" solution when you consider how the underlying `ServiceClient<T>` itself is designed to be used. 

Well there's a couple phases we could go through to address different problems, but ultimately `BotFrameworkAdapter` shouldn't be `new`ing up instances of `ConnectorClient` at all otherwise there's no way to unit test it or, per this issues requires, have someone supply their own instances of `HttpClient` that are baked with some custom handlers in it or maybe just replace the entire backing implementation of `IConnectorClient` with my own thing that's not even using `ServiceClient<T>`. To do that we need to introduce a factory that `BotFrameworkAdapter` would call any time it needs one and, in that way, we can move the entire responsibility of lifetime management out of the `BotFrameworkAdapter` and into that factory... HURRAY FOR DECOUPLING! 🎉

Foundational stuff would look something like this...

```CSharp
public interface IConnectorClientFactory
{
    IConnectorClient GetConnectorClient(Uri serviceUri);
}

public sealed class ConnectorClientFactory : IConnectorClientFactory
{
    private readonly ConditionalWeakTable<Uri, IConnectorClient> _connectorClients = new ConditionalWeakTable<Uri, IConnectorClient>();
    private readonly Func<Uri, HttpClient> _httpClientFactory;

    public ConnectorClientFactory() : this(() => this.CreateDefaultHttpClient())
    {
    }

    public ConnectorClientFactory(Func<Uri, IConnectorClient> httpClientFactory)
    {
        _httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory);
    }

    public IConnectorClient GetConnectorClient(Uri serviceUri) =>
        _connectorClients.GetOrCreateValue(serviceUri, _httpClientFactory);    
}
```
Then we change `BotFrameworkAdapter` to take and use an `IConnectorClientFactory` instead of `new`ing up its own instances and all those responsibilities and problems melt away. All of this then has ripples up through configuration where I would expose some kind of new configuration API in order to allow setting the `IConnectorClientFactory`.

> NOTE: I've purposefully left out other details like setting the retry policy on the `ConnectorClient` and managing the credentials, but they fall into the same category of: not the responsibility of `BotFrameworkAdapter` and something that should be moved out and into the `IConnectorClientFactory`.

**Comment by EricDahlvang** [comment]
This issue is no longer relevant, since there is no longer a UseSharedHttpClient property and we now have an HttpClient parameter for the ConnectorClient constructor.
