### ISSUE TITLE
Dialogs.Debugging.SourceMap: SourceMap is taking too much memory when chatbot loading 

### ISSUE THREAD

**Issue by QaisAlkhateeb** [microsoft/botbuilder-dotnet#5469]
I'm using Composer Runtime in one of the bots I working on, the bot have multiple service and we have multiple dialogs (50 dialogs) to handle these services. when bot it loading it consuming too much memory, after investigation I found that SourceMap is consuming most of the memory and below simple explanation to what I did:

I tried to load the Bot without doing any change on SourceMap and here is the memory usage screenshot (3 GB):
![image](https://user-images.githubusercontent.com/25031218/114367059-b899af00-9b84-11eb-92de-fb6e241727ef.png)

then I tried to Load the Bot without using SourceMap by commenting the Add method as shown below (using latest Packages 4.12.2):
![image](https://user-images.githubusercontent.com/25031218/114366455-242f4c80-9b84-11eb-9301-2258818b5729.png)

and the memory after loading the bot (660 MB)
![image](https://user-images.githubusercontent.com/25031218/114366935-999b1d00-9b84-11eb-9342-f28dc5aaf534.png)

Can you please advise,
- Can you please explain the purpose of SourceMap ?
- Can I keep this line commented and how could this affect my Bot ? are there any better way to not use SourceMap if it does not affect the Bot ?

**Comment by carlosscastro** [comment]
Hello, thanks for reporting this! Our current release (4.13)  is already in release candidate phase but we'll make sure to fix this in the following 4.14 release. 

I would love to get us a workaround that does not require you to change the SDK, so that you don't experience this problem until we ship the fix. 

In your startup.cs, could you try adding the following line?

```csharp
DebugSupport.SourceMap = NullSourceMap.Instance;
```

Which basically will prevent the default source map to grow indefinitely by disabling the debugging module.

To answer your question about what source map is for, there is built in debug support for adaptive dialogs that is under development, and will allow to pause execution and do debugging while dialogs run. Furthermore, eventually down the road we could expose this as a visual feature in composer to enable visual debugging when under development.

**Comment by tsuwandy** [comment]
@QaisAlkhateeb, were you able to try @carlosscastro's workaround?

**Comment by QaisAlkhateeb** [comment]
I tied it on the version 4.10.3 But did not work, null exception is thrown while loading the dialogs. currently I'm working on upgrade the My Bot to the latest version to test the workaround. 

will let you know if it's work

**Comment by QaisAlkhateeb** [comment]
Dears, 

Just want to inform you that we upgraded the Bot to latest version and the workaround is working, 

Thanks for your support

**Comment by mrivera-ms** [comment]
@carlosscastro, is this issue to be resolved in R14?

**Comment by carlosscastro** [comment]
Glad to hear the workaround worked. We'll resolve this in R14 so that by default there is no such memory consumption.

**Comment by carlosscastro** [comment]
We have a candidate solution for this that will both 1) allow for debugging in development scenarios (such as in vs code or composer local run), and 2) free up the dictionary after initial load in production scenarios.

We need more time to verify this given that source map is crucial for type loading and debugging. To that end, we'll keep recommending the one-liner workaround and we are moving this to R15, our next release. Expect a PR within the next 2 weeks,
