### ISSUE TITLE
MemoryStorage cannot store private fields

### ISSUE THREAD

**Issue by SamVanheer** [Microsoft/botbuilder-dotnet#550]
When using MemoryStorage and possibly other types of storage private fields are not stored.
Even if fields are made public, some Bot Builder framework types have private fields that cannot be stored, such as DialogSet.

When storing a class that contains a DialogSet the set will not be restored with its previously added dialogs, resulting in an exception when a new dialog or prompt is started.

I assume the idea behind DialogSet is to keep a single instance in the bot instance itself that receives its state during execution, but it would be nice if we could have bot state that can store its dialogs internally.

I looked into the code behind this and it seems to be caused by the JSON conversion, which by default ignores private fields: [NewtonSoft docs](https://www.newtonsoft.com/json/help/html/SerializationGuide.htm#Objects)

Marking fields as serializable by the JSON converter would place a hard dependency on the method used to store data, so is there another way to make this work or should we store dialogs in the `IBot` implementation, and dialog state as `ConversationState`?

**Comment by drub0y** [comment]
First, purely regarding serialization, please [check out this reply that I gave on a previous issue](https://github.com/Microsoft/botbuilder-dotnet/issues/403#issuecomment-380573809) that addresses this topic. TL;DR - this is indeed "by design".

Now, specific to your question about `DialogSet`, yes any state you want to persist you need to persist (and retrieve) through the state management APIs (`GetConversationState<T>` et. al.). The dialogs themselves are implementation and not state. The state you want to persist needs to be in the form of primitive types (e.g. `int`, `string`, etc) or POCO (plain-old-clr-object) classes that follow the DCS compatibility rules I mention in the issue I linked above.

**Comment by SamVanheer** [comment]
Alright, i've set up my dialogs to create the dialog set in a no argument constructor to ensure they are always created, all state is kept as public properties. Thanks for the information.
