### ISSUE TITLE
Location Card

### ISSUE THREAD

**Issue by nimbusparis** [Microsoft/botbuilder-dotnet#551]
Is it possible to send location to user with a card? Perhaps Adaptative Cards could handle that? Can you add a sample of this feature?

**Comment by Stevenic** [comment]
Are you just wanting a card that has a map with a pin in it? You should be able to use Bing Maps to generate such a card. I've seen several bots that do this.

**Comment by nimbusparis** [comment]
In fact, i would like both way : tell the user to go to a specific location and receive from the user where he is (the user should send the location, I don't intent to get it silently).
The location card using Bing I've seen was developed for previous bot builder framework, I didn't see anything for the v4.0.
I mainly target Telegram Bot, would it be possible to develop a specific card for this kind of bot?

**Comment by Stevenic** [comment]
I'll have to re-investigate a LocationPrompt. The core issue is not every platform supports sending location to the bot but it might be ok to have a LocationPrompt that only works on select channels.  It's been a year or so since I dug into which channels support sending location and which don't. 

On the outbound side there's not many updated samples for v4 yet but they'll get there pretty quickly.

**Comment by yochay** [comment]
This is more of a question for https://stackoverflow.com/questions/tagged/botframework
