### ISSUE TITLE
AdaptiveDialog has dialogs property added in declarative schema and that property should be hidden.

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-dotnet#5566]
## Version

4.13.0

## Describe the bug

To support legacy coded dialogs we added a DialogSet property on AdaptiveDialog called **Dialogs**.  The purpose for this is for you to add existing **coded dialog** to an adaptive dialog so that they can be invoked with a **BeginDialog**.

The schema file includes the definition of Dialogs as an array of IDialogs, which means that it shows up in composer UI.  The problem is that

*   there is no way to refer to a coded "legacy" dialog by id, we need the actual object to be added to the collection.
*   Composer's UI shows all IDialogs (which includes all actions) See screen shot

Any string you put in here will attempt to resolve to a declarative dialog, which if it doesn't exist will break the bot.  If it does exist, it is duplicated with what would happen today via BeginDialog.  

## To Reproduce

1.  Go to a adaptive dialog
2.  Click on dialogs and add "x", "y", "z" 
3.  Try talking to the bot, it will fail because x, y and z don't exist.
4.  Try selecting a dialog, you will see all **actions** listed as dialogs.

## Expected behavior

We should remove dialogs property from the .schema file.

## Screenshots

![](https://user-images.githubusercontent.com/17789481/117046496-9ac3f380-acc5-11eb-8199-f65c58213f5e.png)

**Comment by sgellock** [comment]
Shiproom - investigate but candidate for moving out to R14.  @cwhitten to investigate

**Comment by sgellock** [comment]
Shiproom - moving out to R14

**Comment by cwhitten** [comment]
@tomlm I have some thoughts here.

> To support legacy coded dialogs we added a DialogSet property on AdaptiveDialog called Dialogs.  The purpose for this is for you to add existing coded dialog to an adaptive dialog so that they can be invoked with a BeginDialog.

This is _super_ confusing in the authoring application. In order to call a coded dialog, you need to first have knowledge of this coded dialog's existence and then manually add it to this funky thing called a DialogSet, and then go back to the call-site and wire up the BeginDialog action. This needs to happen for evert Adaptive Dialog that wishes to call a particular coded dialog. It seems broken to me, or at the least forcing implementation details on the user.

> there is no way to refer to a coded "legacy" dialog by id, we need the actual object to be added to the collection.

Why isn't this possible? Can we not adjust this mechanism in the SDK to not be so coupled to declarative dialogs?

Lastly, and more important to this particular ticket:

> We should remove dialogs property from the .schema file.

This would mean that DialogSet is no longer author-able in Composer, thus removing the legacy support for coded dialogs at all, right? Am I confused here?

**Comment by cwhitten** [comment]
Update: spoke with Tom - need to revisit in R14

**Comment by cleemullins** [comment]
via @cwhitten 

> I agree it's pretty confusing and provide a rough experience. hiding fields on a component is really simple. All you should need to do is add dialogs to the list here: botbuilder-dotnet/Microsoft.AdaptiveDialog.uischema at main · microsoft/botbuilder-dotnet (github.com)

@tracyboehrer This looks like a great first Adaptive issue for @LeeParrishMSFT
