### ISSUE TITLE
Twilio Adapter response to WhatsApp message will not work due to wrong syntax of From field

### ISSUE THREAD

**Issue by Clooney24** [microsoft/botbuilder-dotnet#5569]
## Version
4.13.1

## Describe the bug
Twilio Adapter response to WhatsApp message will not work due to wrong from-syntax. Twilio will answer with:

> From(+4915735xxxxxx) and To(whatsapp:+491725xxxxxx) addresses should be of the same channel.
> https://www.twilio.com/docs/errors/21910

Reason is that in From the prefix "whatsapp:" is missing.

## To Reproduce
Process a message coming from Twilio WhatsApp number

## Expected behavior
The value of that From field should contain that "whatsapp:" prefix. To achieve this in TwilioHelper.ActivityToTwilio messageOptions.From should be set with activity.From.Id instead of twilioNumber.

## Screenshots
![image](https://user-images.githubusercontent.com/14079908/117420808-36e83780-af1e-11eb-9290-a356080f7b26.png)

**Comment by mdrichardson** [comment]
@Clooney24 Sorry, I'm not super familiar with using Twilio and Whatsapp together. Per the error, it sounds like messages have to be either:

1. <regularPhoneNumber> to <regularPhoneNumber>, or
2. <whatsAppNumner> to <whatsAppNumber>

So, in your `appsettings.json`, you should be able to set `"TwilioNumber"` to `"whatsapp:<yourNumber>"`.

If this does not fix it for you, can you please specify exactly how the message flow should work, including whether the bot's number and the user's number is a WhatsApp number or a regular one. It's a little unclear since `From.Id` in that method should never change, since it's only used for outgoing messages.

**Comment by Clooney24** [comment]
Hi Michael, 

yes, your assumption is right. When changing the number in appsettings, it might work, but then I'm no longer able to send SMS over this TwilioAdapter. I'd like to use both channels, WhatsApp and SMS over the TwilioAdapter. 

My fix using From.Id does work with both channels. And in that case you are using both channels, the From.Id should change depending on the channel, so when the bot is responding to a SMS, its the regular syntax and when responding to a WhatsApp, it's a WhatsApp syntax. 

From.Id is already correctly set like this as in incoming messages the receiver Id is formatted in the same manner and is used as From.Id in outgoing messages. So it's just that one change that makes it work.
