### ISSUE TITLE
Child Recognizers hit twice in quick succession when interruptions are enabled in Child Dialog (Adaptive)

### ISSUE THREAD

**Issue by taicchoumsft** [microsoft/botbuilder-dotnet#5593]
## Version
4.13.1

## Describe the bug
When building a bot with Composer, and enabling interruptions for a text input in a child dialog, the child recognizer is hit twice in quick succession.  There is one more call to the parent dialog recognizer, making 3 network calls for the same query. The parent query is expected, but should the child dialog recognizer be queried twice?

Fiddler screenshot showing two LUIS network calls from the child dialog for the same user query when interruptions are enabled (call to parent dialog recognizer not in this screenshot): 
![image](https://user-images.githubusercontent.com/61705609/118735526-7a338780-b7f5-11eb-8c8f-ff83e13b85ce.png)

## To Reproduce
1. Create an Empty bot in Composer
1. Create a new dialog, and in it, create a new Text Input (right click `Ask a Question->Text`)
1. Enable Interruptions
![image](https://user-images.githubusercontent.com/61705609/118735905-34c38a00-b7f6-11eb-9248-6b10ce8c78fd.png)
1. Create a trigger in the root dialog, and begin a new dialog to the newly created dialog
1. Set the child dialog to use LUIS or Orchestrator
1. Start Bot
1. Invoke the child dialog, and enter some text for the text input

## Expected behavior
When interruptions are on, we expect to see the child dialog recognizer hit only once for the child dialog,  and the parent recognizer hit only once for the parent dialog.

## Additional context
Some tracing showed the following: 
1) The dialog context starts at the Text Input, and `InputDialog.cs::OnPreBubbleAsync` calls its parent (the child dialog) to do a `RecognizeUtterance`.  This is the first invocation of the child LUIS recognizer. Bubbling appears to be stopped.
2) Somewhere down the line, the child dialog gets called (don't know why), and `Dialog.cs::OnDialogEventAsync` is called, which in turn calls `this.OnPreBubbleAsync` on itself. This causes the child dialog recognizer to now be invoked twice for the same query.  Bubbling is allowed to continue, and the child dialog calls `dc.Parent.EmitEventAsync` to invoke the root dialog.
3) The parent dialog is now called to do a `recognizeUtterance` on the parent dialog recognizer, this appears to be a correct bubbling from child to root. 
4) This was a customer reported issue on Composer [here](https://github.com/microsoft/BotFramework-Composer/issues/7696)

**Comment by boydc2014** [comment]
@Stevenic can you help comment is this by design?

**Comment by boydc2014** [comment]
After digging into the code base, this is somehow expected, the input dialogs are designed to run parent(child dialog)'s recognition first (note: without actually bubbling up yet) in order to be able to evaluate "allowInterruptions" field, and all this happens in the input itself.  

Then when the actual interruption happens, the message is bubbled to the parent (child dialog) and the recognition happens again. 

I'm not sure how we avoid the recognition twice, by setting a special flag\state, what do you think?

**Comment by boydc2014** [comment]
Put @Stevenic on this for design input, i can take the implementation part once the design is settled down.

**Comment by Stevenic** [comment]
It's by design that it's called twice but it should be getting cached for the turn such that its only called once. That was the assumption I was operating on when I implemented the double call.  The double call is needed because the interruption needs to run an expression to determine whether or not it should allow interruptions. 

The feature I was asked to implement was the ability to look at the parents intents when evaluating the "AllowInterruptions" property. The only way I could make that work was to have the child ask the parent to call its recognizer.

The recognizer should be caching for the turn otherwise its a bug. The JS version caches.
