### ISSUE TITLE
Handle custom language policies per recognizer type (LUIS/QnA Maker) and for language generation

### ISSUE THREAD

**Issue by mvelosop** [microsoft/botbuilder-dotnet#5600]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
When creating multilingual bots with unsupported LUIS locales in Composer the recommended solution is to create a customized language policy and then use a translation middleware. However, it's pretty easy to have "hand translated" templates that perform much better, from a user language POV, than what can be achieved on-the-fly with a translation middleware.

And it can even become more complicated, because QnA maker supports more locales than LUIS.

The above scenario is relatively easy to solve when creating a code-based bot, because you can create a "`MultilanguageTranslatingRecognizer`" that can be completely customized. However solving this with Composer has not been possible, mainly because the `LanguagePolicy` kind of gets in the way. Because a single `LanguagePolicy`, that applies both to user and bot messages is too restrictive.

**Describe the solution you'd like**
The possibility to define separate language policies per recognizer on one side and another for LG.

**Describe alternatives you've considered**
- Creating a "TranslatingRecognizer" to replace the standard LUIS recognizer. Result: by the time the recognizer is about to do its job the LUIS app has already been selected as per the language policy.
- Defining a custom LG policy on the MultiLanguageGenerator produces an error.

**Additional context**

**Comment by carlosscastro** [comment]
Thanks for your detailed explanation @mvelosop . I'm doing some experiments with this and will get back at you shortly.

**Comment by mvelosop** [comment]
Thanks @carlosscastro just let me know if you need any more info or details 😊

**Comment by mvelosop** [comment]
@carlosscastro I can invite you to a private repo in GitHub where you can see the working middleware solution, and the unsuccessful attempt, is that OK?

**Comment by carlosscastro** [comment]
Absolutely, feel free to invite me or send me a zip, whichever works better for you

**Comment by mvelosop** [comment]
You should 've received the invitation already.

**Comment by carlosscastro** [comment]
Hello @mvelosop! A few follow ups.

You mentioned above

> The above scenario is relatively easy to solve when creating a code-based bot, because you can create a "MultilanguageTranslatingRecognizer" that can be completely customized

The new component model that we are just releasing makes it so that code dialogs, recognizers and triggers are usable in composer and viceversa. So you can create your own recognizer in composer and not only consume it yourself in composer but if you wanted to, share it in a package if you want other folks to consume it.  You could create a recognizer just like we explain how to create a custom action [here](https://docs.microsoft.com/en-us/composer/how-to-create-custom-actions). If you already coded the recognizer, you can extend the composer object model and make it understand your recognizer. For that, as the article shows, you have to 1) add a Kind property to your recognizer that will be used to reference your recognizer in composer json format, 2) register the declarative type in your startup or as a separate component by calling `services.AddSingletong<DeclarativeType<MultiLanguageTranslatingRecognizer>>(MultiLanguageTranslatingRecognizer.Kind)`, and 3) if you want your recognizer to be configurable in the composer UI, add a schema for your recognizer just like the article shows. 

In parallel, we'll consider if we want to add something like this to the SDK or think other ways to allow the control you are looking for. Feel free to share your MultiLanguageTranslatingRecognizer code for us to review toward that end!

Finally, you mentioned that providing your custom language policy resulted in an error. Could you expand on that? Providing custom language policies should work. If you share the error and / or the language policy code, we can help on that as well.

**Comment by mvelosop** [comment]
Hi @carlosscastro,

Thanks for the info, will check on the new component model, I guess that means migrating to composer 2.0, right?

About the LG custom language policy, what I did, roughly, was creating a specialized  MultilanguageGenerator and repplacing the new one on the explorer registration with a hard coded policy just as a POC, but couldn't make it to work.

I also tried using a custom recognizer, it was mentioned in the documentation a few days ago, although it didn't really explained how to do it, but now it's gone from the docs.

Can you share a link where adding custom recognizers is explained? will also explore the custom component link you mentioned.

Thanks 😊

**Comment by mvelosop** [comment]
Hi @carlosscastro,

Finally I managed to get an initial custom recognizer component running, in spite of the (lack of) documentation 😅

You can take a look at this sample repo: <https://github.com/mvelosop/explore-bot-composer-2>

However, when I select the Custom recognizer and enter the custom JSON definition, which is jus identical to a LUIS recognizer, 
the trigger phrases input disappears:

![image](https://user-images.githubusercontent.com/7357806/121959740-14d3a780-cd5d-11eb-915c-f55e493ce062.png)

So I guess all the LUIS configuration that Composer does under the hood gets lost too, right?

So I kind of feel like in a dead end 😕

Any ideas around this?

**Comment by mvelosop** [comment]
BTW, you can see the changes in this draft PR: https://github.com/mvelosop/explore-bot-composer-2/pull/4

**Comment by mvelosop** [comment]
Hi @carlosscastro,

I tried another approach:

Registering a specialization of `LuisAdaptiveRecgnizer` with the `Microsoft.LuisRexognizer` [this way](https://github.com/mvelosop/explore-bot-composer-2/pull/4/commits/3f9f2529350b9d61369ffc35817a105a36924fe4#diff-7841c8bfb4ce6ef09c26cd64b82eece80dd6597221af809af365fd5da912ea05)

After several unsuccessful tries I forced an exception in the [TranslatingLuisRecognizer](https://github.com/mvelosop/explore-bot-composer-2/pull/4/commits/3f9f2529350b9d61369ffc35817a105a36924fe4#diff-1a600252d5fd3fd609740da2ee91b0bc50ca7f637bcd49317d1ca9d03a670847) but it never got executed.

What am I missing 😕?

Thanks in advance!

**Comment by mvelosop** [comment]
Hi @carlosscastro,

Finally I managed to create a custom LUIS recognizer and replace the standard one but it was kind of cumbersome, in the end I had to unregister the `LuisBotComponent` from the DI container, so mine was used instead.

You can see the changes in the PR: https://github.com/mvelosop/explore-bot-composer-2/pull/4

I think the scenario I depicted in the issue is fairly common, something like in the whole world except, perhaps, in the US.

Are there any plans, or at least discussions, about this issue.

Also wanted to check with you if this approach Is OK. Are there any hidden issues with this?

Thanks.

**Comment by mrivera-ms** [comment]
Closing it as @gabog is keeping track of this issue.

**Comment by mvelosop** [comment]
Hi @gabog, glad to know that someone's working on this, will you be updating an open issue/PR?

Thx 😊
