### ISSUE TITLE
Bot framework throws memory scope exception after 4.13

### ISSUE THREAD

**Issue by fabio-muramatsu** [microsoft/botbuilder-dotnet#5608]
## Version
4.13.2

## Describe the bug
We've started hitting an error when upgrading the bot framework SDK from 4.12.2 to 4.13.2. The error looks like the following:

```
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_bubble' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_name' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_classname' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_message' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_data' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_data_dialogcontext' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_data_dialogcontext_activedialog' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_data_dialogcontext_parent' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_data_dialogcontext_stack' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_data_dialogcontext_state' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_innerexception' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_helpurl' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_stacktracestring' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_remotestacktracestring' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_remotestackindex' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_exceptionmethod' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_hresult' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_source' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_watsonbuckets' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_paramname' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''dialog._tracker.paths.turn_dialogEvent_value_actualvalue' does not match memory scopes:[]')
MultiTurnPromptBot Error: 0 : Specified argument was out of the range of valid values. (Parameter ''turn' does not match memory scopes:[]')
```

This error gets thrown before it hits the root dialog of our bot, which is written using adaptive dialogs. 

## To Reproduce
Comparing the code of our bot with the [MultiTurnPromptBot](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/adaptive-dialog/01.multi-turn-prompt) from botbuilder-samples, I see that the sample bot includes a few additional statements in Startup.cs:

```cs
// Register dialog. This sets up memory paths for adaptive.
ComponentRegistration.Add(new DialogsComponentRegistration());
// Register adaptive component
ComponentRegistration.Add(new AdaptiveComponentRegistration());
// Register to use language generation.
ComponentRegistration.Add(new LanguageGenerationComponentRegistration());
```

So to reproduce:
1. Comment out the `ComponentRegistration` calls listed above from the MultiTurnBotPrompt (lines 25, 28 and 31 of Startup.cs);
2. Run the bot. It should throw an exception like the ones listed above;
3. Now, update the package version of the bot framework sdk to 4.12.2, and rerun. The bot should work.

## Expected behavior
Hopefully the bot should keep working in 4.13 without the `ComponentRegistration` bits, since it did on 4.12.

## Observations
Maybe the bot framework was never supposed to work without the `ComponentRegistration` statements, but I couldn't find a documentation telling what it does. So I'm raising this as a bug because that's what it looks like to me. If the guidance is to add these statements, I'd love if someone could clarify what they do and why it was working with 4.12.

**Comment by ryanlengel** [comment]
#5609 uses the same sample

**Comment by johnataylor** [comment]
Can you provide a few more details about what you are doing here?

As I understand it you are following the Adaptive code samples not the regular samples? is that correct?

I should point out up front that it is not recommended best practice to create Adaptive Dialogs with code. The recommended route is to use Composer. Our samples showing the ability to create Adaptive Dialogs from code are really just illustrative of how it works under the covers. Perhaps our samples didn't make that clear. If you are working all in code then the recommendation is to stick with the traditional Dialog classes - Waterfall and Prompts.

There is actually a pretty good level of interoperability - not surprising because Adaptive Dialogs are (literally) derived from the same base classes - for example it is easy to invoke a coded Dialog from an Adaptive Dialog for example.

Adaptive Dialogs actually require a bunch of things to be set up correctly for them to run. We made some effort in 4.13 to formalize this. And along with that a align better with .NET's Dependency Injection. Take a look at [AdaptiveDialogBot](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/AdaptiveDialogBot.cs)

This class is actually what you get by default when you say:

```
services.AddBotRuntime();
```

in your startup. I say "default" because you can override the bot class, just add your bot to the services collection too. We will be updating all our samples to do that in due course.

Anyhow, that doesn't exactly help you if you have a coded Adaptive Dialog because this AdaptiveDialogBot class assumes your Adaptive Dialog is a JSON object found in the resource provider. But other than that the code is basically the correct code for setting up an Adaptive Dialog.

Your speculation that it worked by accident previously is probably not unreasonable. I can't find any docs. The closest thing we have to docs is that sample code.

As I understand your comments, you say that adding those lines works for you in which case that's good. However, a better way to do things is illustrated by the AdaptiveDialogBot because that brings you closer to alignment with the platform DI system which works best when dependencies are explicitly modeled as constructor arguments. I could write a sample of what that would look like if that was helpful.

**Comment by fabio-muramatsu** [comment]
After chatting with @johnataylor, it seems like the direction this is going is away from global registrations and instead using DI. Comparing our IBot code with AdaptiveDialogBot, there are missing pieces that we may want to converge, and hopefully this will fix our original issue. I'm closing this for now.
