### ISSUE TITLE
AdaptiveExpressions `bool()` only converts `null`

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-dotnet#5615]
[The docs](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#bool) state that at least `1` and `0` should convert to true/false, respectively.

![image](https://user-images.githubusercontent.com/40401643/119877181-8c8c8000-bedd-11eb-9536-c48bf23a3c2f.png)

**Comment by Danieladu** [comment]
@chrimc62 has changed the logic to : Make booleans be false if expression is null or error and otherwise be true for non-boolean values or the actual boolean value.
But the document has not been updated.
So, do we need to modify the doc or need to modify the code logic here?

Reference: 
https://github.com/microsoft/botbuilder-dotnet/commit/effd01fb736a9ea8f794d3453286bfbe4ee72253
