### ISSUE TITLE
System.ArgumentNullException: 'Value cannot be null.' when credentials provider not configured

### ISSUE THREAD

**Issue by wmeints** [Microsoft/botbuilder-dotnet#562]
When I configure my ASP.NET Core app with the code below, without specifying a credentials provider.
I receive a `ArgumentNullException` on the line `app.UseBotFramework()` without actually specifying what the problem is.

However, I know what my problem is by looking  at the stacktrace: I didn't specify a credential provider.

I think it would be a great help if people got a descriptive error message for this misconfiguration.

``` csharp
public class Startup
{
    public Startup(IHostingEnvironment env)
    {
        Configuration = new ConfigurationBuilder()
            .SetBasePath(env.ContentRootPath)
            .AddJsonFile("appsettings.json", optional: true)
            .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
            .AddEnvironmentVariables()
            .AddUserSecrets("CustomerServiceBotSecrets")
            .Build();
    }

    private IConfigurationRoot Configuration { get; set; }

    // This method gets called by the runtime. Use this method to add services to the container.
    // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddBot<SupportBot>(options =>
        {

        });
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseBotFramework();
    }
}
```

**Comment by drub0y** [comment]
Thanks for reporting this! Ironically I just stumbled across this yesterday while working on unit tests for the ASP.NET integration APIs and am already working on a fix. The proposed fix will be as follows:

> If the `CredentialProvider` is not set on the `options` then the integration will automatically register the `ConfigurationCredentialProvider` which will attempt to load the values from app settings (e.g. `MicrosoftAppId` and `MicrosoftAppPassword`).

Now, the only thing I don't like about this is that this will at least get past the `ArgumentNullException`, but you'll run into a runtime problem later about missing credentials if those settings are null/empty. It's a better experience for sure, but I'm wondering if we should fail faster at startup time, just with a more detailed error explaining that credentials are missing. Any one have any thoughts?

**Comment by drub0y** [comment]
Ok, I'm flip-flopping on this because I had this change all set and working in tests and then I remembered that, when someone just does file -> new project and wants to fire it up in an emulator locally, they shouldn't be required to be supply any specific credentials because they might not even have any yet. So I don't want to put that 🚧 in the way of the experience. 

Instead I'm going to go the route of detecting that no `ICredentialManager` has been configured and default to an empty instance of `SimpleCredentialManager`. This provides the easiest route to getting started and only once you're ready to actually start interacting with the live Bot Framework Service will you need to concern yourself with configuring credentials explicitly.
