### ISSUE TITLE
Compile warnings from Adaptive Runtime on a new project

### ISSUE THREAD

**Issue by darrenj** [microsoft/botbuilder-dotnet#5634]
## Describe the bug

Following warnings on any new project created using Composer
```bash
C:\Users\darrenj\downloads\CoreWithLanguageDocs\CoreWithLanguageDocs\CoreWithLanguageDocs.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
C:\Users\darrenj\downloads\CoreWithLanguageDocs\CoreWithLanguageDocs\CoreWithLanguageDocs.csproj : warning NU1701: Package 'Microsoft.Azure.KeyVault.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
```

## Version

![image](https://user-images.githubusercontent.com/33519520/117444247-19709900-af31-11eb-8ee1-6a2f9cea341f.png)

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## Expected behavior

No compile warnings

**Comment by mrivera-ms** [comment]
The KeyVault dependency exists in library Microsoft.Bot.Builder.Azure and is associated with classes [AzureBlobStorage](https://github.com/microsoft/botbuilder-dotnet/blob/667e0cea22ae60c87bdf4353b876bf5b565c9a4a/libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs#L31) and [AzureBlobTranscriptStore](https://github.com/microsoft/botbuilder-dotnet/blob/667e0cea22ae60c87bdf4353b876bf5b565c9a4a/libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs#L23). These classes are deprecated and may be removed from future versions of the SDK and because updating the referenced libraries may have larger implications than we anticipate, we prefer not to make further changes at this point. The warnings are suppressed in the SDK and do not appear at build time. They may need to be suppressed in Composer projects if they appear as well.
