### ISSUE TITLE
Component registration for declarative only packages

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#5674]
We need a mechanism for determining if a particular package contains declarative assets only, so that the runtime can know not to look for a dll/library to load for that particular package. Currently we are using tags to determine this, however we'll need a long-term solution.

From @carlosscastro :

Taking a step back and throwing another option: The same NuGet apis that we use to get the list of packages also has apis to get more metadata about packages, such as for example, dependencies of the package. All BotComponent packages will have a well known dependency to Microsoft.Bot.Builder. These metadata apis also may allow to tell whether the package has dlls and / or content. The same can also be achieved through inspection of the packages like schema merge does. So with that in mind, either though api or package inspection, we could build in logic in the SchemaMerger or in composer to add component data stating whether they have assets, dlls or both. Then based on that output we could make a 100% solid decision on whether to add the package to the components list or not.

**Comment by peterinnesmsft** [comment]
@clearab can you review and validate if the below is an acceptable approach for tackling this?

Having reviewed with @tracyboehrer, we believe there are two high-level items that need to happen:

1. When an upstream source (e.g. Composer, CLI, etc) adds a package dependency to the bot application, if the package contains code of some kind (for .NET, assemblies; for other languages, script files and so on), then corresponding entries should be added to the list of components in the application settings. For the .NET case, this would be assembly references.
2. In the runtime itself, during application startup, the runtime will attempt to load components from the list as defined in application settings. If the assembly exists, but does not contain any bot component implementations, a warning should be logged, and the application should continue through initialization as normal.

---

Having done some investigation, NuGet does not have any capability to specify custom metadata. As a rule of thumb, the belief is we should keep custom steps required by developers to create a component package to a bare minimum - in other words, it should be as simple as publish a package that contains a publicly available implementation of the bot component type.

We also recognize that just because a package contains assemblies, however, does not necessarily mean that any of those may contain bot component implementations. Ideally, we only would register assemblies that contain a type that implements the base bot component type, but the only way to do that reliably means to load up the assembly and discover its types. We could do this at the time a package is added, but it forces a crawl of a package's contents which is additional latency to the overall operation. It also would require us figuring out how to interop .NET code with JS, since that is what the BF CLI is written in.

In the case of .NET and NuGet, there is also the issue that assemblies contained in a package may not match the name of the package itself. We could ask developers to keep names between packages and assemblies the same, but I don't think that is a realistic expectation we can have of them since it may be beyond their control.

---

What this would entail is that whichever upstream source responsible for adding component packages would need to additionally restore dependencies, crawl through packages to determine contained assemblies, and register those in the application settings. This keeps the amount of deep inspection required to a minimum, and allows runtimes implemented in their respective languages to use their own mechanisms to determine whether referenced components are indeed present and able to be loaded (i.e. JS runtime could pull in a referenced npm package, and inspect to see whether it exported a type matching whatever desired signature, in the same way that .NET runtime could inspect the assembly for the implemented type).

In terms of runtime behavior itself, this would mean we then do the following during startup:

- Attempt to load a non-existent assembly -> Error and exit
- Attempt to load an existent assembly that does not contain bot component implementation -> Warning and continue
- Attempt to load an existent assembly that contains a bot component implementation and throws during loading -> Error and exit

This does add some initialization overhead depending on the number of assemblies that need to be checked, but would otherwise have no effect on API performance once the web app itself is running. Warnings could direct users to remove entries from application settings that are not required as an optimization to startup time.

**Comment by peterinnesmsft** [comment]
Spoke offline with @clearab - he has agreed with the approach outlined above. We will need asks on the Components and JS folks to track in those areas as well. Will create additional issues as needed.
