### ISSUE TITLE
BotFrameworkAdapter CreateConversationAsync overrides conversationParameters.ChannelData

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botbuilder-dotnet#5676]
First reported in [Python 1665](https://github.com/microsoft/botbuilder-python/issues/1665). Seems to be an issue in C# as well: https://github.com/microsoft/botbuilder-dotnet/blob/baf78d01d4c0b8ddae2d117a52d2a4bca1479683/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L1362
Needs verification.

**Comment by cleemullins** [comment]
This is an issue in Python, and we need to figure if this also an issue in C#.

**Comment by tracyboehrer** [comment]
It's the same for every platform.  It just sets the channelData with a new object.  The suggested fix in Python seems to be appropriate.  If there is already channelData, just set the tenantId on it instead of creating a new object.  Thing is, we don't really know what that object is in C# and Java.

**Comment by tracyboehrer** [comment]
My question is from this comment: "Putting tenantId in channelData is a temporary solution while we wait for the Teams API to be updated"

Is this still even needed?

**Comment by MartinLuccanera** [comment]
Hi @tracyboehrer, we tested the fix suggested in the issue and it works. Removing the temporary solution works too. However, as we can't confirm that the Teams API has been updated, we created the PR applying the fix.
