### ISSUE TITLE
GetTeamDetailsAsync errors Bot.Builder Nuget Package 4.13.2 and 4.13.1

### ISSUE THREAD

**Issue by clearab** [microsoft/botbuilder-dotnet#5712]
Approvals bot is facing issues calling GetTeamDetailsAsync method with Bot.Builder package 4.13.2 and 4.13.1. Upon calling the method, the error we are getting back is this:

```    
Cannot access a disposed object.
Object name: 'Get'.


      turnContext
{Microsoft.Bot.Builder.DelegatingTurnContext<Microsoft.Bot.Schema.IInvokeActivity>}
    Activity: ["invoke"] ""
    Adapter: {Approvals.Common.Bot.AdapterWithErrorHandler}
    Responded: true
    TurnState: Count = 6
    
turnContext.Activity.TeamsGetTeamInfo().Id
"19:1111111111111111111@thread.tacv2"
cancellationToken
IsCancellationRequested = false
    CanBeCanceled: false
    IsCancellationRequested: false
    WaitHandle: {System.Threading.ManualResetEvent}
```

It was working fine on 4.10.0, which was a previous package we are using. This is preventing our team from upgrading our bot builder package and also future deployments. Could we get someone to help us with this? Thank you.

**Comment by EricDahlvang** [comment]
This could be due to the disposing of `ConnectorClient` and `TeamsConnectorClient`:
https://github.com/microsoft/botbuilder-dotnet/pull/4864/files

Is the call to `TeamsInfo.GetTeamDetailsAsync` performed within the context of processing an incoming activity? Please share the code, or a repro. A stack trace would also be helpful.

**Comment by clearab** [comment]
I was unable to repro using the latest SDK and sample 57 as a base.
