### ISSUE TITLE
Using Strictfilters in Bot Composer for getting QnA response based on metadata passed from AD

### ISSUE THREAD

**Issue by RohitJhander** [microsoft/botbuilder-dotnet#5721]
We are creating QnA dialog in bot composer to get answers from KB. And in QnA maker we have defined metadata for some questions and want to get response based on that metadata . In bot composer we are getting dynamic values from Azure AD based on user profile which we want to send as metadata to QnA along with user utterance. Before sending metadata to QnA, in bot composer we are using Strict Filters option. As we are storing values coming from AD in $user memory variable and want to apply strict filters on $user.something, we changed schema  (in sdk.schema file) to accept metadata name and values as reference ( by default it accepts string). But this approach is not working as schema changes are not getting reflected when we are testing in bot emulator and getting error: "Response status code does not indicate success: 400 (Bad Request)." What is the correct approach to apply strict filters using memory variables or to update the schema? 
<img width="520" alt="Qna1" src="https://user-images.githubusercontent.com/11708992/122708106-057ebd80-d279-11eb-846f-2e6289032343.PNG">
<img width="228" alt="qna2" src="https://user-images.githubusercontent.com/11708992/122708112-07488100-d279-11eb-8c6d-4a8dc0c65ce0.PNG">

**Comment by LeeParrishMSFT** [comment]
I'm actively looking into this and will provide an update later this week once we can determine what might be possible to meet this scenario of setting StrictFilter values from memory variables.

**Comment by LeeParrishMSFT** [comment]
@RohitJhander and @richa0912  Unfortunately the fields exposed by Composer for name/value are not evaluated as expressions and they are taken as literal string values and won't be evaluated as expressions. This is something we will be looking into as a potential feature for a future release. 

There is a workaround that will let you use an expression for the strictFilters but it requires manually modifying the .dialog file that contains your QnAMakerDialog. The downside to doing this is that any time you edit the dialog with Composer it will overwrite the manual changes you made to the .dialog file. 

If you want to go this route my suggestion would be to create a step before the QnAMakerDialog to create and set a property to the expression you want to use, then assign that property to the strictFilters of the QnAMakerDialog so that if Composer did overwrite it would only overwrite the assignment of the property to the strictFilters property, and not the expression.  Unfortunately it's not possible to do the strictFilter assignment to an expression directly in Composer as it only allows name/value pairs and not an assignment an an expression. 

Here's an example of the workaround. First create a new property and assign it to an expression that we can use to set later manually in the .dialog file:

![image](https://user-images.githubusercontent.com/30470292/125102117-938fdc00-e0a0-11eb-81b7-2bcdf95b79e5.png)
In this step I've created a property in user called user.metadata and assigned it to the following expression:

createArray(addProperty(addProperty(json('{}'), 'name', 'firstName'), 'value', `${user.firstName}`),             addProperty(addProperty(json('{}'), 'name', 'lastName'), 'value', `${user.lastName}`))

The expression results in a JSON fragment that would look like this when it's evaluated if had other properties set for user.firstName of "Joe", and user.lastName of "Brown":
```
  "strictFilters": [
    {
      "name": "firstName",
      "value": "Joe"
    },
    {
      "name": "lastName",
      "value": "Brown"
    },
  ]
  ```
You can also set the "name" values to properties as well by using ${} syntax with an assignment of a property for the name values as well. And you can use the expression syntax to have one or more name/value pairs, just modify the expression to meet your own needs.
  
Once you have this done and you have an expression that covers your filters, you'll need to open the .dialog file that defines the dialog that includes the QnADialog you want to set the strictFilters on. This will be in the dialogs folder of the project and named whatever you named the dialog in Composer with a .dialog extension. For example my dialog was named "QnAMakerTestDialog", so it was in a directory /dialogs/QnAMakerTestDialog/ and was named QnaMakerTestDialog.dialog. Once you have this file, open it in a text editor find where within the file it defines the QnaMakerDialog instance. In mine it looks like this:
```
        {
          "$kind": "Microsoft.QnAMakerDialog",
          "$designer": {
            "id": "Uy2EFu"
          },
          "knowledgeBaseId": "=settings.qna.knowledgebaseid",
          "endpointKey": "=settings.qna.endpointkey",
          "hostname": "=settings.qna.hostname",
          "noAnswer": "${QnAMakerDialog_NoAnswer_Uy2EFu()}",
          "threshold": 0.3,
          "activeLearningCardTitle": "Did you mean:",
          "cardNoMatchText": "None of the above.",
          "cardNoMatchResponse": "${QnAMakerDialog_CardNoMatchResponse_Uy2EFu()}",
          "top": 3,
          "isTest": false,
          "strictFilters": []
        }
```
What we need to manually edit is the "strictFilters" assignment. To assign it to your property update this line to the property you created to contain your expression, in my case it would be turn.metadata:
```
          "strictFilters": "=user.metadata"
```
This will evaluate the expression, and it will result in a set of name/value pair(s) that can be assigned with expressions instead of literal values. Save the .dialog file and be sure to come back and make this one line change to the strictFilters if you open and update the Dialog in composer as it will overwrite your manual change and set it back to "strictFilters":[].

Let me know if you have any questions or have any issues. I know this workaround isn't the easiest as it requires a manual change that composer may overwrite, but it's the best we can provide without a larger change to the Bot Framework SDK itself.

**Comment by gabog** [comment]
Closing due to no response.
