### ISSUE TITLE
DCR: add 'immediateAccept' setting to BotFrameworkAdapter

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botbuilder-dotnet#598]
The `BotFrameworkAdapter` currently holds open incoming requests for the lifetime of the turn which has two significant impacts on the bot:

1. It holds open a network resource which can negatively impact the performance of the bot and limit scalability.
2. If the bot performs a long running operation the incoming request can be timed out by the calling server leading to false errors being reported to the original sender.

To address these potential issues I suggest we add a `immediateAccept` setting that lets a developer force the adapter to send a 202 ACCEPT status code immediately after it authenticates the incoming request. This will free up resources and let the bot perform long running operations without timing out the request. The potential con is that the channel no longer receives notifications of errors that occur while processing the request and a bigger potential issue is that depending on what type of hosting plan you're using you could end up getting recycled before the request completes.

**Comment by drub0y** [comment]
Totally like the idea on the surface, here are some thoughts that popped into my head as soon as I thought about it for a second:

First, might I suggest that, since this is really a transport level concern, we actually represent the `immediateAccept` concept via an HTTP header and not inside of the message payload (e.g. activity) itself. For example, maybe something like: 

`X-MS-BotFramework-Options: immediate-accept`

> NOTE: this header could be expanded to support multiple options over time if the need arises.

Next, there is one protocol "clash" here that I can think of off the top of my head which is that if this is specified for an invoke activity then that's conflicting since obviously invoke implies an actual response in the traditional HTTP request/response sense. I would suggest that we return a `400` (Bad Request) in the case of such a conflict vs. maybe just ignoring the `immediateAccept`.

Implementation wise I wonder how you're actually planning on doing this on the Node side though. Specifically how are you going to fork off your background work off the original request context?

On .NET side, a naïve implementation could just fire this off to the `Task` pool, but my initial concern there is that, right now, we're getting request bounding from the ASP.NET runtime itself (i.e. it's in charge of limiting exactly how many requests are being processed at once). If we start returning `202`s through ASP.NET immediately and spinning off the work in the background, we can get into a situation where we are actually accepting and queuing up more work to the background pool than it should be handling. So, at the very least, it would be wise to put some kind of bounding in place to govern that pool and then you're in the business of providing some kind of bounded work queue. Now this is something that TPL data flow could provide pretty easily if we're comfortable with taking that dependency, but then some more questions come into play: 

 * Where does configuration of that bounding come into play? Should it just inherit from whatever's configured for ASP.NET?
 * What should the behavior be if the pool's queue is at capacity? I would assume it should return a `503` instead.

**Comment by Stevenic** [comment]
Thanks for the detailed response @drub0y. 

> First, might I suggest that, since this is really a transport level concern, we actually represent the immediateAccept concept via an HTTP header and not inside of the message payload (e.g. activity) itself.

While i agree that it feels like a transport thing it needs to very on a per-bot basis.  When would the channel know to send it versus not send it?  The protocol says you have *n seconds* to respond with a 202. Perf wise the best way to fulfill the protocol is to ACK immediately but that can cause issues in some cases (particularly with IIS) which is why we currently just hold the request open. It's safer.  If you set this flag you may need to do extra work (like telling IIS not to recycle you) but you'll get better performance.

> Next, there is one protocol "clash" here that I can think of off the top of my head which is that if this is specified for an invoke activity then that's conflicting since obviously invoke implies an actual response in the traditional HTTP request/response sense. I would suggest that we return a 400 (Bad Request) in the case of such a conflict vs. maybe just ignoring the immediateAccept.

I was planning to just ignore the flag in the case of `invoke`. Why would you send a `400` instead? The protocol wasn't violated by the calling server in any way so it's not a client error.

> Implementation wise I wonder how you're actually planning on doing this on the Node side though. Specifically how are you going to fork off your background work off the original request context?

This is how the v3 SDK already works. Your promise chain can resolve independent of the response being sent to the caller.  So just because you sent a response to the server doesn't mean you have to stop running code. Again, on IIS you need to tell IIS not to recycle you.

**Comment by gmmarc** [comment]
For anyone struggling with this on WebChat, I've solved it this way on my bot:

```node
// index.js file

// Listen for incoming activities and route them to your bot main dialog.
server.post('/api/messages', (req, res) => {
    // Route received a request to adapter for processing
    adapter.processActivity(req, res, async (context) => {
        // route to bot activity handler.
        await bot.onTurn(context);
    });

    // Send 202 response right now.
    // That prevents WebChat from showing 'Sending' until the message has been processed.
    // NOTE: by doing this, we lose the 'Retry' capability.
    // More info:
    // @link: https://github.com/Microsoft/BotFramework-WebChat/issues/465#issuecomment-468000346
    // @link: https://github.com/Microsoft/botbuilder-dotnet/issues/598
    res.status(202);
    res.end();
});
```

If anyone has a better approach or sees an issue with this solution, please let me know :)

**Comment by lirimi1996** [comment]
@gmmarc hello, how to import this components (server,bot,adapter) ?

**Comment by harshithkashyap** [comment]
We have been trying to migrate our v3 Node.js bot to v4 and this has been a major issue for us. In order to provide a natural conversation flow when the bot needs to send across multiple messages as reponse to user's queries, we allow customers to set delays and typing indicator values delaying each message sent within a dialog. We use bluebird `Promise.delay()` function and delay the execution of the dialog based on the given timeout values. In most of the cases, we are running into directline timeout though the bot still processes the utterance.

> The potential con is that the channel no longer receives notifications of errors that occur while processing the request and a bigger potential issue is that depending on what type of hosting plan you're using you could end up getting recycled before the request completes.

The errors which occur when a dialog is being processed is caught by `adapter.onTurnError` method and the response is sent out as a separate message and not as HTTP response to the original request. The HTTP request still completes with a 202 and an id value as the response.

> Perf wise the best way to fulfill the protocol is to ACK immediately but that can cause issues in some cases (particularly with IIS) which is why we currently just hold the request open. It's safer. If you set this flag you may need to do extra work (like telling IIS not to recycle you) but you'll get better performance.

Sending an acknowledgement back immediately is how I see v3 implemented and our dialogs based on this model. The way I see it, user's messages should be processed asynchronously. The bot receives the message and the framework acknowledges that the message was successfully received after the framework token validations are complete. The bot then responds back to the user asynchronously.
Since the responses from bot to user itself aren't actually sent back along with the HTTP request and obtained over a websocket or HTTP polling, I don't see why we should limit it in this case.

I see suggestions to use proactive approach to handle the timeout issue but this becomes an overkill. When you have arbitarary customer configurable timeouts and delays, every incoming message would then have to processed as a proactive message.
As streaming extensions are coming to Node, messages will be sent fully over a websocket and/or websocket + namedpipe. All the messages would then be processed async by default.

I request that `immediateAccept` or similar flag be added to the framework at the earliest. You can add a warning stating the potential issues users might run into. This would help users migrate to v4 keeping their existing implementation logic.

**Comment by gabog** [comment]
Closing as part of R10 triage.
