### ISSUE TITLE
FoundChoice misbehaving when text and an integer value is entered

### ISSUE THREAD

**Issue by frei-sven** [microsoft/botbuilder-dotnet#6010]
## Version
Microsoft.Bot.Builder.Dialogs 4.14.1.0

## Describe the bug
In the validation of the component `FoundChoice` the property `.Recognized.Succeeded` is also set to true if none of the given choices match directly. For example we have a choice prompt with the choices `Send` and `Cancel`. If I enter for example `No start at 01.01.2022` the first choice `Send` is detected. Which is not what I would expect. And if I enter something like `... 02.02.2022` the second choice `Cancel` is detected.
Also no aliases have been registered for the choices.

## To Reproduce
1. Have a dialog with a `ChoicePrompt` and one or more choices without any aliases.
2. Register a choice validation method for the `ChoicePrompt` e.g.:
```c#
AddDialog(new ChoicePrompt(nameof(ChoicePrompt), ChoiceValidation));
```
3. The choice validation should only return the following:
```c#
return Task.FromResult(promptContext.Recognized.Succeeded);
```
4. When testing the prompt in BotFramework Emulator input none of the given choices but rather something with an integer value (e.g. `Do 01`)
5. Then check if the choice has been recognized in the validator. In my case the returned value was `true`

## Expected behavior
The choice should not be recognized therefor the validation should return `false`.

## Additional context
My workaround now is to check if the input value matches the registered choices:
```c#
protected async Task<bool> ChoiceValidation(PromptValidatorContext<FoundChoice> promptContext, CancellationToken cancellationToken)
        {
            return await Task.FromResult(promptContext.Recognized.Succeeded) &&
                promptContext.Options.Choices.Any(c => c.Value.Equals(promptContext.Context.Activity.Text, StringComparison.InvariantCultureIgnoreCase));
        }
```

If something is unclear. I can provide additional information.

**Comment by dmvtech** [comment]
I'm investigating this. Thank you for reporting.

**Comment by anishprasad01** [comment]
I was able to reproduce this bug and confirm that the workaround functions. However, not every combination of numbers and letters causes this.  There seems to be something about the format of certain strings that causes validation to pass incorrectly. For example, standalone numbers separated by periods is one that tends to fail. Further investigation is required to determine why.

**Comment by anishprasad01** [comment]
Hi @frei-sven,

After some investigation, I believe I know the cause of your problem. When the user's input cannot be directly matched to one of the choices, the code will then fall back on checking for ordinal numbers or integer values to try and deduce which option the user wants. In your example, you have the options `Send` and `Cancel`. The input `Do 01` is being interpreted by the ChoicePrompt as a request for the first option, and thus `Send` is recognized. This result would be akin to entering something like "The first option" or "Pick number 4". Essentially, the integer is being interpreted as an index into the available choices.

When you entered the dates `01.01.2022` and `02.02.2022`, the same thing happened. The code broke the utterances into tokens, sorted them, then pulled the first one and interpreted the numbers as an index. Thus, `01` became `Send`, and ``02` became `Cancel`, the second option.

When you enter an incorrect input without specifying any numbers, this validation fails since there are no integers or ordinals to interpret and the user is prompted again, as you would expect.

As we want to be able to recognize users that choose options by number, this is intended behavior. Given that, your solution of double-checking the input against the choice in your dialog is an appropriate workaround.

**Comment by frei-sven** [comment]
HI @anishprasad01
Thanks for your detailed answer. Now I completely understand that this behavior is as intended with the examples you have described. I never thought of this while coding with the Botframework. But maybe I have a use case for this in the future 💯 .
But maybe as an idea for a future modification of the `ChoicePrompt`/`FoundChoice` component, to make this behavior controllable via an input value. To give the developer a choice if he wants this implicit decision-making or not.
