### ISSUE TITLE
AdaptiveCard SubmitAction does not serialize anonymous types in Data

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-dotnet#633]
So I just stumbled across this today. I was attempting to use an anonymous type for the `Data` property of a `SubmitAction` and while it compiles fine (of course) and runs fine at runtime, the action data from the anonymous type is not being serialized and emitted into the `data` property in the JSON that is returned.

I was surprised by this because JSON.NET supports serialization of anonymous types, so I'm not sure what's preventing this from working.

**Comment by yochay** [comment]
@drub0y  can you take a look and see if you can fix this?

**Comment by johnataylor** [comment]
This is caused by the use of the ReadOnlyJsonContractResolver on the JsonSerializerSettings ContractResolver.

This is set in the integration code to deserialize the inbound activity and its set by default in the swagger generated connector client.

The fact that we are consistent is good.

Switching the ContractSerializer out to the DefaultContractResolver allows anonymous types to be used however we would need to test for any regression. (And supporting anonymous types would be a good thing and testing for regression shouldn't be too bad.)
