### ISSUE TITLE
Bot not authorizing on teams

### ISSUE THREAD

**Issue by ikaur1718** [microsoft/botbuilder-dotnet#6479]
The Teams bot Authentication doesn't work, doesn't allow users to login. It always give the error below

![image](https://user-images.githubusercontent.com/33502206/192282633-a7424e42-8ef7-408d-82a5-fd594f428b55.png)

when logging on mobile teams app. It is redirecting to https://token.botframefork.com but with an error saying failed to load webview

**Comment by anishprasad01** [comment]
Hi @ikaur1718,

We need you to provide more information in order to repro or investigate this. 

- What samples did you use as a base?
- What code changes did you make? 
- What documentation did you use?
- What kind of configuration did you perform?
- Is there any other relevant information which may help diagnose your issue?

**Comment by anishprasad01** [comment]
I believe the `UseSingleSignOn` setting needs to be set to `true` for Teams SSO.

**Comment by ikaur1718** [comment]
That did not work. that app setting is not being used in the application.

**Comment by anishprasad01** [comment]
As per the README of the sample you linked:
![image](https://user-images.githubusercontent.com/33945547/192581195-143a6b2c-1418-4022-9831-b47b07b33ba7.png)
The setting is set to `false` be default, but the developer should enable it when configuring Teams SSO, assuming the rest of your configuration is correct.

**Comment by ikaur1718** [comment]
I made those changes but now my adaptive card for login is not appearing at all.
