### ISSUE TITLE
Async methods should take cancellation token

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-dotnet#661]
For example the middleware is async and should take cancellation tokens.

**Comment by drub0y** [comment]
We should probably make sure this is coordinated or someone's going to be in a merge conflict nightmare! 😆

Side note: this might be a good time to introduce a strongly typed delegate for what is currently just `Func<ITurnContext, Task>` because now that's going to have to become `Func<ITurnContext, CancellationToken, Task>` allllll over the place.

![Good luck!](https://media.giphy.com/media/1lk1IcVgqPLkA/giphy.gif)
