### ISSUE TITLE
Microsoft.Bot.Builder project not set to generate nuget package for local build

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-dotnet#666]
When building the BotBuilder project locally the nuget package for Microsoft.Bot.Builder is not generated and put in the outputpackages folder. All other projects seem fine.

Checking the "Generate NuGet package on Build" setting on Microsoft.Bot.Builder.csproj resolves the issue.

![image](https://user-images.githubusercontent.com/33519520/41508101-08f386ee-7237-11e8-9a0b-fc066cbcc612.png)

**Comment by cleemullins** [comment]
@johnataylor John is in the middle of cleaning up (and merging / refactoring) a number of the projects in our overall solution. John - can you take a quick look? I don't want to change this myself simply so you don't end up in Crazy Merge Land with all of the outstanding changes you have. 

(If you can't get to this, it's easy enough to fix once you're all checked in)

**Comment by drub0y** [comment]
So, it's there, it's just that it's only doing in `Release` configuration. This needs to be added to the project to bring it inline with the other projects:

```XML
<PropertyGroup Condition="$(Configuration) == 'Debug - NuGet Packages'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
</PropertyGroup>
```

That said, now that we're using `Directory.Build.props` this kind of stuff should ultimately just be rolled up under there instead of maintained on a per-project basis. /cc @BruceHaley
