### ISSUE TITLE
suggestedactions behavior

### ISSUE THREAD

**Issue by franperezlopez** [Microsoft/botbuilder-dotnet#717]
I'm using `CardAction` as buttons for `MessageFactory.SuggestedActions`. I have some problems understanding the relationship between Type and DisplayText. Currently:
* Type = `Postback`, no text is displayed in the feed when the button is clicked
* Type = `ImBack`, in the feed I've got displayed the `Value` property, even if the `DisplayText` inline help (*Gets or sets (Optional) text to display in the chat feed if the button is clicked*) suggests its value should be shown in the feed

Also, when using the `MessageFactory.SuggestedActions` method, if you leave the `text` parameter as null, you get an empty box (empty line) in the feed (at least in the webchat emulator)

![image](https://user-images.githubusercontent.com/1222398/42156674-f70b3efc-7deb-11e8-8848-a65f116ac134.png)

**Comment by cleemullins** [comment]
@EricDahlvang, @JonathanFingold

**Comment by EricDahlvang** [comment]
Hi @franperezlopez 

Thank you for taking the time to report these issues.

There is some discussion about the current implementation of **DisplayText** on SuggestedActions here: https://github.com/Microsoft/BotFramework-WebChat/issues/868  (Apparently the WebChat repository is waiting for the DirectLineJs repository to implement something.  Since the emulator uses WebChat internally, it is also waiting for this feature to be fully implemented).

Similarly, WebChat has fixed the bug related to an empty message bubble: https://github.com/Microsoft/BotFramework-WebChat/issues/870  But, the emulator repository has not yet brought in the fix.

**Comment by daveta** [comment]
Closing since this is being discussed/ tracked in the webchat repo
