### ISSUE TITLE
Customize the response from QnA maker

### ISSUE THREAD

**Issue by phule80** [Microsoft/botbuilder-dotnet#766]
I am using Bot SDK v4 integrate with QnA maker.Everything works fine but now I want a way to customize the response message from QnA maker. For ex:  when use is in the middle of conversation and then suddenly he/she asked unrelated question to Bot and then QnA detects the question and response. I need a approach to catch the response and append the message to ask user that he/she want to continue with the current conversation or not?How can I do that in Bot framework version 4? ( I am using C#). Tks

**Comment by ukphillips** [comment]
Are you using the QnAMaker middleware? There is an option in the QnAMakerMiddlewareOptions for an answer prefix:

```
var qnaMiddleware = new QnAMakerMiddleware(qnaEndpoint, new QnAMakerMiddlewareOptions() { DefaultAnswerPrefixMessage = "Here is an answer, do you want to continue?" } );

options.Middleware.Add(qnaMiddleware);
```
not appending on the end, but close. 

It seems like you would need to set some state on the bot to indicate you have transitioned to an QnA response, if you know that you could send a proactive message following up the QnA response with another message "Do you want to continue?" which makes more sense to be a separate message rather than added into the end of a message coming from QnA maker.

**Comment by JonathanFingold** [comment]
If you are using QnA Maker as a service, as opposed to middleware, you will have access to the responses from your bot code.

**Note**: the following code was written against one of the recent daily builds, so some small amount of reworking would be necessary to get this to compile against the packages published to NuGet.org.

Within your bot's turn handler (here, QnA is an instance of the QnAMaker class):

```csharp
if (!context.Responded)
{
    // Field any questions the user has asked.
    var answers = await QnA.GetAnswers(text).ConfigureAwait(false);
    if (answers is null)
    {
        // Output trace information to the Emulator.
        // This does not generate a response to the user.
        await context.TraceActivityAsync("Call to the QnA Maker service failed.").ConfigureAwait(false);
    }
    else if (answers.Any())
    {
        // If the service produced one or more answers, send the first one.
        await context.SendActivityAsync(answers[0].Answer).ConfigureAwait(false);
        // Add additional logic here.
    }
}
```

When using QnA Maker as middleware, you could get access to the answers list, but you'd have to jump through more hoops. @phule80, Let me know if you need a code sample for that.

**Comment by phule80** [comment]
Thanks so much for your quick response. Let me re-describe the situation more details so you guys don't take time much on this.
For ex :  In the bot project I have a dialog name: “dialog1” which using Waterfall technology as below:
this.Dialogs.Add(dialogId1, new WaterfallStep[] { Step1, Step2 , Step3, Step4}); 

When user is in a conversation and at step2, suddenly the user type: “abc” then QnA responses the message match with the question “abc”. By following your idea, I can detect the answer from QnA service and then I prompt out a message to user like “Do you want to continue with the current conversation? (below is the sample):
public async Task OnTurn(ITurnContext context)
{
            var QnA = new QnAMaker(GetQnAMakerEndpoint());
            // Field any questions the user has asked.
            var answers = await QnA.GetAnswers(context.Activity.Text).ConfigureAwait(false);
            if (answers !=null && answers.Length > 0)
            {   
                await context.SendActivity("Do you want to continue with the current conversation?”)

            }
} 
**Note:** after the user types:”abc” then QnA responses before the system jumps into Onturn method

So, what is expect here is:  after I prompt out the message to ask user what he/she wants next. If they answer: “Yes” then they can continue with the current step(step2). However, currently after I prompt out the message and user type anything then system will repeat at step2. Do you have any way to detect and intervene in to this one base on user’s answer yes or no? 
When I run at debug mode, the system doesn’t stop at step2 or anyway to I don’t know how to intervene.
And yes, I am using QnA as middleware (integrates with Luis also). So, if you guys have any idea then provide me. I appreciate your help. 
If maybe please help provide me the code sample. That will help me much. Thanks

**Comment by daveta** [comment]
Thanks for reporting this. We are working through a solution for this. @Stevenic @Kaiqb

**Comment by JonathanFingold** [comment]
@phule80 , sorry for the delay. I will defer to @Stevenic for a full answer, but in short, you probably want to design your logic as follows. (Note that the team is planning to remove both the QnA Maker and LUIS middleware classes, and suggesting that developers just use QnA Maker and LUIS as services within their bot code.)

**Step n**: The user has asked a question and your bot has sent an answer from QnA Maker. Your bot can send a second message asking if the user wishes to continue the dialog. You'll need to set a state flag for yourself to know that you're in this indeterminate...state. However, do not continue the dialog this turn, as [presumably] the user input was not meant as a response within the dialog.

**Step n+1**: Your bot is expecting a yes/no response from the user this turn. On `yes`, clear your state flag so that your dialog will continue next turn. On `no`, call the dialog context's end method. Again, do not continue the dialog this turn, unless you want to assume that a non-yes/no response should be interpreted as the user continuing the dialog flow.

**Step n+2**: Unless the user interrupts the dialog flow again, such as with another question, call the dialog context's continue method.

**Comment by phule80** [comment]
Thanks @JonathanFingold , @Stevenic , @daveta so much for your time on this. I got your idea. It works now .
