### ISSUE TITLE
Bot created with the Bot Builder SDK v4 into an Azure Bot Function

### ISSUE THREAD

**Issue by MarceloRGonc** [microsoft/botbuilder-dotnet#793]
Hi there,

I've been trying to put a bot created with the Bot Builder SDK v4 into an Azure Bot Function, so far unsuccessful, due to problems with dependencies.

My question is at this point the Bot Builder SDK v4 is already supported by the Azure Bot Function? If not, are there any plans for it to be introduced?

Thanks in advance for the help...

**Comment by cleemullins** [comment]
Hey @Andrea-Orimoto, can you chime in with the roadmap here around support for SDKv4? I suspect the issue is .Net Core 2 support, as we bumped into that recently.

**Comment by drub0y** [comment]
Actually we have an open issue around this already in #467 that I suggest you read, but the TL;DR; is that the .NET assembly versioning issues that are common with Azure Functions, due to lack of binding redirects, are a blocker to working with the BBSDK within a function right now. Those still haven't been solved in AF 2.x, and you can [follow along here](https://github.com/Azure/azure-functions-host/issues/992).

**Comment by MarceloRGonc** [comment]
Thanks for the quick answer!

I' ll keep an eye on this for future updates.

**Comment by fcovely** [comment]
I've been learning a lot about bots and the various 'channel's and working with the various offerings from the 3 major cloud vendors, did not include 'big blue' in those 3.  While I think bot framework does a good job in getting one off the ground quickly, there is just no way I want to use anything other than serverless for this.  So I love the bot framework conceptually but after beating my head against a wall for a good week on Azure Functions and Bot SDK 4, I reach the conclusion that MS is ok with going slowly to serverless for obvious profit reasons.  I've been using MS development products since pre Windows 1 (the 'dos days'), and sometimes they get it right the first time but generally it takes way too long.  I'm thinking 'agile' needs to be more in their culture.  I find it odd that 2 major cloud vendors are HQ'd in the Seattle area with such disparate cultures.  No offense intended here, just an observation.

**Comment by artemious7** [comment]
Any progress on this? Or should i stay on Bot Builder SDK v3 with Azure Functions v1?
