### ISSUE TITLE
Hosting V3 Dialogs in V4 issues

### ISSUE THREAD

**Issue by jjshuler** [Microsoft/botbuilder-dotnet#797]
We are attempting to convert a v3 bot to use the v4 code with the Classic compatibility layer. This requires using the full .NET framework with the v4 sdk, but there is near zero documentation on how to do this (everything is .NET core)

1. Should we be switching to using the IBot-style, controllerless root? How does this work in the full framework asp.net?
2. How do we implement persistent storage that is compatible with the V3 dialogs?
The TableBotDataStore from Microsoft.Bot.Builder.Azure seems to be gone. In the Classic codebase I only see one implementation of IBotDataStore<BotData> and it is the in-memory, non-persistent version. The V3 version of Microsoft.Bot.Builder.Azure is incompatible with the Classic library due to (at least) the new namespace on the interface.
The new V4 storage implementations do not implement IBotDataStore<BotData>.

Thanks!

**Comment by drub0y** [comment]
Some thoughts...

1. I would highly suggest this, yes. It abstracts away all the ASP.NET'isms and gives you a simpler surface area for unit testing as well. For full framework there's the `Microsoft.Bot.Builder.Integration.AspNet.WebApi` package which does all the same plumbing work using ASP.NET WebAPI 2.x. There is a sample project showing that kind of project [here in the history of the codebase](https://github.com/Microsoft/botbuilder-dotnet/tree/0fe1f60971e27a83eca822bf136ce8f96110fa6e/samples/Microsoft.Bot.Samples.EchoBot-AspNetWebApi)<sup>1</sup>. NOTE: Since this is older code _some_ of it might not work exactly the same against the newer versions of the core packages, but certainly the ASP.NET startup/configuration logic should be pretty close. Happy to help if you run into anything else, just follow up here.

2) This seems like a gap. @tomlm @cleemullins it seems like we'd want to somehow provide an `IBotDataStore` implementation that just layers over the newer storage APIs so any v4 `IStorage` provider could be configured/used the v4 way and the classic abstraction just works...?

<sup>1</sup> I'm actually surprised to learn this project was deleted, but not replaced by a newer sample. @cleemullins @vishwacsena I think we'll want to get a sample for WebAPI added back to the new samples.

**Comment by jjshuler** [comment]
1. Thanks, I will investigate this.

2. To workaround this issue, I copied the code for TableBotDataStore from the v3 github and updated the namespaces. Code is attached.
[TableBotDataStore.cs.txt](https://github.com/Microsoft/botbuilder-dotnet/files/2241298/TableBotDataStore.cs.txt)

**Comment by jjshuler** [comment]
Thanks, I was successful in switching to the IBot implementation with the caveat mentioned in #797 (4.0.1-preview doesn't work with azure bot service). I have also worked around this.
