### ISSUE TITLE
Cannot get BotState services because by default BotState are tranformed into CachedBotState 

### ISSUE THREAD

**Issue by GhostAtom** [Microsoft/botbuilder-dotnet#807]
Hi, 
At runtime when the key requested doesn't exists in AzureBlobStorage a new CachedBotState is added in the turn services collection. Then I cannot access the original BotState object to create the assessor

`var userState = dc.Services.Get<UserState>();`
or
`var userState = dc.Services[nameof(UserState)] as UserState;`
`userState` is null because of the impossible cast to `BotState.CachedBotState`
`var property = userState.CreateProperty<T>(typeof(T).Name, () => new T());` 

Do you have a best way to retrieve the service and access the properties or did I miss something for instance initialization?
Thanks

**Comment by GhostAtom** [comment]
@drub0y for me it isn't a question but more an issue.
Using the underling private object `CachedBotState` directly in the services collection prevent any use of the `BotState` and the state management methods.

**Comment by GhostAtom** [comment]
@ukphillips in the master branch version this extension doesn't exists.
I created my own extensions but in the implementation I have faced the issues mentioned in this thread.

I managed to tackle this by turning the `CachedBotState` to public.

**Comment by ukphillips** [comment]
Good point. I was just looking and it appears a lot around state has changed quite a bit. Looking at the latest code and the tests, it's definitely a little confusing how to use it. Loading the state sets the service (`CachedBotState` as you mentioned which is private) this doesn't quite feel right, but it would mean that you need that as a public type as you has solved it.

It seems like there should be a more natural way to access the objects outside of the services collection - Like returning the `IDictionary<string, object>` from the LoadAsync method but reserving the `CachedBotState` internally for later hash comparing to avoid unnecessary storage round trips.

**Comment by GhostAtom** [comment]
Sadly I cannot access UserState, ConversationState or a custom BotState actually because of the problem I mentioned, `CachedBotState` is inaccessible.
Anyway `GetPropertyValueAsync` is internal so I would have to do some plumbing with a custom BotState manager.

**Comment by GhostAtom** [comment]
Of course I know that the implementation is not final but I need SSO features...So for now this workaround is good enough for my needs.
Thanks for pointing me to this PR I'll take a look.

**Comment by ukphillips** [comment]
I also ran into the DI and middleware issue (or atleast a dependency of the middleware). As a short term fix, I explicitly resolved it when I created the middleware in configure services:

`services.AddTransient<ITranscriptLogger, CosmosTranscriptLogger>();`
`var sp = services.BuildServiceProvider();`
`var service = sp.GetService<ITranscriptLogger>();`
...
`options.Middleware.Add(new TranscriptLoggerMiddleware(sp.GetService<ITranscriptLogger>()));`



not ideal but it let me side step the issue for now.

**Comment by ukphillips** [comment]
Having pulled down the daily builds I am starting to see with some of the issues caused by the latest changes. Based on a few samples I have seen posted, there is an accessor being registered as a singleton after the bot that wraps the variaous IStatePropertyAccessor<T> properties. This works fine to get the injection to work into the Bot main class, but I think I'm running into the same issue as @GhostAtom where I want to inject that into a piece of middleware. So I end up with something looking like this:

```csharp
services.AddBot<FlexAssistantBot>(options =>
            {
                options.CredentialProvider = new ConfigurationCredentialProvider(Configuration);

                IStorage dataStore = new MemoryStorage();

                options.State.Add(new ConversationState(dataStore));
                options.State.Add(new UserState(dataStore));

                // Forces storage to auto-load on a new message, and auto-save when complete.  
                // Put at the beginning of the pipeline.
                options.Middleware.Add(new BotStateSet(options.State.ToArray()));
                options.Middleware.Add(new CustomMiddleware());
            });

            services.AddSingleton<StateAccessors>(sp =>
            {
                var options = sp.GetRequiredService<IOptions<BotFrameworkOptions>>().Value;
                if (options == null)
                {
                    throw new InvalidOperationException("BotFrameworkOptions must be configured prior to setting up the State Accessors");
                }

                var userState = options.State.OfType<UserState>().FirstOrDefault();
                if (userState == null)
                {
                    throw new InvalidOperationException("UserState must be defined and added before adding user-scoped state accessors.");
                }

                var conversationState = options.State.OfType<ConversationState>().FirstOrDefault();
                if (conversationState == null)
                {
                    throw new InvalidOperationException("ConversationState must be defined and added before adding conversation-scoped state accessors.");
                }

                var accessors = new StateAccessors
                {
                    CustomUserState= userState.CreateProperty<CustomUserState>(nameof(CustomUserState)),
                    CustomConversationState= conversationState.CreateProperty<CustomConversationState>(nameof(CustomConversationState))
                };

                return accessors;
            });
```

So at this point with the same examples I can get my StateAccessors into the bot constructor, but how can I get it into my CustomMiddleware. It has to be registered with a new instance, and I can't register my StateAccessors type until after I have already created the bot (and middleware). 

Specifically using samples from this PR https://github.com/Microsoft/botbuilder-dotnet/pull/809

**Comment by Stevenic** [comment]
So @ukphillips I'm definitely not a C# expert and this part of the code I'm a little less familiar with but let me take a stab at answering your question...

The moment you create ConversationState or UserState you can call `CreateProperty()` to define a property accessor. So you should be able to do something like this:

```C#
services.AddBot<FlexAssistantBot>(options =>
            {
                options.CredentialProvider = new ConfigurationCredentialProvider(Configuration);

                IStorage dataStore = new MemoryStorage();
                var convoState = new ConversationState(dataStore);
                var userState = new UserState(dataStore);

                options.State.Add(convoState);
                options.State.Add(userState);

                var customProp = convoState.CreateProperty("custom");

                // Forces storage to auto-load on a new message, and auto-save when complete.  
                // Put at the beginning of the pipeline.
                options.Middleware.Add(new BotStateSet(options.State.ToArray()));
                options.Middleware.Add(new CustomMiddleware(customProp));
            });
```

If you then needed your bot to have access to the property as well, you would need to use dependency injection to get the accessor into the bot.

**Comment by johnataylor** [comment]
@GhostAtom @ukphillips Just a few comments to close out on this topic.

The starting point and very much the primary abstraction you should be looking at is the accessor. The higher level components, for example, the Dialogs, are coupled only to the accessor. The accessor pattern provides a level of decoupling and significantly some level of name collision avoidance.

As @drub0y points out much of that is internal and you should be focused on the accessor interfaces.

The BotState and CachedBotState classes are ultimately component parts of an implementation of the accessor. There is also plugable model here for different types of physical storage (for example, blob and CosmosDB) but whatever you chose at that level you still get the semantics of BotState.

Incidentally you don't really use BotState directly - instead you subclass it and use that. In the framework you will see subclasses called UserState and ConversationState. In the unit tests you will see more.

The BotState semantics are essentially "last write wins." That might work just fine for you. In a scaled out scenario (in fact, even with multiple concurrent requests) you might observe the implications of the "last write wins" semantics: concurrent state updates can be overwritten. This might not be an issue for you, but if it is, the solution is to implement your own accessor.

If you were to do that you would probably be also implementing some specific logic in your IBot OnTurn, for example, if in your implementation you were to fail a Save because of eTag precondition checks, then you might like to re-fetch the state and retry the logic. In such a scenario you might have also chosen to buffer outbound responses until you see a successful save. There are various alternatives here. However, it is important to understand that this isn't the behavior you get when you use BotState. I'm describing the kind of thing an advanced implementation might decide to do. But given the accessor abstraction such highly involved and complex state solutions can be built. The important point is that they will work with the Dialogs and Middleware.

Another piece that is tied into the BotState world is the AutoSaveStateMiddleware. The idea here is that the BotState accessors support a somewhat hidden lazy load with the middleware supporting a somewhat hidden and optimized save. Just add the middleware and you get the save happening, hence the name "auto." The load is lazy in the sense that it only happens when you actually first call the Set, Get or Delete on the accessor. The save is optimized in a couple of ways: firstly it attempts to only save when things have changed and secondly it attempts to perform multiple BotState saves in parallel.

The AutoSaveStateMiddleware makes a lot of sense when you chose to play with state inside of your own Middleware components. If you don't have any such components in play then there is no difference between using this and adding the SaveChanges calls to the end of your OnTurn logic.

Hopefully this explanation of some of the moving parts was helpful.
