### ISSUE TITLE
Module dialogs and dependency injection

### ISSUE THREAD

**Issue by vcardins** [Microsoft/botbuilder-dotnet#860]
Hello,
I want to use modular dialogs but I need to inject a dependency. (I followed the article https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol where it returns an instance of the Dialog.)
Here is what I tried and worked, but I'm not sure is the right approach. Any advice?

```csharp
public MyDialog(IServiceProvider serviceProvider) {
		Add(FirstFlow.Id, FirstFlow.GetInstance(serviceProvider));
		...
}
```
and

```csharp
public class FirstFlow: DialogContainer
	{
		public const string Id = "firstFlow";
		private const string FirstFlowKey = "FirstFlow";
		private static Instance;
		
		public static FirstFlow GetInstance (IServiceProvider serviceProvider) {
			if (Instance == null)
			{
				Instance = new FirstFlow(serviceProvider);
			} 
			return Instance;
		}

		private FirstFlow(IServiceProvider serviceProvider) : base(Id) {
			Dialogs.Add(
		}
		...
}
```

**Comment by cleemullins** [comment]
@EricDahlvang - Can you please take a look at this and see if you've got any ideas? What's here seems fine.

**Comment by EricDahlvang** [comment]
I believe the dependency injection method you have here is correct, except I don't think there should be a static instance of the **DialogContainer**.  I've been in contact with the docs writers, and that page will be updated soon.

Since **DialogContainer** (now named **DialogSet**) contains dialogs and now takes a property accessor, it should be constructed on every turn, like in this example: https://github.com/Microsoft/BotBuilder-Samples/blob/v4/csharp_dotnetcore/5.MultiTurn-Prompts-Bot/MultiTurnPromptsBot.cs#L42

Something like this:
```cs
public MyDialog(IServiceProvider serviceProvider) {
     Add(FirstFlow.Id, new FirstFlow(serviceProvider));
     ...
}
public class FirstFlow: DialogContainer
{
public const string Id = "firstFlow";
private const string FirstFlowKey = "FirstFlow";

private FirstFlow(IServiceProvider serviceProvider) : base(Id) {
			Dialogs.Add(
}
```

**Comment by drub0y** [comment]
So where does that `IServiceProvider` instance come from? Is it the root instance or are you starting a scope somewhere with `CreateScope`? I suspect it's the former.

The problem you're going to run into if it is indeed the root instance is that any transient services that you resolve via that provider are going to "leak" on each turn because the root provider will not be disposed until the process exits. If everything is singleton**¹**, you're not going to have a problem, but... beware.

To be totally clear: the way the framework is designed right now, unless you're instantiating your dialog tree on every single turn (which can be costly) and creating a scoped `IServiceProvider` for yourself you're not going to get the typical DI lifecycle behavior you would expect.

**¹** Or scoped... because, when resolving from the root container, they implicitly become singletons.

**Comment by johnataylor** [comment]
You can dependency inject the dialog class you are using. When using dialogs the key thing to do is write a custom dialog that subclasses ComponentDialog. It's ComponentDialog that brings in the modularization.

You might be able to dependency inject your custom dialog object (as a singleton) in fact this sample does just that for a dialog called RootDialog:

https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/42.scaleout/Startup.cs

The point is the component dialog object itself doesn't have to have the runtime state.
