### ISSUE TITLE
Fit and finish: CancellationToken and ITurnContext parameter names

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#867]
Can we settle on a fixed name to use for the CanellationToken and the ITurnContext parameters?

It's low priority, but it would make writing the docs easier.

| Parameter name | Count |   | Parameter name | Count |
| :-- | --: | -- | :-- | --: |
| cancellationToken | 164 |   | context | 90 |
| ct | 5 |   | turnContext | 12 |
| cancelationToken | 1 |   | v4Context | 4 |
| token | 103 |   |   |  |

PS. I'll be fixing the one typo shortly.

**Comment by drub0y** [comment]
My votes and reasoning...

 * `cancellationToken` - obvious IMHO because there's precedent in .NET framework already
 * `turnContext` - for me `context` is just too abstract and when you start working with dialogs you immediately have (much to my dismay) _two_ contexts to deal with and then you're always trying to figure out which is which.  

On a related note, I would _strongly_ urge renaming `DialogContext::Context` to `DialogContext::TurnContext` because seeing `context.Context` written in code is just... _really_ hard to even fathom explaining that to people for the next _N_ years. Bigger picture I would propose implementing `DialogContext` completely differently, but I think that ship may have sailed at this point.

**Comment by johnataylor** [comment]
all done
