### ISSUE TITLE
BotBuilder CI packages don't work with ASPNet Projects

### ISSUE THREAD

**Issue by RamjotSingh** [Microsoft/botbuilder-dotnet#880]
I noticed that the CI packages which are published daily don't work with ASPNet. The packages can be installed but the dll references are missing from the projects.

This however does not repro on packages created on machine.

**Comment by drub0y** [comment]
That's strange. 🤔 ASP.NET WebAPI or ASP.NET Core? I actually just did a File->New Project ASP.NET Core empty web app, added the nightlies and have no problem. Any chance you can zip up a repro and throw it somewhere I can grab it to see what's going on? Otherwise I'll have to ask you a bunch of other questions about the project's settings, so that could save us both some time.

**Comment by tomlm** [comment]
There was a break in our build scripts which weren't building one of the libraries, Can you try again?

**Comment by RamjotSingh** [comment]
The libraries were there. ASPNET project was not adding them though. I was forced to add them manually. NetCore works fine.

**Comment by drub0y** [comment]
Ah you mean for a .NET full framework project? What version of FF is your ASP.NET project? 4.7.2??

**Comment by cleemullins** [comment]
@RamjotSingh I beleive this is resolved, and the projects are all building. WE have samples being build using both WebAPI and ASP.Net Core 2, all based off the daily build feed. If anything here is still broken, please re-open this.
