### ISSUE TITLE
BotConfiguration does not have a LoadSync() method

### ISSUE THREAD

**Issue by sgellock** [Microsoft/botbuilder-dotnet#902]
This exists in the NodeJS implementation

**Comment by drub0y** [comment]
Errr, that's because that's not how you would do it in .NET, right? .NET has a specific configuration story and I would argue you want to follow that, so you would load a `BotConfiguration` from config using the built in configuration APIs.

In .NET Core the simplest solution for this would be to treat it as an `IOptions<T>`. In fact, I had tested this a while back when I was first writing the integration lib and I'm pretty sure it already works. We would want to research this further tho 'cause I think there are some types on `BotConfiguration` these days that are not easily expressed from a configuration perspective (e.g. non-intrinsitc types). For that we'd just need to explore whether or not we want to write some type converters.

For .NET FF (i.e. WebAPI) we'd just want to add a custom `ConfigurationSection` into that box.

**Comment by carlosscastro** [comment]
Fix merged.
