### ISSUE TITLE
potential concurrency problems in bot.builder

### ISSUE THREAD

**Issue by johnataylor** [Microsoft/botbuilder-dotnet#949]
From code review, looks like:
- TurnContextStateCollection
- BotState.CachedBotState

should both be using ConcurrentDictionary and not Dictionary
(Note Dictionary is thread safe for read but not write.)

**Comment by drub0y** [comment]
Hmmm... under what scenario should `TurnContextStateCollection` have to be worried about being accessed by multiple threads? It's 1:1 with a `TurnContext` which is, by definition, specific to a single turn. 

If downstream logic actually executes code in parallel that logic needs to worry about serializing access to the collection. Just making everything use a `ConcurrentDictionary<,>` to be defensive comes at a cost as `ConcurrentDictionary<,>` obviously has additional overhead to help guarantee thread safety.

Don't make everyone pay the tax for a few; let those few who may introduce concurrency into their code deal with serializing access back to the `TurnContext` themselves.

Finally, as prior art, look at the design of ASP.NET's `HttpContext`. Its child collections (e.g. `Items)` are not thread safe because they've taken this same stance.

**Comment by johnataylor** [comment]
@drub0y yes that is what @cleemullins said when he saw this yesterday. We'll fix the BotState code (note the cache is a singleton) and leave it to the developer to worry about the TurnContext.

**Comment by johnataylor** [comment]
checked in

**Comment by drub0y** [comment]
Instances of `CachedBotState` are created on every turn as well, so I still don't understand why that needed to be changed to use `ConcurrentDictionary<,>`.

**Comment by johnataylor** [comment]
OK, I guess that would make sense. It seems all a little sketchy having this hidden cache there, especially one that isn't thread safe. I'm not sure I wouldn't be surprised by some of the behavior of the state.

Anyhow, one of the agendas of moving business logic out of direct inline implementation in OnTurn is so that business logic becomes a step more decouped from state.

**Comment by johnataylor** [comment]
We're going to leave this for now.
