### ISSUE TITLE
Bug in c# context.Reply update

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-dotnet#96]
re: [#92](https://github.com/Microsoft/botbuilder-dotnet/pull/92), fix for [#76](https://github.com/Microsoft/botbuilder-dotnet/issues/76)

The following code:
```csharp
            var activity = Activity.CreateMessageActivity();
            var attachment = new Attachment()
            {
                ContentUrl = "http://example.com/sample.jpg",
                ContentType = "image/jpg"
            };
            activity.Attachments.Add(attachment);

            // Send the activity as a reply to the user.
            context.Reply(activity);
```
Generates on the context object the following response object, which is missing key information: `channelData`, `channelId`, `conversation`, `from`, `replyToId`, and `serviceUrl`. This causes a null argument exception in BotFrameworkAdapter.cs line 47.
```json
[
  {
    "type": "message",
    "id": null,
    "timestamp": null,
    "localTimestamp": null,
    "serviceUrl": null,
    "channelId": null,
    "from": null,
    "conversation": null,
    "recipient": null,
    "textFormat": null,
    "attachmentLayout": null,
    "membersAdded": null,
    "membersRemoved": null,
    "reactionsAdded": null,
    "reactionsRemoved": null,
    "topicName": null,
    "historyDisclosed": null,
    "locale": null,
    "text": null,
    "speak": null,
    "inputHint": null,
    "summary": null,
    "suggestedActions": null,
    "attachments": [
      {
        "contentType": "image/jpg",
        "contentUrl": "http://example.com/sample.jpg",
        "content": null,
        "name": null,
        "thumbnailUrl": null
      }
    ],
    "entities": [],
    "channelData": null,
    "action": null,
    "replyToId": null,
    "value": null,
    "name": null,
    "relatesTo": null,
    "code": null,
    "expiration": null,
    "importance": null,
    "deliveryMode": null,
    "textHighlights": null
  }
]
```

**Comment by cleemullins** [comment]
As things sit now, we have the following:
1. The CreateMessageActivity() creates an empty Activity type 'type=message'.
2. You set the .text field, and hit send. 
3. The lower layers are NOT setting the remaining fields. 

This is deliberate, although probably not a good choice overall. As far as I can tell, the current JS SDK works this way as well. 

The code in the text-based Context.Reply creates the message this way:
```
            var reply = this.ConversationReference.GetPostToUserMessage();
            reply.Text = text;
```

The Activity that's created that way has all of the relevant fields filled out, as they're all present on the ConversationReference (which is, afterall, just a bookmark into a conversation). 

**We should alter the SDK to make the code you posted work, as most developers will do exactly what you did. Your code is reasonable and obvious.** 

Some possibilities include:

1. Changing the behavior of Context.Reply() to inspect the Activity and fill out the relevant fields if they're not set. 
2. Requiring the ConversationReference to be passed into the CreateMessageActivity() method, so that method fills out the field. 
3. Creating an in-between method "BindActivityToConversation(activity, conversationReference) that does this on your behalf. 

#1 above seems the cleanest. 

Thoughts?

**Comment by johnataylor** [comment]
Yes I think we could help the user here a little more. I would have thought (1) would work - its basically less API. But does that cover all cases?

**Comment by Stevenic** [comment]
So @cleemullins ... If you look at the `Bot.post()` code below from the JS SDK you'll see that we apply the conversation reference to all activities before sending them through `postActivity`. The middleware and adapter sees well formed and properly addressed activities:

```JavaScript
    public post(context: BotContext, ...activities: Partial<Activity>[]): Promise<ConversationReference[]> {
        // Ensure activities are well formed.
        for (let i = 0; i < activities.length; i++) {
            let activity = activities[i];
            if (!activity.type) {
                activity.type = ActivityTypes.message
            }
            applyConversationReference(activity, context.conversationReference);
        }

        // Run post activity pipeline
        const adapter = this.adapter;
        return this.postActivity(context, activities, function postActivities() {
            // Post the set of output activities
            return adapter.post(activities)
                .then((responses) => {
                    // Ensure responses array populated
                    if (!Array.isArray(responses)) {
                        responses = [];
                        for (let i = 0; i < activities.length; i++) { responses.push({}) }
                    }
                    return responses;
                });
        });
    }
```

**Comment by cleemullins** [comment]
@Stevenic 
👍👍👍👍👍

I'm adopting that same now in the C# SDK. 

More alignment is good!

**Comment by cleemullins** [comment]
Resolved by PR.
