### ISSUE TITLE
Inflexible Configuration for Bot Connected Services

### ISSUE THREAD

**Issue by punitganshani** [Microsoft/botbuilder-dotnet#997]
So with new SDK, there are 3 different places a developer needs to maintain configuration-

1. We have `BotConfiguration.Load` that reads configuration from a JSON file, where we have to define bot endpoint and connected services. Does this method support `KeyVault` integration to secure secrets, or configuration through PowerShell for automated deployments?

2. We have ASP.NET Core configuration which is supported out of the box for any configuration that bot may need, or the overall project/services may need. This uses a much mature way of handling configuration. Can't there be any mechanism to use this with `BotConfiguration.Load` method? Let's say read a particular Section that defines Bot Configuration using a `IOptions` mechanism

3. The third is emulator configuration file. This also has endpoint secrets.

I, somehow think, the SDK should provide a mechanism to provide IConfigurationProvider rather than enforce us to define configuration in a separate `.bot` file. The current one is very inflexible model of configuration.

**Comment by benbrown** [comment]
You can manage your configuration secrets in whatever manner you prefer.  

However, the .bot file is useful for using the Bot Framework Emulator and other integrated tools.

**Comment by benbrown** [comment]
We'd love to see potential solutions for this. Submit a pull request!

**Comment by MattLavalleeMA** [comment]
I, too, found this clunky and _"not so great"_ because it's persisting secrets in files.  I wrote a class that uses Azure Key Vault (inheriting BotConfiguration); I'm a little worried about the "Location" attribute pegged in there (maybe Emulator uses it?), but so far it's been fine in a .NET Core project.  Happy to backport it into BotConfiguration, if interested, but do you want to drag-in the KV dependencies?
